### PR TITLE
chore: Add multi browser testing via Sauce Labs 

### PR DESCRIPTION
**Pull request by Shegox**
#### Please provide a link to the associated issue.
N/A
#### Please provide a brief summary of this pull request.
This PR implements a demo implementation of running Tests on a matrix of Browser via a remote selenium grid ([Sauce Labs](https://saucelabs.com)) inside the master branch. Tests can be only executed if the requester is trusted, as otherwise the Sauce Labs credentials may be leaked (e.g. [on Pull Request builds from forks](https://docs.travis-ci.com/user/pull-requests/#pull-requests-and-security-restrictions)). 

To run test from your local environment run: 
```bash
export SAUCE_USERNAME=xxx
export SAUCE_ACCESS_KEY=xxx
export SAUCE_REGION=eu # or us
export KARMA_PARALLEL_EXECUTERS=1
# Execute the default remote browser matrix defined in the package.json for the core lib
npm run test:saucelabs -- core
# Execute the default remote browser matrix defined in the package.json for the platform lib
npm run test:saucelabs -- platform
```

Before merging this, following settings should be given as secret environment variables inside Travis to ensure that Travis can access SauceLabs.
Environment variables:
- `SAUCE_USERNAME`: the username of the Sauce Labs user used
- `SAUCE_ACCESS_KEY`: the access key from Sauce Labs
- `SAUCE_REGION`: the Sauce Labs region (`eu` or `us`) to be used for spinning up browsers (optional; defaults to `us`)
- `KARMA_PARALLEL_EXECUTERS`: manages in how many shards the test specs get split. For running on Sauce Labs `1` makes sense as the longest time is used for transferring the tests to the browser.

An example Travis build can be seen here: https://travis-ci.org/github/Shegox/fundamental-ngx/builds/715485187
The recordings in Sauce Labs from that Travis build: https://app.eu-central-1.saucelabs.com/builds/5529973f4b24423ab5bac2331ea48f3a

Currently some tests fail in Firefox and Safari and need to be potentially addressed. For the beginning it may make sense to only use `--browsers=SL_Edge,SL_Chrome` until the issues with the tests in Firefox/Safari are resolved.
 
#### Please check whether the PR fulfills the following requirements

- [x] the commit message follows the guideline:
https://github.com/SAP/fundamental-ngx/blob/master/CONTRIBUTING.md
- [x] tests for the changes that have been done
- [x] all items on the PR Review Checklist are addressed :
https://github.com/SAP/fundamental-ngx/wiki/PR-Review-Checklist

Documentation checklist:
- [x] update `README.md`: N/A
- [x] [Breaking Changes Wiki](https://github.com/SAP/fundamental-ngx/wiki/Breaking-Changes): N/A
- [x] Documentation Examples: N/A
- [x] Stackblitz works for all examples: N/A

### CODE REVIEW

**Comment by salarenko** [comment]
@Shegox I think you run you PR right in the moment when `npm` was down for a while.
image

**Comment by Shegox** [comment]
I pushed now again and this should trigger all builds again. Hopefully npm is working smooth in the meantime again.

**Comment by sKudum** [comment]
Hi Tobias, as discussed, when I ran it is not executing typescript specs in browsers. Eyal has arranged a meeting for this with Wim on 12th hope we will get a clue on this to proceed further.

**Comment by sKudum** [comment]
Closing it, as it was raised for testing purposes from sauce lab contact member.

**Pull request closed without merging**
