### PR TITLE
fix: (Core) Add missed controls into Pagination component and fix small issue

### PR DESCRIPTION
**Pull request by mykolavorobiov**
#### Please provide a link to the associated issue.
[3764](https://github.com/SAP/fundamental-ngx/issues/3764)

#### Please provide a brief summary of this pull request.

Implement new functionality for `items per page`. 
Also fixed 
- [3742](https://github.com/SAP/fundamental-ngx/issues/3742)
- [3126](https://github.com/SAP/fundamental-ngx/issues/3126)

#### Please check whether the PR fulfills the following requirements

- [x] the commit message follows the guideline:
https://github.com/SAP/fundamental-ngx/blob/main/CONTRIBUTING.md
- [x] tests for the changes that have been done
- [x] all items on the PR Review Checklist are addressed :
https://github.com/SAP/fundamental-ngx/wiki/PR-Review-Checklist

Documentation checklist:
- [x] update `README.md`
- [x] [Breaking Changes Wiki](https://github.com/SAP/fundamental-ngx/wiki/Breaking-Changes)
- [x] Documentation Examples

### CODE REVIEW

**Review by mikerodonnell89 — CHANGES_REQUESTED** [review]
The "pagination with custom showing template" example code is just the same as the default pagination example 

Screen Shot 2020-12-28 at 6 17 43 PM

**Review by droshev — APPROVED** [review]

**Review by mikerodonnell89 — APPROVED** [review]

**Comment by stefanoScalzo** [comment]
Screen Shot 2021-01-04 at 11 12 03 AM
the number 4 should be shown

**Comment by stefanoScalzo** [comment]
Screen Shot 2021-01-04 at 11 14 07 AM
2 and 6 should both be shown if were limiting to 7 numbers

**Review by Betrozov — APPROVED** [review]

**Review by JKMarkowski — APPROVED** [review]
LGTM

**Pull request merged**
