### PR TITLE
docs: stop showing side bar on resize

### PR DESCRIPTION
**Pull request by JKMarkowski**
#### Please provide a link to the associated issue.
fixes: https://github.com/SAP/fundamental-ngx/issues/2881
#### Please provide a brief summary of this pull request.
There is fixed behaviour of sidebar, which now doesn't collapse/expand always when it's being resized.
Now, when window approach less than 560px, it will be hidden
#### Please check whether the PR fulfills the following requirements

- [x] the commit message follows the guideline:
https://github.com/SAP/fundamental-ngx/blob/master/CONTRIBUTING.md
- [x] tests for the changes that have been done
- [x] all items on the PR Review Checklist are addressed :
https://github.com/SAP/fundamental-ngx/wiki/PR-Review-Checklist

Documentation checklist:
- [x] update `README.md`
- [x] [Breaking Changes Wiki](https://github.com/SAP/fundamental-ngx/wiki/Breaking-Changes)
- [x] Documentation Examples
- [x] Stackblitz works for all examples

### CODE REVIEW

**Comment by droshev** [comment]
@JKMarkowski can we condense the menu while resizing the screen?
sidenav

**Comment by JKMarkowski** [comment]
@droshev I changed breakpoint, so now it closes on <~980px
985px

**Comment by mikerodonnell89** [comment]
Thanks, this has been really bugging me

**Comment by droshev** [comment]
@JKMarkowski i will merge it as the issue is very annoying :) 
🥳

**Pull request merged**
