### PR TITLE
fix: remove product switch bullets

### PR DESCRIPTION
**Pull request by stefanoScalzo**
#### Please provide a link to the associated issue.
fixes: #2164
#### Please provide a brief summary of this pull request.

- This PR will fix the bullets on the product switch. 
- It needs to be done in NGX because it is not strictly following the styles template for the drag and drop option. 
- Fundamental-React and Vue would also need to be notified

#### Please check whether the PR fulfills the following requirements

- [x] the commit message follows the guideline:
https://github.com/SAP/fundamental-ngx/blob/master/CONTRIBUTING.md
- [x] tests for the changes that have been done

Documentation checklist:
- [x] update `README.md`
- [x] [Breaking Changes Wiki](https://github.com/SAP/fundamental-ngx/wiki/Breaking-Changes)
- [x] Documentation Examples
- [x] Stackblitz works for all examples

Screen Shot 2020-03-19 at 9 15 31 AM
Screen Shot 2020-03-19 at 9 15 47 AM

### CODE REVIEW

**Comment by stefanoScalzo** [comment]
> Please add meaningful title for the PR and follow the Contribution guidelines.

fixed

**Comment by stefanoScalzo** [comment]
> @stefanoScalzo it is good you reformatted the code but i think this should happen in a separate PR.
> Can you keep only the fix in this one?

fixed

**Comment by rengare** [comment]
@stefanoScalzo please attach before and after screenshots

**Comment by stefanoScalzo** [comment]
> @stefanoScalzo please attach before and after screenshots

Because stackblitz only goes off of merged PRs and latest pre releases I posted screenshots showing what happens when u remove the docs styling. In mine, there are no docs stying

**Pull request merged**
