### PR TITLE
fix: (Core) add fix for missing styling of selected Tabs

### PR DESCRIPTION
**Pull request by katekozlowska**
#### Please provide a link to the associated issue.

part of https://github.com/SAP/fundamental-ngx/issues/3922

#### Please provide a brief summary of this pull request.

This PR brings temporary solution, semantic colors should be fixed in fundamental-styles. 
Issue connected with changes from PR: [#1865](https://github.com/SAP/fundamental-styles/pull/1865).

#### Please check whether the PR fulfills the following requirements

- [x] the commit message follows the guideline:
https://github.com/SAP/fundamental-ngx/blob/master/CONTRIBUTING.md
- [x] tests for the changes that have been done
- [x] all items on the PR Review Checklist are addressed :
https://github.com/SAP/fundamental-ngx/wiki/PR-Review-Checklist

### CODE REVIEW

**Comment by JKMarkowski** [comment]
This changed brings color bug from styles, which I think should be fixed on styles and temporary added into this PR, to `tabs.scss`
image

**Review by JKMarkowski — CHANGES_REQUESTED** [review]
Looks good! But nav mode tabs with routerLink still don't have active indicator.
Could you try to make them work without bringing breaking changes?
image

Also could you put labels/milestone etc into this PR?

**Review by JKMarkowski — CHANGES_REQUESTED** [review]
Looks Good! but Icon only / process / filter mode still doesn't work with template&routerLink
image

**Comment by mikerodonnell89** [comment]
The routerlink examples don't show the tab selected until after click - intentional?

**Comment by katekozlowska** [comment]
> The routerlink examples don't show the tab selected until after click - intentional?

Yes, by default there is no tab selected via routerLink

**Comment by JKMarkowski** [comment]
Icon Tab and Process tab with routerLink doesn't have underline
image
image

Filter mode doesn't have underline in both modes + parent tab doesn't have highlight
image

**Review by JKMarkowski — APPROVED** [review]
LGTM

**Review by InnaAtanasova — APPROVED** [review]

**Pull request merged**
