### PR TITLE
fix(platform): should be able to reset form components

### PR DESCRIPTION
**Pull request by Betrozov**
## Related Issue.
Closes https://github.com/sap/fundamental-ngx/issues/6781

## Description
Some of the components are not being visually reset when using `setValue(null)` or `reset()` on the reactive form.
Affected components:
- combobox
- multi-combobox
- number step input
- textarea
- slider

##### During Implementation
1. Visual Testing:
- [x] visual misalignments/updates
- [x] check Light/Dark/HCB/HCW themes
- [x] RTL/LTR - proper rendering and labeling
- [x] responsiveness(resize)
- [x] Content Density (Cozy/Compact/(Condensed))
- [x] States - hover/disabled/focused/active/on click/selected/selected hover/press state
- [x] Interaction/Animation - open/close, expand/collapse, add/remove, check/uncheck
- [x] Mouse vs. Keyboard support
- [x] Text Truncation
2. API and functional correctness
- [x] check for console logs (warnings, errors)
- [x] API boundary values
- [n/a] different combinations of components - free style
- [x] change the API values during testing
3. Documentation and Example validations
- [n/a] missing API documentation or it is not understandable
- [n/a] poor examples
- [x] Stackblitz works for all examples
4. Accessibility testing
5. Browser Testing - Edge, Safari, Chrome, Firefox

##### PR Quality
- [x] the commit message(s) follows the guideline:
https://github.com/SAP/fundamental-ngx/blob/main/CONTRIBUTING.md
- [x] tests for the changes that have been done
- [x] all items on the PR Review Checklist are addressed :
https://github.com/SAP/fundamental-ngx/wiki/PR-Review-Checklist
- [n/a] Run npm run build-pack-library and test in external application
- [n/a] update `README.md`
- [n/a] [Breaking Changes Wiki](https://github.com/SAP/fundamental-ngx/wiki/Breaking-Changes)

### CODE REVIEW

**Review by platon-rov — APPROVED** [review]

**Review by mikerodonnell89 — CHANGES_REQUESTED** [review]
Tested on all these components and it works well but I am seeing some new console errors with the multi-combobox, maximum call stack size exceeded errors etc

**Comment by dmitry-stepanenko** [comment]
Hey, @mikerodonnell89 , thanks for reviewing. Fixed that issue

@platon-rov looks like the issue that sneaked in is related to what' I've done to address this your comment https://github.com/SAP/fundamental-ngx/pull/6832#discussion_r724032093. So I've separated methods again. Probably it stopped working because of some other changes I was doing to form components

**Review by N1XUS — APPROVED** [review]

**Review by mikerodonnell89 — CHANGES_REQUESTED** [review]
Now when the page initially loads, selected tokens are not visible in the multicombobox until the input is clicked:

Screen Shot 2021-11-04 at 9 46 41 AM

**Comment by dmitry-stepanenko** [comment]
@mikerodonnell89 switched to "detectChanges" in the method where suggestions are set. Also verified this will never appear in other scenarios.

**Comment by Seamoo13** [comment]
- [ ] 1. multi-combobox mobile mode example: not  able to open mobile example dialog

https://user-images.githubusercontent.com/47522152/141291434-40fcb987-2fc5-4217-b38a-e328526ecdf5.mp4

**Comment by Seamoo13** [comment]
- [ ] 1. plaftorm multi-combobox: case where not all tokens appear
**STR**
1. go to the mobile multi-combobox example
2. open the mobile multi-combobox
3. choose a couple items and click save
4. open the multi-combobox again
5. use the search field to search for another option and select it
6. click save
7. look at results

**Actual results:** only the searched for token appears, all other selected options not shown as tokens BUT do show in the selected output object

https://user-images.githubusercontent.com/47522152/141970923-13eaf4d0-7c53-458d-8fe8-2b047ed22896.mp4



**Expected results:** all selected items will appear as tokens 

- [ ] 2. platform multi-combobox: case where selected items removed on save
**STR**
1. go to the mobile multi-combobox example
2. open the mobile multi-combobox
3. choose a couple items and click save
4. open the multi-combobox again
5. use the search field to search for another option and select it
6. click save
7. open the multi-combobox again
8. look at selected items (should be the ones you initiallu selected and the searched item selected)
9. click save
10. check output

**Actual results:** items which were originally selected are gone and only searched item appears (both as token and selected output)

https://user-images.githubusercontent.com/47522152/141971759-9d1993cd-7779-4294-aa8e-c2e066598d34.mp4

**Expected results:** all selected items will appear as tokens and in selected output

**Pull request merged**
