### PR TITLE
fix(platform): fix failing unit tests

### LINKED ISSUE #3613: Bug. Platform unit tests are failing in the Safari 13.1 (ObjectStatusComponent, Advanced Textarea, InfoLabelComponent, InputGroup component)
#### Is this a bug, enhancement, or feature request?
Bug
#### Briefly describe your proposal.
Platform. 4 unit tests are failing in the Safari 13.1
#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use the current version.)
Angular CLI: 10.0.5
Fundamental Library: 0.23.0-rc.7

#### If this is a bug, please provide steps for reproducing it.
To reproduce run platform unit tests in the Safari browser on you local OR 
To reproduce using sauce labs: checkout https://github.com/AntonOlkhovskyi/fundamental-ngx/tree/feature/setup-saucelabs-integration
In the package.json update test:platform:saucelabs with 
SAUCE_USERNAME='YOU_SAUCE_USERNAME' SAUCE_ACCESS_KEY='YOUR_SAUCE_ACCESS_KEY'
Make sure it is bind to the EU Central 1 data center.
In karma.conf-ci.js comment all but sl_safari_macOS browsers in the customLaunchers obj. 
#### Please provide relevant source code if applicable.
TOTAL: 4 FAILED, 273 SUCCESS

1) Should Validate diffrent object states and icon
     ObjectStatusComponent
     Expected false to be true.

2) should handle call autogrow for any other keypress
     Advanced Textarea
     Expected '57px' to be '60px'.

3) Should Add label with color
     InfoLabelComponent
     Expected false to be true.

4) Should render children in the order that they are placed
     InputGroup component
     Expected false to be truthy.

### PR DESCRIPTION
**Pull request by aberikashvili**
#### Please provide a link to the associated issue.
Closes #3613

#### Please check whether the PR fulfills the following requirements

- [x] the commit message follows the guideline:
https://github.com/SAP/fundamental-ngx/blob/main/CONTRIBUTING.md
- [x] tests for the changes that have been done
- [x] all items on the PR Review Checklist are addressed :
https://github.com/SAP/fundamental-ngx/wiki/PR-Review-Checklist
- [ N/A] Run npm run build-pack-library and test in external application

Documentation checklist:
- [ N/A] update `README.md`
- [ N/A] [Breaking Changes Wiki](https://github.com/SAP/fundamental-ngx/wiki/Breaking-Changes)
- [ N/A] Documentation Examples
- [x] Stackblitz works for all examples

### CODE REVIEW

**Comment by Smiranin** [comment]
Pls fix PR checks and remove extra changes from package-lock.json

**Review by Betrozov — CHANGES_REQUESTED** [review]
please remove package-lock.json  from PR

**Comment by aberikashvili** [comment]
@Smiranin @Betrozov removed package-lock

**Review by Betrozov — APPROVED** [review]

**Review by InnaAtanasova — APPROVED** [review]

**Review by platon-rov — APPROVED** [review]

**Review by mikerodonnell89 — APPROVED** [review]
There are now some merge conflicts but this looks good

**Comment by platon-rov** [comment]
Please take a look into the failing Travis.

**Comment by Smiranin** [comment]
Pls, fix travis and sign cla.

**Review by Smiranin — APPROVED** [review]

**Pull request merged**
