### PR TITLE
docs(core): remove wrong button state example

### PR DESCRIPTION
**Pull request by droshev**
enhance the button state doc with references related to #6206 Issue 1

### CODE REVIEW

**Review by InnaAtanasova — APPROVED** [review]

**Comment by InnaAtanasova** [comment]
Screen Shot 2021-09-15 at 10 02 13 AM

Source: https://codepen.io/stevef/post/short-note-on-the-disabled-attribute


`disabled`: The disabled attribute often appears a little bit dimmed or transparent. By using the tabulator key and navigating within a form the screen readers will ignore the existence of any disabled button. The screen reader doesn't ever reach the button, then he will never indicate that there's a button.

With `aria-disabled` the screen reader will get the fact that there is a button - by navigating through the page with the tabulator - and it will tell the user that it's dimmed (VoiceOver) or disabled (ChromeVox).

Source: https://a11y-101.com/development/aria-disabled

**Comment by InnaAtanasova** [comment]
Reading more about `disabled` state I think we should not change anything in our documentation. 
As per MDN web docs "[The Boolean disabled attribute, when present, makes the element not mutable, focusable, or even submitted with the form. The user can neither edit nor focus on the control, nor its form control descendants. If the disabled attribute is specified on a form control, the element and its form control descendants do not participate in constraint validation. Often browsers grey out such controls and it won't receive any browsing events, like mouse clicks or focus-related ones.](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/disabled)", which is exactly what our example is doing. 

As for aria-disabled, this is what w3 says: "[Disabled elements might not receive focus from the tab order. For some disabled elements, applications might choose not to support navigation to descendants. In addition to setting the aria-disabled attribute, authors SHOULD change the appearance (grayed out, etc.) to indicate that the item has been disabled.](https://www.w3.org/TR/wai-aria-1.0/states_and_properties#aria-disabled)"

`aria-disabled` is used for elements that do not natively support disabled. Button component supports natively disabled and should use is. img tag needs to use aria-disabled and be styled properly.

**Comment by InnaAtanasova** [comment]
Here's an interesting discussion about disabled state:
https://ux.stackexchange.com/questions/103239/should-disabled-elements-be-focusable-for-accessibility-purposes

**Review by Betrozov — APPROVED** [review]

**Review by Smiranin — APPROVED** [review]

**Review by InnaAtanasova — APPROVED** [review]

**Comment by droshev** [comment]
@InnaAtanasova i reverted the example and added the 2 links from Mozilla as a reference

**Pull request merged**
