### PR TITLE
fix: (Core) create card footer by using bar component

### PR DESCRIPTION
**Pull request by DeepakSap14**
#### Please provide a link to the associated issue.
#3929 

#### Please provide a brief summary of this pull request.
This PR uses the correct bar component for creating card footer.
Css has been moved to fundamental-styles.

#### Please check whether the PR fulfills the following requirements

- [x] the commit message follows the guideline:
https://github.com/SAP/fundamental-ngx/blob/main/CONTRIBUTING.md
- [x] tests for the changes that have been done
- [x] all items on the PR Review Checklist are addressed :
https://github.com/SAP/fundamental-ngx/wiki/PR-Review-Checklist
- [x] Run npm run build-pack-library and test in external application

Documentation checklist:
- na update `README.md`
- na [Breaking Changes Wiki](https://github.com/SAP/fundamental-ngx/wiki/Breaking-Changes)
- [x] Documentation Examples
- [x] Stackblitz works for all examples

### CODE REVIEW

**Comment by mikerodonnell89** [comment]
It looks like this footer is cozy (even thought the buttons are compact) and the previous one was compact, is this intended?

New: (40px height)
Screen Shot 2021-04-13 at 9 29 58 AM

Old: (33px height)
Screen Shot 2021-04-13 at 9 32 19 AM

**Review by InnaAtanasova — CHANGES_REQUESTED** [review]
Hi @DeepakSap14 can you point me to the documentation part where Card footer is mentioned?

**Comment by InnaAtanasova** [comment]
The PR title is not correct (missing scope).
The PR template should have the keywords `fixes` or `closes`

**Comment by DeepakSap14** [comment]
Need to raise PR for breaking change when card-footer is removed.
will raise this PR again, once above is merged.

**Pull request closed without merging**
