### PR TITLE
test: comment randomly failing slider  unit test

### PR DESCRIPTION
**Pull request by droshev**
comment randomly failing slider  unit test - issue for addressing it #4893

### CODE REVIEW

**Comment by nikvalor** [comment]
Project: null CORE 
 Url: null 
 This link will expire at

**Comment by nikvalor** [comment]
Project: null Platform B
 Url: null 
 This link will expire at

**Comment by nikvalor** [comment]
Project: null Platform A 
 Url: null 
 This link will expire at

**Review by mikerodonnell89 — CHANGES_REQUESTED** [review]
I think it would be better to simply `xit` the test and maybe add a todo or a comment explaining why this is being skipped

**Review by JKMarkowski — APPROVED** [review]

**Review by dimamarksman — APPROVED** [review]

**Review by mikerodonnell89 — APPROVED** [review]

**Review by KevinOkamoto — APPROVED** [review]

**Comment by nikvalor** [comment]
Project: null CORE 
 Url: null 
 This link will expire at

**Comment by nikvalor** [comment]
Project: null Platform B
 Url: null 
 This link will expire at

**Comment by nikvalor** [comment]
Project: null Platform A 
 Url: null 
 This link will expire at

**Pull request merged**
