### PR TITLE
feat: Button in FIori3 | Dialog in Fiori3 | New way of adding Icons

### PR DESCRIPTION
**Pull request by salarenko**
#### Please provide a link to the associated issue.
fixes: #2110 
fixes: #2127 
fixes: #615 

#### Please provide a brief summary of this pull request.
For associated issues and brief summary check:
- Button: #2183 #2221 
- Dialog: #2189
- Icons: #2203

#### Please check whether the PR fulfills the following requirements

- [x] the commit message follows the guideline:
https://github.com/SAP/fundamental-ngx/blob/master/CONTRIBUTING.md
- [x] tests for the changes that have been done

Documentation checklist:
- [x] update `README.md`
- [x] [Breaking Changes Wiki](https://github.com/SAP/fundamental-ngx/wiki/Breaking-Changes)
- [x] Documentation Examples
- [x] Stackblitz works for all examples

### Button screenshots
**Before:**
image
image
image

**After:**
image
image
image
image

### CODE REVIEW

**Comment by JKMarkowski** [comment]
image
It seems like there is no styles for standard button without any property

**Comment by rengare** [comment]
> image
> It seems like there are no styles for standard button without any property

Issue has been fixed

**Comment by estelaxu3** [comment]
Looks good to me.

**Comment by mikerodonnell89** [comment]
@salarenko conflicts and broken deployment

**Pull request merged**
