### PR TITLE
fix: (platform) add vertical checkbox group and radio group example

### PR DESCRIPTION
**Pull request by DeepakSap14**
#### Please provide a link to the associated issue.
#3563 

#### Please provide a brief summary of this pull request.
1. Added vertical checkbox group example showing error message.
2. separate errors for context free checkboxes
3. Added vertical radio group example showing error message.
4. separate errors for context free radio buttons

#### Please check whether the PR fulfills the following requirements

- [x] the commit message follows the guideline:
https://github.com/SAP/fundamental-ngx/blob/main/CONTRIBUTING.md
- [x] tests for the changes that have been done
- [x] all items on the PR Review Checklist are addressed :
https://github.com/SAP/fundamental-ngx/wiki/PR-Review-Checklist

Documentation checklist:
- [x] Documentation Examples
- [x] Stackblitz works for all examples

### CODE REVIEW

**Review by sKudum — APPROVED** [review]

**Comment by sKudum** [comment]
update README.md we need to uncheck it as we don't have any changes in this PR.

**Review by Betrozov — APPROVED** [review]

**Review by KevinOkamoto — APPROVED** [review]
Looks good.

**Comment by KevinOkamoto** [comment]
@DeepakSap14 For some reason the "Simulate RTL" and "Switch Background" controls look broken in the preview deployment for this PR.

Screen Shot 2020-12-28 at 9 01 25 AM

It's happening on all pages of this deployment not just the Radio Group Button page. I have not seen this on any other PR deployments. It could be that you need to update this PR with the latest changes from "main".

I don't see anything in your code which would cause this ... strange. Anyways can you check to make sure the "Simulate RTL" and "Switch Background" switches look proper before merging?

**Review by mikerodonnell89 — CHANGES_REQUESTED** [review]
LGTM other than what Kevin mentioned about the simulate RTL / switch background buttons being broken.  It is actually happening on all fd-switch components.  Also unsure what could be causing it.  Issue is present on both core and platform docs.  I will push a commit to force a rebuild

**Comment by DeepakSap14** [comment]
@mikerodonnell89 , only rebase was needed.
but because of new styles, checkbox label margin was broken.
i have made the changes for it. have a look for core checkbox change, one more time.

**Review by JKMarkowski — APPROVED** [review]
Looks good for me

**Pull request merged**
