### PR TITLE
docs: fiori 3 table pagination

### LINKED ISSUE #2441: Fiori 3 table - pagination
Table should contain pagination section.  Will reuse our existing pagination component.  Also provide popover specifying rows per page - application developer should be able to configure what values go in this rows per page popover.

2 days

### PR DESCRIPTION
**Pull request by mikerodonnell89**
fixes #2441 

This is actually not in the Fiori 3 or ui5 specifications, but is considered in that first priority from CX

### CODE REVIEW

**Comment by InnaAtanasova** [comment]
Screen Shot 2020-06-11 at 1 20 14 PM
Screen Shot 2020-06-11 at 1 20 07 PM

Some pages are missing

**Comment by JKMarkowski** [comment]
It's not scope of this PR, but we should a little bit improve pagination component for sure. Let's add missing three dots, following Inna's comment.

**Comment by stefanoScalzo** [comment]
Screen Shot 2020-06-15 at 1 53 52 PM
missing dots

**Comment by mikerodonnell89** [comment]
> see comment

Fixed in this pr https://github.com/SAP/fundamental-ngx/pull/2654

just merged master in to this branch so it should be good now

**Comment by mikerodonnell89** [comment]
@rengare fixed

**Comment by stefanoScalzo** [comment]
Screen Shot 2020-06-23 at 9 52 18 AM
When hovering on the three dots, it puts an underline

**Comment by mikerodonnell89** [comment]
> Screen Shot 2020-06-23 at 9 52 18 AM
> When hovering on the three dots, it puts an underline

@stefanoScalzo this is a problem with the pagination component, not relevant to this pr

**Pull request merged**
