### PR TITLE
chore: deprecate icon size

### PR DESCRIPTION
**Pull request by droshev**
#### Please provide a link to the associated issue.

deprecate icon size since we don't support predefined sizes and remove its usage from the examples in the doc
#### Please check whether the PR fulfills the following requirements

- [x] the commit message follows the guideline:
https://github.com/SAP/fundamental-ngx/blob/master/CONTRIBUTING.md
- [x] tests for the changes that have been done
- [x] all items on the PR Review Checklist are addressed :
https://github.com/SAP/fundamental-ngx/wiki/PR-Review-Checklist

Documentation checklist:
- [x] update `README.md`
- [x] [Breaking Changes Wiki](https://github.com/SAP/fundamental-ngx/wiki/Breaking-Changes)
- [x] Documentation Examples
- [x] Stackblitz works for all examples

### CODE REVIEW

**Review by salarenko — CHANGES_REQUESTED** [review]
There are `IconComponent.size` usages in the documentation.
Check:
- `scroll-spy-custom-example.component.html`
- `scroll-spy-offset-example.component.html`
- `scroll-spy-example.component.html`
- `link-example.component.html`
and many more on core and platform side

**Comment by droshev** [comment]
> There are `IconComponent.size` usages in the documentation.
> Check:
> 
> * `scroll-spy-custom-example.component.html`
> * `scroll-spy-offset-example.component.html`
> * `scroll-spy-example.component.html`
> * `link-example.component.html`
>   and many more on core and platform side

updated

**Review by mikerodonnell89 — APPROVED** [review]

**Review by salarenko — CHANGES_REQUESTED** [review]
Still some documentation leftovers, check:
- Combobox examples
- libs/core/src/lib/tile/directives/numeric-content.directives.spec.ts
- libs/core/src/lib/icon/icon.component.ts (comment with usage example)

**Comment by droshev** [comment]
> Still some documentation leftovers, check:
> 
> * Combobox examples
> * libs/core/src/lib/tile/directives/numeric-content.directives.spec.ts
> * libs/core/src/lib/icon/icon.component.ts (comment with usage example)

updates

**Review by salarenko — APPROVED** [review]

**Pull request merged**
