### PR TITLE
fix(platform): table - selection row height issue

### PR DESCRIPTION
**Pull request by dmitry-stepanenko**
## Related Issue(s)

closes https://github.com/SAP/fundamental-ngx/issues/7070
closes https://github.com/SAP/fundamental-ngx/issues/7069

## Description
fixed an issue with selection column height

### Before:
image

### After:
image

##### During Implementation

1. Visual Testing:

-   [x] visual misalignments/updates
-   [x] check Light/Dark/HCB/HCW themes
-   [x] RTL/LTR - proper rendering and labeling
-   [x] responsiveness(resize)
-   [x] Content Density (Cozy/Compact/(Condensed))
-   [x] States - hover/disabled/focused/active/on click/selected/selected hover/press state
-   [x] Interaction/Animation - open/close, expand/collapse, add/remove, check/uncheck
-   [x] Mouse vs. Keyboard support
-   [x] Text Truncation

2. API and functional correctness

-   [x] check for console logs (warnings, errors)
-   [x] API boundary values
-   [n/a] different combinations of components - free style
-   [n/a] change the API values during testing

3. Documentation and Example validations

-   [n/a] missing API documentation or it is not understandable
-   [n/a] poor examples
-   [n/a] Stackblitz works for all examples

4. Accessibility testing
5. Browser Testing - Edge, Safari, Chrome, Firefox

##### PR Quality

-   [x] the commit message(s) follows the guideline:
        https://github.com/SAP/fundamental-ngx/blob/main/CONTRIBUTING.md
-   [n/a] tests for the changes that have been done
-   [x] all items on the PR Review Checklist are addressed :
        https://github.com/SAP/fundamental-ngx/wiki/PR-Review-Checklist
-   [n/a] Run npm run build-pack-library and test in external application
-   [n/a] update `README.md`
-   [n/a] [Breaking Changes Wiki](https://github.com/SAP/fundamental-ngx/wiki/Breaking-Changes)

##### PR Review

-   [x] visual misalignments/updates
-   [x] check Light/Dark/HCB/HCW themes
-   [x] RTL/LTR - proper rendering and labeling
-   [x] responsiveness(resize)
-   [x] Content Density (Cozy/Compact/(Condensed))
-   [x] States - hover/disabled/focused/active/on click/selected/selected hover/press state
-   [x] Interaction/Animation - open/close, expand/collapse, add/remove, check/uncheck
-   [x] Mouse vs. Keyboard support
-   [x] Text Truncation

2. API and functional correctness

-   [x] check for console logs (warnings, errors)
-   [x] API boundary values
-   [x] different combinations of components - free style
-   [x] change the API values during testing

3. Documentation and Example validations

-   [x] missing API documentation or it is not understandable
-   [x] poor examples
-   [x] Stackblitz works for all examples

4. Accessibility testing
5. Browser Testing - Edge, Safari, Chrome, Firefox

### CODE REVIEW

**Review by genereg1 — APPROVED** [review]

**Review by N1XUS — APPROVED** [review]

**Review by platon-rov — COMMENTED** [review]
Great work!

Only one small notice, you forgot to pass the parameter in the header selection cell.

image

**Comment by platon-rov** [comment]
Also, I guess your solution can be applied to eliminate two more bugs #7068 & #7067, as there will be not many changes I think we can do it in scope of this pr, what do you think?

**Comment by dmitry-stepanenko** [comment]
> Great work!
> 
> Only one small notice, you forgot to pass the parameter in the function called in the header selection cell.
> 
> image

Thanks, Platon, but it was omitted intentionally - header won't have more than 1 row 
image


On the subject of that other issue you mentioned: it has exactly the same origin and it's a good idea to address them together, but this PR is already approved by developers and QA engineers, so I would prefer to create a new one, if you don't mind

**Comment by dmitry-stepanenko** [comment]
Didn't understand Platon's point exactly, fixed now
image

image

**Review by platon-rov — APPROVED** [review]

**Pull request merged**
