### PR TITLE
Enhancement/#422 added single selection lists

### PR DESCRIPTION
**Pull request by MattL75**
#### Please provide a link to the associated issue.

Part of #422 

#### Please provide a brief summary of this pull request.

The code isn't exactly pretty, but it serves as an automated single selection list. It could also be implemented by the user, so I'm not sure what direction we want to go in. Doesn't hurt to implement it ourselves though, saves the user some time.

@mikerodonnell89 If you have an idea of how to accomplish this besides my method pls let me know 😶 

#### If this is a new feature, have you updated the documentation?
yes

### CODE REVIEW

**Comment by mikerodonnell89** [comment]
Failing unit test, `Can't bind to 'ngModel' since it isn't a known property of 'input'`, probably means the test needs to import `FormsModule`

**Comment by mikerodonnell89** [comment]
Also I think, if we are going to have single-select lists, the checkbox should actually be a radio button, thoughts @fkolar @xak ?

**Comment by fkolar** [comment]
> Failing unit test, `Can't bind to 'ngModel' since it isn't a known property of 'input'`, probably means the test needs to import `FormsModule`

It just means that for ngModel you haven't imported FormModule

**Comment by fkolar** [comment]
Yes if you turn on single select mode have it backed up by radio is the easiest way to track what is selected. Even you probably will not show the actual radio button

**Comment by MattL75** [comment]
Yeah we're not sure if the radio button from fundamental would work here

**Comment by fkolar** [comment]
I think any radio group would work. I think radio buttons will not be visible user will see only a list no? The specs for Controls is not finalized yet so not sure what is the final state.

**Comment by MattL75** [comment]
Ideally we would want to give some visual feedback to the user about what is selected or not with the radio buttons themselves

**Comment by fkolar** [comment]
I think this is good inspiration in terms how the list should be customizable. 
https://sapui5.hana.ondemand.com/#/entity/sap.m.StandardListItem

with icons, description, titles, etc..

**Comment by MattL75** [comment]
That can all be done with our current list, it's very flexible though requires you to code some of it. I know you are an advocate of stricter api so that might not be what you're looking for though

**Pull request closed without merging**
