### PR TITLE
fix: (core) Add shellbar side navigation example and directive.

### PR DESCRIPTION
**Pull request by JKMarkowski**
#### Please provide a link to the associated issue.
fixes: https://github.com/SAP/fundamental-ngx/issues/347
#### Please provide a brief summary of this pull request.
There is added side navigation directive on shellbar and 1 example of usage.
Also I removed information about side navigation up to 10 levels usage.
#### Please check whether the PR fulfills the following requirements

- [x] the commit message follows the guideline:
https://github.com/SAP/fundamental-ngx/blob/master/CONTRIBUTING.md
- [x] tests for the changes that have been done

Documentation checklist:
- [x] update `README.md`
- [x] [Breaking Changes Wiki](https://github.com/SAP/fundamental-ngx/wiki/Breaking-Changes)
- [x] Documentation Examples

### CODE REVIEW

**Comment by droshev** [comment]
@JKMarkowski can you move `(core)` after `:`?

**Comment by JKMarkowski** [comment]
Now, the 3rd levels are removed completely.

**Comment by InnaAtanasova** [comment]
Screen Shot 2019-11-19 at 4 36 28 PM

The Hamburger menu is still with light blue background

**Comment by JKMarkowski** [comment]
Hi @InnaAtanasova, the button is with white background only on hover, shouldn't it be like that ? shellbar

**Comment by InnaAtanasova** [comment]
> Hi @InnaAtanasova, the button is with white background only on hover, shouldn't it be like that ? shellbar

It should look like the Product Switch button

**Comment by JKMarkowski** [comment]
Hi @InnaAtanasova, it fully follows product-switch control button now.

**Pull request merged**
