### PR TITLE
fix(platform): table filter enhancement

### PR DESCRIPTION
**Pull request by khotcholava**
feat(core):
closes [#11783](https://github.com/SAP/fundamental-ngx/issues/11783)

- Add support for formatting array values in table component
- Fix format field name

## Before

Screenshot 2024-11-25 at 17 49 05

## After

Screenshot 2024-11-25 at 17 49 53

### CODE REVIEW

**Comment by khotcholava** [comment]
@mikerodonnell89 @dpavlenishvili Ping

**Comment by InnaAtanasova** [comment]
Please use proper naming for the PRs. If this gets merged without the proper title we would need to manually fix the release notes

**Review by mikerodonnell89 — CHANGES_REQUESTED** [review]
Two things I noticed:

- There's a space before the comma
- no "Status Color" text, just "(critical)"

Screenshot 2024-12-05 at 10 49 43 AM

**Comment by karolgromacki** [comment]
Hi @khotcholava , I've noticed one problem - so far the info bar is displayed after changing the filter through UI or from code, but I have a case when I load the whole tableState from the session storage and it doesn't apply the filter info bar - it seems that the problem is related to
`this._tableService.stateChange$.subscribe(({ type, state }) => {
                switch (type) {`

because when we use `this.table.setTableState()`, the state is changed, but the type is undefined and 
 `this._setAppliedFilterNames(state.current);` is not executed.

**Comment by khotcholava** [comment]
@karolgromacki Please include the valid code example. It's easier for me to debug.

**Comment by droshev** [comment]
@khotcholava fix the linting issues, make sure e2e/unit are not failing. Then we should review it.

**Pull request closed without merging**
