### PR TITLE
fix: (Core) fix grid list

### PR DESCRIPTION
**Pull request by Betrozov**
#### Please provide a link to the associated issue.
Closes https://github.com/SAP/fundamental-ngx/issues/4560#issuecomment-774880602
Closes https://github.com/SAP/fundamental-ngx/issues/4634
#### Please provide a brief summary of this pull request.
Fixed part of the issue, the other part was fixed in the Styles repository
#### Please check whether the PR fulfills the following requirements

- [X] the commit message follows the guideline:
https://github.com/SAP/fundamental-ngx/blob/main/CONTRIBUTING.md
- [X] tests for the changes that have been done
- [X] all items on the PR Review Checklist are addressed :
https://github.com/SAP/fundamental-ngx/wiki/PR-Review-Checklist

Documentation checklist:
- [X] update `README.md`
- [X] [Breaking Changes Wiki](https://github.com/SAP/fundamental-ngx/wiki/Breaking-Changes)
- [X] Documentation Examples
- [X] Stackblitz works for all examples

### CODE REVIEW

**Review by IlyaSurmay — APPROVED** [review]

**Review by mykolavorobiov — APPROVED** [review]

**Comment by mikerodonnell89** [comment]
Shouldn't this counter and button move to the opposite side in RTL as well?

Screen Shot 2021-02-08 at 3 30 36 PM

**Review by mikerodonnell89 — CHANGES_REQUESTED** [review]
Is the list item supposed to receive a focus outline? Not seeing anything about that in the specs, and Inna mentioned it in the initial issue

**Comment by Betrozov** [comment]
> Is the list item supposed to receive a focus outline? Not seeing anything about that in the specs, and Inna mentioned it in the initial issue

Hi @mikerodonnell89 
1. If look at the first image/issue I see only one issue is that the image overlaps the border. @InnaAtanasova can you help to understand what did you mean on the first image of the issue?
2. Focus state was presented in the `Visual specs`
grid-list-focus
gl-f

**Comment by Seamoo13** [comment]
- [ ] 1. When using tab navigation to select a list item edit icon, or other, and hit the enter key, the whole list item is selected, rather than just the button/icon
Peek 2021-02-09 15-35

**Review by Seamoo13 — CHANGES_REQUESTED** [review]
Please see the comment above

**Review by Seamoo13 — APPROVED** [review]
looks good

**Comment by Betrozov** [comment]
> Shouldn't this counter and button move to the opposite side in RTL as well?
> 
> Screen Shot 2021-02-08 at 3 30 36 PM

Created issue https://github.com/SAP/fundamental-ngx/issues/4634

**Review by mikerodonnell89 — APPROVED** [review]
Approving since RTL will be addressed in another issue, and we are still wondering about the focus but will talk to designers

**Comment by InnaAtanasova** [comment]
> > Is the list item supposed to receive a focus outline? Not seeing anything about that in the specs, and Inna mentioned it in the initial issue
> 
> Hi @mikerodonnell89
> 
> 1. If look at the first image/issue I see only one issue is that the image overlaps the border. @InnaAtanasova can you help to understand what did you mean on the first image of the issue?
> 2. Focus state was presented in the `Visual specs`
>    grid-list-focus
>    gl-f

@Betrozov yes, I meant the corners of the image that overlaps the border

**Comment by InnaAtanasova** [comment]
@Betrozov some more issues:
1. On click, the radio button still has the wrong focus:
Screen Shot 2021-02-10 at 3 05 04 PM
2. The item counter should not get a focus:
Screen Shot 2021-02-10 at 2 54 03 PM
3. Clicking on the `edit` button makes the whole card active:
Screen Shot 2021-02-10 at 3 02 26 PM
4. The delete button is on the wrong place in RTL
Screen Shot 2021-02-10 at 2 57 42 PM
5. The status indicator is covering the focus outline:
Screen Shot 2021-02-10 at 2 58 35 PM
6. The Cards in Drag and Drop mode don't have the correct cursor (on hover, active, etc.)

**Review by JKMarkowski — APPROVED** [review]

**Review by JKMarkowski — CHANGES_REQUESTED** [review]
@Betrozov Check Inna's comment. For sure RTL should be in scope of this PR, I don't know what about the rest

**Comment by Betrozov** [comment]
> @Betrozov some more issues:
> 
> 1. On click, the radio button still has the wrong focus:
> 
> Screen Shot 2021-02-10 at 3 05 04 PM
> 
> 2. The item counter should not get a focus:
> Screen Shot 2021-02-10 at 2 54 03 PM
> 
> 3. Clicking on the `edit` button makes the whole card active:
> Screen Shot 2021-02-10 at 3 02 26 PM
> 
> 4. The delete button is on the wrong place in RTL
> Screen Shot 2021-02-10 at 2 57 42 PM
> 
> 5. The status indicator is covering the focus outline:
> Screen Shot 2021-02-10 at 2 58 35 PM
> 
> 6. The Cards in Drag and Drop mode don't have the correct cursor (on hover, active, etc.)

1. Was fixed in the fundamental-styles repository, here is the PR - https://github.com/SAP/fundamental-styles/pull/2115
2. Fix located in the fundamental-styles repository, here is the PR - https://github.com/SAP/fundamental-styles/pull/2143
3. Created issue https://github.com/SAP/fundamental-ngx/issues/4643
4. Fix located in this the PR please look at the last comment
5. Fix located in the fundamental-styles repository, here is the PR - https://github.com/SAP/fundamental-styles/pull/2143
6. Fix located in this the PR please look at the last comment

**Comment by JKMarkowski** [comment]
Hello @Betrozov , thanks for fast response
1. :+1: 
2. Fix located in the fundamental-styles repository, here is the PR - SAP/fundamental-styles#2143 - Could you remove tabindex from counter in NGX for this PR?
3. :+1: 
4. Could you rotate(180deg) navigation icon in RTL?
image
5. :+1: 
6. :+1:

Could you check 2 and 4 point? Rest is ok for me

**Review by JKMarkowski — APPROVED** [review]
LGTM

**Review by InnaAtanasova — APPROVED** [review]
LGTM

**Pull request merged**
