### PR TITLE
Update README.md

### LINKED ISSUE #787: Change the link to demo in README.md
Currently in README.md, the link to demo is:
https://github.com/SAP/fundamental-ngx/tree/master/docs

However, it should be:
https://sap.github.io/fundamental-ngx/calendar

### PR DESCRIPTION
**Pull request by InnaAtanasova**
#### Please provide a link to the associated issue.
#787 

#### Please provide a brief summary of this pull request.
The link to demo in the README.md was:
`https://github.com/SAP/fundamental-ngx/tree/master/docs`
It's been changed to:
`https://sap.github.io/fundamental-ngx/home`

### CODE REVIEW

**Comment by MattL75** [comment]
This doesn't really solve anything - there's already a link to the docs above. Maybe we should remove this section altogether?

**Comment by droshev** [comment]
I kinda agree that the section doesn't bring much value. Unless we re-write it as an option to run older API versions.

**Comment by MattL75** [comment]
@droshev Yeah not a bad idea. We've had quite a few questions about that lately.

**Comment by MattL75** [comment]
Closing this PR, I'll accept one for replacing the current section with something describing how to run older version of the documentation.

**Comment by droshev** [comment]
I think we should merge this as it is fixing an issue but open a new issue for updating the section

**Comment by droshev** [comment]
> Closing this PR, I'll accept one for replacing the current section with something describing how to run older version of the documentation.

can we avoid closing other people's PRs?

**Comment by MattL75** [comment]
No. I am not merging this as the 'fix' serves absolutely no purpose.

**Comment by droshev** [comment]
done

**Comment by MattL75** [comment]
Again, this really doesn't fix anything

**Comment by MattL75** [comment]
Closing this as I'll merge the PR which removes this section.

**Pull request closed without merging**
