### PR TITLE
feat: (Platform) Introduce Value Help Dialog

### PR DESCRIPTION
**Pull request by mykolavorobiov**
#### Please provide a link to the associated issue.

[#4073](https://github.com/SAP/fundamental-ngx/issues/4073)

#### Please provide a brief summary of this pull request.

The value help dialog is a UI pattern that helps the user find and select single and multiple values. 

**Re-create** for Travis from https://github.com/SAP/fundamental-ngx/pull/4117

#### Please check whether the PR fulfills the following requirements

- [x] the commit message follows the guideline:
https://github.com/SAP/fundamental-ngx/blob/master/CONTRIBUTING.md
- [x] tests for the changes that have been done
- [x] all items on the PR Review Checklist are addressed :
https://github.com/SAP/fundamental-ngx/wiki/PR-Review-Checklist

Documentation checklist:
- [x] Documentation Examples
- [x] Stackblitz works for all examples

### CODE REVIEW

**Comment by stefanoScalzo** [comment]
Screen Shot 2021-01-04 at 11 20 50 AM
Looks good! mobile styling needs adjustments

**Review by Betrozov — APPROVED** [review]

**Comment by mikerodonnell89** [comment]
Labels not aligned with inputs

Screen Shot 2021-01-05 at 10 04 26 AM

**Comment by mikerodonnell89** [comment]
Need padding between buttons

Screen Shot 2021-01-05 at 10 04 51 AM

**Comment by mikerodonnell89** [comment]
Tokens in multi-input not vertically aligned properly (fine on the actual multi-input component)

Screen Shot 2021-01-05 at 10 06 38 AM

**Review by JKMarkowski — APPROVED** [review]
LGTM - Great job with keeping 1 file with data/class per example. It will make stackblitz work + user will be able to check whole code

**Review by mikerodonnell89 — CHANGES_REQUESTED** [review]
See my previous comments

**Comment by dimamarksman** [comment]
Items in the dropdown are duplicated 
image

**Review by mikerodonnell89 — APPROVED** [review]

**Review by dimamarksman — APPROVED** [review]

**Pull request merged**
