### PR TITLE
fix(core): control value not updating properly on user input

### PR DESCRIPTION
**Pull request by ZsDeak-SAP**
## Related Issue(s)

https://github.com/SAP/fundamental-ngx/issues/11848

## Description

Keeping input and form control value in sync (unless using objects only).
One exceptional scenario is when the user do not use `communicateByObject`, but does use `displayFn`. `displayFn` expects one of the `item` objects, that is why in `inputText` setter we need to set `_value`, not call `setValue`.

3. Documentation and Example validations
[this example](https://fundamental-ngx.netlify.app/#/core/combobox#display-object) and many others can be used to validate. select one of the items, modify the text input and open the select again by the chevron button. there should be no selected highlighting when `communicateByObject` is false, since the new valid value is what the user typed.

### CODE REVIEW

**Review by InnaAtanasova — APPROVED** [review]

**Comment by InnaAtanasova** [comment]
Thank you for taking care of this issue @ZsDeak-SAP 🙇‍♀️

**Review by mikerodonnell89 — CHANGES_REQUESTED** [review]
We will need this for the platform combobox as well

**Comment by ZsDeak-SAP** [comment]
> We will need this for the platform combobox as well

i cannot reproduce, nor find this issue in the code of that combobox. the implementation is vastly different

**Comment by mikerodonnell89** [comment]
Ok - one of my understandings of this issue is that previously, when the user would select an item in the list and then erase a character from the input, the popover would still display the previously selected item as selected with a blue background like so:

Screenshot 2024-07-08 at 10 58 58 AM

And this PR changes that behavior so the previously selected item is no longer displayed as selected, like so: 

Screenshot 2024-07-08 at 11 55 36 AM

So, we'd expect this behavior in platform as well, correct? Because on your PR, the platform combobox is still working like my first screenshot above

**Comment by ZsDeak-SAP** [comment]
@mikerodonnell89 that's a good point, but Core and Platform comboboxes are very different, even in how they function. Core updates all comboboxes by default on typing, Platform only sends the changes when you click out or hit enter. Try after selecting an item deleting a character, hit enter/or click out, and then open the list again. The previously selected item is deselected as expected, and the texts showing the state under the combobox examples show the correct value.

**Review by mikerodonnell89 — APPROVED** [review]

**Pull request merged**
