### PR TITLE
feat(btp) navigation refactoring

### PR DESCRIPTION
**Pull request by N1XUS**
## Related Issue(s)

relates #10750

## Description
- Refactored Vertical nav component markup;
- Added `NavigationModule` for easier usage;
- Refactored keyboard navigation;
- Added `dataSource` functionality; 
- Refactored overflow menu logic;

BREAKING CHANGE:
- Markup changed
**Before:**
```html
<fdb-navigation
    [state]="state"
    [mode]="mode"
    homeSeparator="false"
    [style.width]="'fit-content'"
    [style.height.px]="400"
>
    <a fdb-navigation-link [routerLink]="['/btp/navigation']" *fdbNavigationHome glyph="home" label="Home"></a>
    <fdb-navigation-content-start>
        <ul fdb-navigation-list>
            <li fdb-navigation-list-item [group]="true" [expanded]="true">
                <a fdb-navigation-link label="Main items"></a>
                <ul fdb-navigation-list>
...
```
**After:**
```html
<fdb-navigation
    [state]="state"
    [mode]="mode"
    homeSeparator="false"
    [style.width]="'fit-content'"
    [style.height.px]="400"
>
    <fdb-navigation-content-start>
        <fdb-navigation-list-item home>
            <a fdb-navigation-link *fdbNavigationLinkRef glyph="home">Home</a>
        </fdb-navigation-list-item>
        <fdb-navigation-list-item group expanded>
            <a fdb-navigation-link *fdbNavigationLinkRef>Main items</a>
            <fdb-navigation-list-item expanded>
                <a fdb-navigation-link *fdbNavigationLinkRef glyph="create-entry-time">Time</a>
            </fdb-navigation-list-item>
...
```

### CODE REVIEW

**Comment by N1XUS** [comment]
@InnaAtanasova thank you for your review.

Majority of issues were fixed.
As to `selected` state. Component automatically detect whether the link is active via `RouterLinkActive` directive, and then set the `selected` state. Additionally, I've added input property `selected` for the cases when `selected` state should be manually set without using `RouterLinkActive`. Hope that's enough functionality for this behaviour.

**Review by InnaAtanasova — COMMENTED** [review]
All my comments have been addressed. The `selected` state is in discussion with the designers. If we keep the current implementation we would need to document the difference with UI5

**Comment by g-cheishvili** [comment]
Screenshot 2023-12-06 at 14 03 04
Screenshot 2023-12-06 at 14 03 49
Screenshot 2023-12-06 at 14 04 23

Something's up with the border

**Comment by N1XUS** [comment]
@g-cheishvili fixed.

**Review by g-cheishvili — APPROVED** [review]

**Review by InnaAtanasova — APPROVED** [review]

**Pull request merged**
