### PR TITLE
fix(core): remove list body focus and focus to the list items

### PR DESCRIPTION
**Pull request by Lokanathan-k**
#### Please provide a link to the associated issue.
Closes: https://github.com/SAP/fundamental-ngx/issues/5779

#### Please provide a brief summary of this pull request.

removed list body focus and focused to the list items 

#### Please check whether the PR fulfills the following requirements

- [x] the commit message follows the guideline:
https://github.com/SAP/fundamental-ngx/blob/main/CONTRIBUTING.md
- [x] tests for the changes that have been done
- [x] all items on the PR Review Checklist are addressed :
https://github.com/SAP/fundamental-ngx/wiki/PR-Review-Checklist
- [x] Run npm run build-pack-library and test in external application

Documentation checklist:
- [NA] update `README.md`
- [NA] [Breaking Changes Wiki](https://github.com/SAP/fundamental-ngx/wiki/Breaking-Changes)
- [x] Documentation Examples
- [x] Stackblitz works for all examples

### CODE REVIEW

**Comment by Lokanathan-k** [comment]
regarding the issue 2: the Spacing is equally vertically and horizontally placed with padding of 16px and from the spec says that the Horizontal placement is needed for avatar with margin right of 12px
 PFA
Expected:
Screenshot 2021-07-13 at 12 13 29 PM
Screenshot 2021-07-13 at 12 13 47 PM

current implementation.
Screenshot 2021-07-13 at 12 15 36 PM

**Review by sKudum — APPROVED** [review]
lgtm

**Review by platon-rov — APPROVED** [review]

**Review by InnaAtanasova — APPROVED** [review]

**Comment by Seamoo13** [comment]
bar chart list items not accessible via tab, only the body gets the focus

**Comment by Lokanathan-k** [comment]
> bar chart list items not accessible via tab, only the body gets the focus
> 

these change requested is part of the card component documentation, will add the changes as part of the issue (https://github.com/SAP/fundamental-ngx/issues/5776)

**Review by Seamoo13 — APPROVED** [review]

**Pull request merged**
