### PR TITLE
implement time picker

### PR DESCRIPTION
**Pull request by mikerodonnell89**
#### Please provide a link to the associated issue.
#104

### CODE REVIEW

**Comment by droshev** [comment]
the time toggle button doesn't close the time picker

**Comment by InnaAtanasova** [comment]
We can set the time picker with invalid values.
screen shot 2018-08-08 at 9 28 52 am

**Comment by InnaAtanasova** [comment]
Cannot set the am/pm from the Time Picker input
screen shot 2018-08-08 at 9 38 18 am

**Comment by droshev** [comment]
I see that if the time picker field is disabled the button is not disable and it opens the time picker

**Comment by droshev** [comment]
Once you enter invalid time timeObject doesn't get updated even with a correct time 
[2018-08-08_09-44-07.mp4.zip](https://github.com/SAP/fundamental-ngx/files/2270474/2018-08-08_09-44-07.mp4.zip)

**Pull request closed without merging**
