### PR TITLE
fix: (Core) remove card-footer component

### LINKED ISSUE #3929: Bug: Card Footer Bar height should be increased to align with Visual Core
#### Is this a bug, enhancement, or feature request?
Bug
#### Briefly describe your proposal.
Card Footer Bar height should be increased from 33px to 40px to aligned with Visual Core
image
image

#### If this is a bug, please provide steps for reproducing it.
Go to: https://sap.github.io/fundamental-ngx/#/core/card
Scroll down to: Card Footer
See error below:
image
image

### LINKED ISSUE #5157: remove card-footer component from card component. Deviation from fiori
#### Is this a bug, enhancement, or feature request?
bug

#### Briefly describe your proposal.
Card is made of Card header and card content.
Card should not have card footer component.

#### Is there anything else we should know?
This change will cause breaking change in core library.

### PR DESCRIPTION
**Pull request by DeepakSap14**
#### Please provide a link to the associated issue.
fixes #5157
fixes #3929

BREAKING CHANGE:
CardFooter component has been removed.

#### Please provide a brief summary of this pull request.
Card should have only two areas.
1. Card header
2. Card content
Card Footer needs to be removed.

#### Please check whether the PR fulfills the following requirements

- [x] the commit message follows the guideline:
https://github.com/SAP/fundamental-ngx/blob/main/CONTRIBUTING.md
- [x] tests for the changes that have been done
- [x] all items on the PR Review Checklist are addressed :
https://github.com/SAP/fundamental-ngx/wiki/PR-Review-Checklist
- [x] Run npm run build-pack-library and test in external application

Documentation checklist:
- [x] update `README.md`
- [x] [Breaking Changes Wiki](https://github.com/SAP/fundamental-ngx/wiki/Breaking-Changes)
- [x] Documentation Examples
- [x] Stackblitz works for all examples

### CODE REVIEW

**Comment by InnaAtanasova** [comment]
Code looks good, let's see the Netlify preview and the build and will approve it.

**Review by InnaAtanasova — APPROVED** [review]

**Comment by InnaAtanasova** [comment]
@DeepakSap14 when you introduce Breaking changes in a PR you need to provide info in the Wiki page of how the user should handle them. For example, you can introduce `before` and `after` code snippets to illustrate the migration. I did it for this PR but please add this in future:

**Review by KevinOkamoto — APPROVED** [review]

**Comment by DeepakSap14** [comment]
@pierrom 
can you please verify the issue #3929 using below link.
https://deploy-preview-5158--fundamental-ngx.netlify.app

**Comment by DeepakSap14** [comment]
has been verified by @pierrom and issue is closed. merging this PR.

**Pull request merged**
