### PR TITLE
fix: (Core) updating the example for the truncation behaviour

### PR DESCRIPTION
**Pull request by Lokanathan-k**
updating the example for the truncation behaviour

#### Please provide a link to the associated issue.
fixes https://github.com/SAP/fundamental-ngx/issues/3748

#### Please provide a brief summary of this pull request.

truncation behaviour of the component example not available so added an example to the code. 

#### Please check whether the PR fulfills the following requirements

- [x] the commit message follows the guideline:
https://github.com/SAP/fundamental-ngx/blob/main/CONTRIBUTING.md
- [x] tests for the changes that have been done
- [x] all items on the PR Review Checklist are addressed :
https://github.com/SAP/fundamental-ngx/wiki/PR-Review-Checklist
- [x] Run npm run build-pack-library and test in external application

Documentation checklist:
- [x] update `README.md`
- [x] [Breaking Changes Wiki](https://github.com/SAP/fundamental-ngx/wiki/Breaking-Changes)
- [x] Documentation Examples
- [x] Stackblitz works for all examples

### CODE REVIEW

**Comment by nikvalor** [comment]
Project: allure-results CORE 
 Url: https://allure-results--core-pr-4857-4aane4zm.web.app 
 This link will expire at Sun 04 Apr 2021 05:04:24 AM GMT

**Comment by nikvalor** [comment]
Project: allure-results Platform B
 Url: https://allure-results--platform-b-pr-4857-jlbs02yy.web.app 
 This link will expire at Sun 04 Apr 2021 05:14:42 AM GMT

**Comment by nikvalor** [comment]
Project: allure-results Platform A 
 Url: https://allure-results--platform-a-pr-4857-nrbdk8d8.web.app 
 This link will expire at Sun 04 Apr 2021 05:17:49 AM GMT

**Review by manu-kr — APPROVED** [review]

**Review by KevinOkamoto — APPROVED** [review]

**Review by mikerodonnell89 — CHANGES_REQUESTED** [review]
The incorrect example code displays (showing decimal example again)

**Comment by Lokanathan-k** [comment]
> (showing decimal example again

@mikerodonnell89 
As per the spec this is how the truncation behaviour is explained. please share more details what needs to be done.

Screenshot 2021-03-10 at 8 57 14 AM

**Comment by mikerodonnell89** [comment]
Seems to be a little misunderstanding, this should help

Screen Shot 2021-03-10 at 8 14 28 AM

**Review by mikerodonnell89 — APPROVED** [review]

**Pull request merged**
