### PR TITLE
[WIP] feat(platform): new  micro-frontends component

### PR DESCRIPTION
**Pull request by yuchao-guo**
add 3 new components into platform

1) MicroFrontendsWrapperComponent, this is main component can be used in client main app for wrap micro app.

2)MicroFrontendsRouterSinkComponent , this is utility component, if    MicroFrontendsWrapperComponent is used as route node and micro app has it's own primary router, then this component match sub path  to avoid  404 error. 

3) MicroAppMain, if micro app is written in angular , this super class  should be extended by each micro app's entry component,  it setup router configuration and css application for micro app.

- [x] the commit message follows the guideline:
https://github.com/SAP/fundamental-ngx/blob/master/CONTRIBUTING.md
- [x] tests for the changes that have been done
- [x] all items on the PR Review Checklist are addressed :
https://github.com/SAP/fundamental-ngx/wiki/PR-Review-Checklist

Documentation checklist:
- [x] update `README.md`
- [x] [Breaking Changes Wiki](https://github.com/SAP/fundamental-ngx/wiki/Breaking-Changes)
- [x] Documentation Examples
- [x] Stackblitz works for all examples

### CODE REVIEW

**Comment by fkolar** [comment]
What is the goal of all if this ?

**Comment by yuchao-guo** [comment]
> What is the goal of all if this ? Let’s start commenting once its clear what this PR is really about and if this should belong even here.

The goal of all this is for allow  main angular app  include micro apps, micro apps can be developed and deployed independently with angular/vue/reactjs framework, main app need a container to include micro apps , this container is MicroFrontendWrapper, which response for micro app creation in main page, event communication and route integration between main app and micro apps .

**Comment by droshev** [comment]
@yuchao-guo let's have a meeting and discuss the PR and how to continue further.

**Comment by fkolar** [comment]
I think the platform layer is not really place for this code. This should be part of a repo focusing on microfrontends. In facts, we would have issue here with IE11, that we still need to support. 

For this layer we try to have a design document to make sure component signature is going to work for all of us, but again I am not really sure about the actual usecase. Let;s setup a call to discuss this. 

Does WED around PST lunch time is good for you? @yuchao-guo , @droshev ?

**Comment by yuchao-guo** [comment]
Hi Frantisek,

Yes, WED before 10:00 am EDT(Eastern Daylight Time) or after 1:00pm EDT time is good for me.

Thanks
Richard Guo

**Comment by rengare** [comment]
> I think the platform layer is not really place for this code. This should be part of a repo focusing on microfrontends. In facts, we would have issue here with IE11, that we still need to support.
> 
> For this layer we try to have a design document to make sure component signature is going to work for all of us, but again I am not really sure about the actual usecase. Let;s setup a call to discuss this.
> 
> Does WED around PST lunch time is good for you? @yuchao-guo , @droshev ?

On top of what Frank said,  micro frontend app main file's weight is 3mb.
I don't think that this is a good idea to include it on our site especially for library project when users want quick access to the documentation site.

image

**Comment by fkolar** [comment]
> We will discuss and decide for the next steps

Is this still an active topic? When we canceled that call, I assumed this is solved and you guys are planing to merge this with some other project?

**Comment by InnaAtanasova** [comment]
Let's keep the branch but the PR can be closed.

**Pull request closed without merging**
