### PR TITLE
fix(core): popover, fix a11y issues

### PR DESCRIPTION
**Pull request by Betrozov**
## Related Issue.
Closes SAP/fundamental-ngx/#6097

## Description

Fixed popover a11y issues

##### During Implementation
1. Visual Testing:
- [n/a] visual misalignments/updates
- [n/a] check Light/Dark/HCB/HCW themes
- [n/a] RTL/LTR - proper rendering and labeling
- [n/a] responsiveness(resize)
- [n/a] Content Density (Cozy/Compact/(Condensed))
- [n/a] States - hover/disabled/focused/active/on click/selected/selected hover/press state
- [n/a] Interaction/Animation - open/close, expand/collapse, add/remove, check/uncheck
- [n/a] Mouse vs. Keyboard support
- [n/a] Text Truncation
2. API and functional correctness
- [n/a] check for console logs (warnings, errors)
- [n/a] API boundary values
- [n/a] different combinations of components - free style
- [n/a] change the API values during testing
3. Documentation and Example validations
- [n/a] missing API documentation or it is not understandable
- [n/a] poor examples
- [n/a] Stackblitz works for all examples
4. Accessibility testing
5. Browser Testing - Edge, Safari, Chrome, Firefox

##### PR Quality
- [X] the commit message(s) follows the guideline:
https://github.com/SAP/fundamental-ngx/blob/main/CONTRIBUTING.md
- [n/a] tests for the changes that have been done
- [X] all items on the PR Review Checklist are addressed :
https://github.com/SAP/fundamental-ngx/wiki/PR-Review-Checklist
- [n/a] Run npm run build-pack-library and test in external application
- [n/a] update `README.md`
- [n/a] [Breaking Changes Wiki](https://github.com/SAP/fundamental-ngx/wiki/Breaking-Changes)

### CODE REVIEW

**Review by platon-rov — APPROVED** [review]

**Review by InnaAtanasova — APPROVED** [review]

**Comment by puru-hk** [comment]
ssue 1: Fixed

Issue 2: Fixed

Issue 3: Fixed

Issue 4: Not fixed
Observed: On accessing the buttons, the button name is read first followed by the labels.
Expected: The label should be read first followed by the button name

Screenshot 2021-09-27 at 17 07 20

Issue 5: Fixed

Issue 6: Not fixed.
Observed: The header ‘Mobile Popover’ is not read and the dialog is read twice to the user and the focus should be available on the ‘Count Click’ input which is first interactive element in the list

Expected: The Dialog name ‘Mobile Popover’ and dialog should be announced once and the focus should be available on the first interactive element in the dialog.

Screenshot 2021-09-27 at 17 08 12

Issue 7: Fixed

**Review by Smiranin — APPROVED** [review]

**Comment by dmitry-stepanenko** [comment]
@puru-hk 
Regarding pt.6, I've made few adjustments, but it still might be not ideal. It looks like the issue is specific to JAWS, VoiceOver produces correct output

VoiceOver
image
JAWS 
image

**Review by mikerodonnell89 — CHANGES_REQUESTED** [review]
Issue #7 I think has not been addressed - not being read on chrome screenreader and not seeing any changes in the code here that would address it

**Comment by puru-hk** [comment]
All issues are fixed.

**Comment by mikerodonnell89** [comment]
@puru-hk regarding issue 7 the screenreader just says “accept, button, footer” it does not announce the “success” color indication.  The issue says it needs to. I think however the change may need to come from button and not popover

**Comment by puru-hk** [comment]
> wever the change may need to come fr

Issues7: Yes I agree with but Accessibility team said color is not a mandatory. Accessibility team has tested and they have told that issues has been fixed

**Review by mikerodonnell89 — APPROVED** [review]

**Pull request merged**
