### PR TITLE
fix(core): show clear button in any combobox

### PR DESCRIPTION
**Pull request by droshev**
BREAKING CHANGE:
showClearButton set default to false

fixes: #11921

before: showClearButton only when the combobox is used as search field
after: showClearButton can be used independently and can be set to any type

### CODE REVIEW

**Review by InnaAtanasova — CHANGES_REQUESTED** [review]
Need an example in the documentation

**Comment by droshev** [comment]
> Need an example in the documentation

@InnaAtanasova Thank you for the review: having a documentation example is a great idea. I just added it.

**Comment by InnaAtanasova** [comment]
The width of the input changes when the clear button is shown. 
Expectation: the width of the control should stay consistent:
Screenshot 2024-05-22 at 9 12 40 AM
Screenshot 2024-05-22 at 9 12 31 AM

**Review by mikerodonnell89 — COMMENTED** [review]
Does platform need this too?

**Review by InnaAtanasova — APPROVED** [review]

**Pull request merged**
