### PR TITLE
fix(platform): exclude columns from p13n dialog

### LINKED ISSUE #9520: [Sourcing] Column with empty label appears on p13 dialog
#### Is this a bug, enhancement, or feature request?
enhancement
#### Briefly describe your proposal.
There is a use case when we have a column with empty label to perform multi-actions (represented as three dots, buttons, or symbol...). However, it is shown in a column panel with empty title like this:

Screenshot 2023-03-14 at 8 31 22 PM

We have [filterable]="false" or [sortable]="false" to make the column not visible on filter or sort panel. Can we have something similar to make that not visible in column panel? Or can we have some property to act as alt label in column panel?

Sample: https://angular-wtufa9.stackblitz.io

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)

Angular 15.2.0
fundamental-ngx/core: 0.39.1-rc.4 or latest
fundamental-ngx/platform": 0.39.1-rc.4 or latest

#### Please provide relevant source code if applicable.
Please refer: https://stackblitz.com/edit/angular-4hdtve?file=src%2Fapp%2Fplatform-table-p13-columns-example.component.html
#### Is there anything else we should know?
UX member does not recommend to have a label for "action" type column, so we don't have workaround for this case.

### PR DESCRIPTION
**Pull request by fkolar**
Introducing new input property which removes column from the P13n list

## Related Issue(s)

closes #9520

## Description

Introduced new `disableP13n` property on the `TableColum` that excludes columns from P13n Dialog. By default all columns are included.

### CODE REVIEW

**Review by g-cheishvili — APPROVED** [review]
Please restart pipeline

**Comment by fkolar** [comment]
Putting on hold this PR, to see if we cant find better solution.

**Review by InnaAtanasova — APPROVED** [review]

**Review by mikerodonnell89 — APPROVED** [review]

**Comment by mikerodonnell89** [comment]
> Putting on hold this PR, to see if we cant find better solution.

What is it you don't like about this approach?

**Comment by fkolar** [comment]
> > Putting on hold this PR, to see if we cant find better solution.
> 
> What is it you don't like about this approach?

Even this  simple, I wanted to see if we can somehow use the p13 column component but for now I think this is the best we can get and unblock everybody

**Comment by mikerodonnell89** [comment]
> > > Putting on hold this PR, to see if we cant find better solution.
> > 
> > 
> > What is it you don't like about this approach?
> 
> Even this simple, I wanted to see if we can somehow use the p13 column component but for now I think this is the best we can get and unblock everybody

I agree, I think let's get this merged

**Comment by N1XUS** [comment]
@fkolar please resolve the conflicts so we could merge your branch. Thank you

**Comment by fkolar** [comment]
updated from main

**Pull request merged**
