### PR TITLE
docs(core): fix dialog stackblitz examples

### PR DESCRIPTION
**Pull request by web-dev23**
#### Please provide a link to the associated issue.
Closes https://github.com/SAP/fundamental-ngx/issues/4391

#### Please provide a brief summary of this pull request.
fix Dialog examples.

#### Please check whether the PR fulfills the following requirements

- [x] the commit message follows the guideline:
https://github.com/SAP/fundamental-ngx/blob/main/CONTRIBUTING.md
- [x] tests for the changes that have been done
- [x] all items on the PR Review Checklist are addressed :
https://github.com/SAP/fundamental-ngx/wiki/PR-Review-Checklist
- [x] Run npm run build-pack-library and test in external application

Documentation checklist:
- [x] update `README.md`
- [x] [Breaking Changes Wiki](https://github.com/SAP/fundamental-ngx/wiki/Breaking-Changes)
- [x] Documentation Examples
- [x] Stackblitz works for all examples

### CODE REVIEW

**Review by InnaAtanasova — APPROVED** [review]

**Comment by web-dev23** [comment]
@InnaAtanasova , I can't merge this PR.

**Review by Betrozov — APPROVED** [review]

**Comment by Betrozov** [comment]
> @InnaAtanasova , I can't merge this PR.

@web-dev23  PR can be merged after approval from the QA side

**Comment by maxym-valor** [comment]
New bug in this PR:

**Comment by maxym-valor** [comment]
New bug in this PR: if you uncheck 'hasBackDrop' select in Playground - dialog should not open
Steps:
1. Open https://deploy-preview-5387--fundamental-ngx.netlify.app/#/core/dialog
2. Go to Playground section
3. hasBackdrop selected by default, unselect it
4. Click on Open Dialog button
**Expected result:** dialog is not opened
**Actual result:** dialog is opened at the lower left corner
Запись_экрана_2021-05-24_в_11 18 27

**Comment by web-dev23** [comment]
> New bug in this PR: if you uncheck 'hasBackDrop' select in Playground - dialog should not open
> Steps:
> 
> 1. Open https://deploy-preview-5387--fundamental-ngx.netlify.app/#/core/dialog
> 2. Go to Playground section
> 3. hasBackdrop selected by default, unselect it
> 4. Click on Open Dialog button
>    **Expected result:** dialog is not opened
>    **Actual result:** dialog is opened at the lower left corner
>    Запись_экрана_2021-05-24_в_11 18 27

@maxym-valor , I guess separate bug should be created for that. The scope of this ticket is to fix StackBlitz issue.

**Comment by maxym-valor** [comment]
@web-dev23 This bug does not exist on dev/prod and was created in this PR. So, it should be fixed before merge. We should not merge new bug!!

**Comment by maxym-valor** [comment]
> > New bug in this PR: if you uncheck 'hasBackDrop' select in Playground - dialog should not open
> > Steps:
> > 
> > 1. Open https://deploy-preview-5387--fundamental-ngx.netlify.app/#/core/dialog
> > 2. Go to Playground section
> > 3. hasBackdrop selected by default, unselect it
> > 4. Click on Open Dialog button
> >    **Expected result:** dialog is not opened
> >    **Actual result:** dialog is opened at the lower left corner
> >    Запись_экрана_2021-05-24_в_11 18 27
> 
> @maxym-valor , I guess separate bug should be created for that. The scope of this ticket is to fix StackBlitz issue.

@web-dev23 This bug does not exist on dev/prod and was created in this PR. So, it should be fixed before merge. We should not merge new bug!!

**Comment by maxym-valor** [comment]
> > New bug in this PR: if you uncheck 'hasBackDrop' select in Playground - dialog should not open
> > Steps:
> > 
> > 1. Open https://deploy-preview-5387--fundamental-ngx.netlify.app/#/core/dialog
> > 2. Go to Playground section
> > 3. hasBackdrop selected by default, unselect it
> > 4. Click on Open Dialog button
> >    **Expected result:** dialog is not opened
> >    **Actual result:** dialog is opened at the lower left corner
> >    Запись_экрана_2021-05-24_в_11 18 27
> 
> @maxym-valor , I guess separate bug should be created for that. The scope of this ticket is to fix StackBlitz issue.

Yeah, i mistaken, sorry. Bug exists on prod also.

**Comment by maxym-valor** [comment]
Still have nothing in Stackblitz @web-dev23

**Comment by web-dev23** [comment]
> Still have nothing in Stackblitz @web-dev23

@maxym-valor , fixed.

**Comment by maxym-valor** [comment]
Approved!

**Pull request merged**
