### PR TITLE
fix: (Core)  arrow keys in Core carousel component

### PR DESCRIPTION
**Pull request by mykolavorobiov**
#### Please provide a link to the associated issue.
Closes: https://github.com/SAP/fundamental-ngx/issues/3752

Additional fixes for: https://github.com/SAP/fundamental-ngx/issues/3853

#### Please provide a brief summary of this pull request.
Prevent native focus behavior on carousel buttons if buttons will be disabled.
Fixed issue with showing active slide and navigation with arrow buttons after change RTL.

#### Please check whether the PR fulfills the following requirements
- [x] the commit message follows the guideline:
https://github.com/SAP/fundamental-ngx/blob/master/CONTRIBUTING.md
- [x] tests for the changes that have been done
- [x] all items on the PR Review Checklist are addressed :
https://github.com/SAP/fundamental-ngx/wiki/PR-Review-Checklist

### CODE REVIEW

**Review by DeepakSap14 — APPROVED** [review]
LGTM

**Review by mikerodonnell89 — CHANGES_REQUESTED** [review]
This should be checking the RTL service to see whether to use next or previous.  Otherwise looks good

**Comment by mykolavorobiov** [comment]
> This should be checking the RTL service to see whether to use next or previous. Otherwise looks good
It's have no sense how we will go to last or first slide, from left to right or right to left. If we have no loop and buttons will be disabled, I move focus to carousel.
If you mean something else, please clarify.

p.s. pushed small update - remove duplicated code.

**Review by KevinOkamoto — APPROVED** [review]
Looks good.

**Comment by InnaAtanasova** [comment]
`Carousel with vertical direction` has a bug in RTL mode (at least on my side). Ways to reproduce it:
1. Click on the "right" navigation button 2 times:
Screen Shot 2020-11-12 at 2 44 37 PM
2. Switch to RTL using the Switch in the left hand-side corner. The images disappear:
Screen Shot 2020-11-12 at 2 45 40 PM

**Comment by mikerodonnell89** [comment]
> > This should be checking the RTL service to see whether to use next or previous. Otherwise looks good
> 
> It's have no sense how we will go to last or first slide, from left to right or right to left. If we have no loop and buttons will be disabled, I move focus to carousel.
> If you mean something else, please clarify.
> 
> p.s. pushed small update - remove duplicated code.

@mykolavorobiov Flick the "Simulate RTL" switch. If the carousel is displayed right to left, then pressing the right arrow key should move the carousel to the image to the right.  In your PR it is opposite

**Comment by mykolavorobiov** [comment]
@InnaAtanasova 
@mikerodonnell89 
I confused a little bit, it's not related to my fix and my code, and in general not related to an issue.
It's not a big deal to fix all your comments in my PR.
All of your comments reproduced in the original version, https://fundamental-ngx.netlify.app/#/core/carousel
Please create separate issues, and I will attach them to this PR.

**Comment by InnaAtanasova** [comment]
@mykolavorobiov I created an issue for the comments Mike and I added. Here's a link: https://github.com/SAP/fundamental-ngx/issues/3853

Let us know if you will include them as part of this PR or they will be handled in another PR.

**Review by salarenko — APPROVED** [review]

**Comment by InnaAtanasova** [comment]
Hi @mykolavorobiov could be a problem with Netlify and unfortunately I can't check your branch locally but neither of the issues logged in https://github.com/SAP/fundamental-ngx/issues/3853 seems to be fixed. `Carousel with vertical direction` still has issues with RTL. If you follow the steps described in the issue you will be able to reproduce. 
As to the last point of issue #3853 , please check the behavior of Carousel in [Bootstrap](https://getbootstrap.com/docs/4.0/components/carousel/#with-indicators) and [MDB](https://mdbootstrap.com/docs/angular/advanced/carousel/) in the cases where they have page indicators. Add `dir="rtl"` to the body of the html page and you can see that clicking on the right hand side button "moves" the active dot from right to left. In normal cases the flow of the dots is `left to right`, so in RTL mode the flow should be `right to left`. In our case, when switched to RTL mode, the flow of the "dots" is still from left to right. Hope it makes sense.

**Review by InnaAtanasova — APPROVED** [review]

**Review by mikerodonnell89 — APPROVED** [review]

**Comment by DeepakSap14** [comment]
Merging it on behalf of valor team.

**Pull request merged**
