### PR TITLE
feat: add height/width inputs to modal

### LINKED ISSUE #522: Modal various improvements
#### Is this a bug, enhancement, or feature request?
Enhancement

#### Briefly describe your proposal.
- Users should be able to pass the width/height of the modal manually if they so choose. Currently the only way to do that is to use /deep/.
- Maybe as part of that ticket we can offer full screen mode too?
- allow having modals without header so applications can have free style modal

### PR DESCRIPTION
**Pull request by MattL75**
#### Please provide a link to the associated issue.
fixes #522 

#### Please provide a brief summary of this pull request.
Allows more control over modal sizing for users.

### CODE REVIEW

**Comment by droshev** [comment]
@MattL75 I added 2 minor improvements to #522. Would you mind doing them as well in the same PR?

**Comment by MattL75** [comment]
Full screen should already work by just using % or vw/vh units. 

Also pretty sure modals without a header is already possible.

**Comment by droshev** [comment]
@MattL75 This is great! Would you mind adding examples in the playground? It would be more obvious for the developers. Also, how about unit testing the changes?

**Comment by MattL75** [comment]
Done

**Pull request merged**
