### PR TITLE
docs(core): fix file uploader stackblitz examples

### PR DESCRIPTION
**Pull request by web-dev23**
#### Please provide a link to the associated issue.
Closes SAP/fundamental-ngx#4391

#### Please provide a brief summary of this pull request.
Fixes File Uploader Stackblitz examples.

#### Please check whether the PR fulfills the following requirements

- [x] the commit message follows the guideline:
https://github.com/SAP/fundamental-ngx/blob/main/CONTRIBUTING.md
- [x] tests for the changes that have been done
- [x] all items on the PR Review Checklist are addressed :
https://github.com/SAP/fundamental-ngx/wiki/PR-Review-Checklist
- [x] Run npm run build-pack-library and test in external application

Documentation checklist:
- [x] update `README.md`
- [x] [Breaking Changes Wiki](https://github.com/SAP/fundamental-ngx/wiki/Breaking-Changes)
- [x] Documentation Examples
- [x] Stackblitz works for all examples

### CODE REVIEW

**Comment by dimamarksman** [comment]
@web-dev23 this PR is not mergeable, please see CI section

**Comment by web-dev23** [comment]
> @web-dev23 this PR is not mergeable, please see CI section.
> Also PR has to be linked to the issue it belongs to

Okay, will do.

**Comment by InnaAtanasova** [comment]
Hi @web-dev23 when you open a PR you need to assign reviewers and assignee. If you have the right to merge a PR (you probably do if you are added to the project and not use forks) you should assign yourself. This means that once the PR is approved you are responsible for merging it. Then you need to add an appropriate label to the PR. In this case I added documentation and Stackblitz. The last step is to add a project (for you it will always be Platform development) and the current sprint. I added those for you but in future make sure this section is maintained.

**Comment by web-dev23** [comment]
> Hi @web-dev23 when you open a PR you need to assign reviewers and assignee. If you have the right to merge a PR (you probably do if you are added to the project and not use forks) you should assign yourself. This means that once the PR is approved you are responsible for merging it. Then you need to add an appropriate label to the PR. In this case I added documentation and Stackblitz. The last step is to add a project (for you it will always be Platform development) and the current sprint. I added those for you but in future make sure this section is maintained.

@InnaAtanasova , sure, thank you.

**Review by hanjunt — APPROVED** [review]

**Review by N1XUS — APPROVED** [review]

**Review by Betrozov — APPROVED** [review]

**Review by N1XUS — APPROVED** [review]

**Comment by maxym-valor** [comment]
Still have nothing in Stackblitz.

**Review by InnaAtanasova — APPROVED** [review]

**Comment by web-dev23** [comment]
> Still have nothing in Stackblitz.
> image

@maxym-valor , fixed.

**Comment by maxym-valor** [comment]
Approved!

**Pull request merged**
