### PR TITLE
fix(core): fix dialogs footer button size

### PR DESCRIPTION
**Pull request by xandrio**
#### Please provide a link to the associated issue.
#5076 

#### Please provide a brief summary of this pull request.
Service updated, button size depends on config.mobile, documentation updated also

#### Please check whether the PR fulfills the following requirements

- [x] the commit message follows the guideline:
https://github.com/SAP/fundamental-ngx/blob/main/CONTRIBUTING.md
- [x] tests for the changes that have been done
- [x] all items on the PR Review Checklist are addressed :
https://github.com/SAP/fundamental-ngx/wiki/PR-Review-Checklist
- [x] Run npm run build-pack-library and test in external application

Documentation checklist:
- [x] update `README.md`
- [x] [Breaking Changes Wiki](https://github.com/SAP/fundamental-ngx/wiki/Breaking-Changes)
- [x] Documentation Examples
- [x] Stackblitz works for all examples

### CODE REVIEW

**Review by dimamarksman — APPROVED** [review]

**Review by InnaAtanasova — CHANGES_REQUESTED** [review]
The changes are applied in the docs part but also in the library itself, it should not be a `docs`. You need to maintain the right-hand side of the PR.

**Comment by maxym-valor** [comment]
Approved!

**Comment by xandrio** [comment]
@InnaAtanasova can you please check again? I hope I did it right

**Comment by InnaAtanasova** [comment]
> @InnaAtanasova can you please check again? I hope I did it right

Nope :D Try again with the PR naming :)

**Comment by xandrio** [comment]
@InnaAtanasova done :)

**Review by Betrozov — APPROVED** [review]

**Review by InnaAtanasova — APPROVED** [review]

**Pull request merged**
