### PR TITLE
fix(core): truncate breadcrumb text when item text is longer than 30 chars

### LINKED ISSUE #7840: Truncate the title in fd-breadcrum if it's too long
#### Is this a bug, enhancement, or feature request?
enhancement
#### Briefly describe your proposal.
Ideally if the title is more than specific length, we should truncate and show title-truncated...
Screen Shot 2022-01-25 at 11 47 36 AM
Screen Shot 2022-01-25 at 11 50 18 AM

#### Please provide relevant source code if applicable.
<fd-breadcrum>

### PR DESCRIPTION
**Pull request by shrvr**
## Related Issue(s)

closes #7840 

## Description

Truncates the breadcrumb text if item text is longer than 30 characters.

##### During Implementation

1. Visual Testing:

-   [x] visual misalignments/updates
-   [ ] check Light/Dark/HCB/HCW themes
-   [ ] RTL/LTR - proper rendering and labeling
-   [x] responsiveness(resize)
-   [ ] Content Density (Cozy/Compact/(Condensed))
-   [ ] States - hover/disabled/focused/active/on click/selected/selected hover/press state
-   [ ] Interaction/Animation - open/close, expand/collapse, add/remove, check/uncheck
-   [ ] Mouse vs. Keyboard support
-   [x] Text Truncation

2. API and functional correctness

-   [ ] check for console logs (warnings, errors)
-   [ ] API boundary values
-   [ ] different combinations of components - free style
-   [ ] change the API values during testing

3. Documentation and Example validations

-   [ ] missing API documentation or it is not understandable
-   [ ] poor examples
-   [ ] Stackblitz works for all examples

4. Accessibility testing
5. Browser Testing - Edge, Safari, Chrome, Firefox

##### PR Quality

-   [ ] the commit message(s) follows the guideline:
        https://github.com/SAP/fundamental-ngx/blob/main/CONTRIBUTING.md
-   [ ] tests for the changes that have been done
-   [ ] all items on the PR Review Checklist are addressed :
        https://github.com/SAP/fundamental-ngx/wiki/PR-Review-Checklist
-   [ ] Run npm run build-pack-library and test in external application
-   [ ] update `README.md`
-   [ ] [Breaking Changes Wiki](https://github.com/SAP/fundamental-ngx/wiki/Breaking-Changes)

### CODE REVIEW

**Comment by g-cheishvili** [comment]
This implementation is missing few points:
* If you truncate, there should be way to see whole text, besides aria title or something like it
* What about cases when text is changed? AFTER content init

Please take a look at the main branch now and try reimplementing

**Comment by mikerodonnell89** [comment]
> * What about cases when text is changed? AFTER content init

@g-cheishvili True that the PR doesn't handle this, but I don't see a real-world case of this happening so in my opinion it isn't worth it to run the check more than once. If a developer needs this they can trick the breadcrumb into reloading with an *ngIf but I see that as a very rare edge-case

**Comment by mikerodonnell89** [comment]
> * If you truncate, there should be way to see whole text, besides aria title or something like it

Agreed here, need some aria support and maybe a mouseover tooltip

**Comment by g-cheishvili** [comment]
> > * What about cases when text is changed? AFTER content init
> 
> @g-cheishvili True that the PR doesn't handle this, but I don't see a real-world case of this happening so in my opinion it isn't worth it to run the check more than once. If a developer needs this they can trick the breadcrumb into reloading with an *ngIf but I see that as a very rare edge-case

Content might not be only text-based, it can be something else too, for example icon, object status or any HTML-based element. We can not handle all cases with just innerText

**Comment by mikerodonnell89** [comment]
> > > * What about cases when text is changed? AFTER content init
> > 
> > 
> > @g-cheishvili True that the PR doesn't handle this, but I don't see a real-world case of this happening so in my opinion it isn't worth it to run the check more than once. If a developer needs this they can trick the breadcrumb into reloading with an *ngIf but I see that as a very rare edge-case
> 
> Content might not be only text-based, it can be something else too, for example icon, object status or any HTML-based element. We can not handle all cases with just innerText

True, and in that case it would probably be better to check for a large width of the element in pixels?  And I'm also thinking maybe rather than picking an arbitrary number of pixels (or characters or anything) to truncate on, we provide an input for the developer to configure the truncation point for themselves (perhaps with a default value).

**Comment by g-cheishvili** [comment]
> > > > * What about cases when text is changed? AFTER content init
> > > 
> > > 
> > > @g-cheishvili True that the PR doesn't handle this, but I don't see a real-world case of this happening so in my opinion it isn't worth it to run the check more than once. If a developer needs this they can trick the breadcrumb into reloading with an *ngIf but I see that as a very rare edge-case
> > 
> > Content might not be only text-based, it can be something else too, for example icon, object status or any HTML-based element. We can not handle all cases with just innerText
> 
> True, and in that case it would probably be better to check for a large width of the element in pixels?  And I'm also thinking maybe rather than picking an arbitrary number of pixels (or characters or anything) to truncate on, we provide an input for the developer to configure the truncation point for themselves (perhaps with a default value).

Would be great, plus it should be additional separate directive

**Comment by mikerodonnell89** [comment]
Closing in favor of this issue: https://github.com/SAP/fundamental-ngx/issues/8239

**Pull request closed without merging**
