### PR TITLE
fix: adjusting styles from version 0.11

### PR DESCRIPTION
**Pull request by JKMarkowski**
Please provide a link to the associated issue.
Closes: https://github.com/SAP/fundamental-ngx/issues/2956

Please provide a brief summary of this pull request.
release 0.11.0 summary: https://github.com/SAP/fundamental-styles/releases/tag/v0.11.0

removed components:
- identifier
- image
- dropdown
- select-native
#### Please check whether the PR fulfills the following requirements

- [x] the commit message follows the guideline:
https://github.com/SAP/fundamental-ngx/blob/master/CONTRIBUTING.md
- [x] tests for the changes that have been done
- [x] all items on the PR Review Checklist are addressed :
https://github.com/SAP/fundamental-ngx/wiki/PR-Review-Checklist

### CODE REVIEW

**Comment by mikerodonnell89** [comment]
tile-disabled-example.component.html and tile-media-example.component.html should be removed

**Comment by stefanoScalzo** [comment]
Screen Shot 2020-08-17 at 2 45 23 PM
Shellbar user i con needs to be fixed

**Comment by stefanoScalzo** [comment]
Screen Shot 2020-08-17 at 2 48 54 PM
i dont think the x is positioned properly

**Comment by stefanoScalzo** [comment]
Screen Shot 2020-08-17 at 2 49 35 PM
split button has rounded corners

**Comment by JKMarkowski** [comment]
Let's change links in background images
image

**Comment by JKMarkowski** [comment]
Split button has overwritten css's on segmented button example. There is how to reproduce it
splitbutton
Let's add some properties in `split-button.component.scss` and add `// TODO` comment, to fix it on styles

**Comment by JKMarkowski** [comment]
Seems like styles on switch are not added properly
image

**Pull request closed without merging**
