### PR TITLE
fix(core): fixing accessibility of datetime picker component

### PR DESCRIPTION
**Pull request by web-dev23**
## Related Issue.
Closes https://github.com/SAP/fundamental-ngx/issues/6215

## Description

Fix of accessibility issues of Datetime Picker component.

##### During Implementation
1. Visual Testing:
- [x] visual misalignments/updates
- [x] check Light/Dark/HCB/HCW themes
- [x] RTL/LTR - proper rendering and labeling
- [x] responsiveness(resize)
- [x] Content Density (Cozy/Compact/(Condensed))
- [x] States - hover/disabled/focused/active/on click/selected/selected hover/press state
- [x] Interaction/Animation - open/close, expand/collapse, add/remove, check/uncheck
- [x] Mouse vs. Keyboard support
- [x] Text Truncation
2. API and functional correctness
- [x] check for console logs (warnings, errors)
- [x] API boundary values
- [x] different combinations of components - free style
- [x] change the API values during testing
3. Documentation and Example validations
- [x] missing API documentation or it is not understandable
- [x] poor examples
- [x] Stackblitz works for all examples
4. Accessibility testing
5. Browser Testing - Edge, Safari, Chrome, Firefox

##### PR Quality
- [x] the commit message(s) follows the guideline:
https://github.com/SAP/fundamental-ngx/blob/main/CONTRIBUTING.md
- [x] tests for the changes that have been done
- [x] all items on the PR Review Checklist are addressed :
https://github.com/SAP/fundamental-ngx/wiki/PR-Review-Checklist
- [x] Run npm run build-pack-library and test in external application
- [x] update `README.md`
- [x] [Breaking Changes Wiki](https://github.com/SAP/fundamental-ngx/wiki/Breaking-Changes)

##### PR Review
- [x] visual misalignments/updates
- [x] check Light/Dark/HCB/HCW themes
- [x] RTL/LTR - proper rendering and labeling
- [x] responsiveness(resize)
- [x] Content Density (Cozy/Compact/(Condensed))
- [x] States - hover/disabled/focused/active/on click/selected/selected hover/press state
- [x] Interaction/Animation - open/close, expand/collapse, add/remove, check/uncheck
- [x] Mouse vs. Keyboard support
- [x] Text Truncation
2. API and functional correctness
- [x] check for console logs (warnings, errors)
- [x] API boundary values
- [x] different combinations of components - free style
- [x] change the API values during testing
3. Documentation and Example validations
- [x] missing API documentation or it is not understandable
- [x] poor examples
- [x] Stackblitz works for all examples
4. Accessibility testing
5. Browser Testing - Edge, Safari, Chrome, Firefox

### CODE REVIEW

**Review by Betrozov — APPROVED** [review]

**Comment by InnaAtanasova** [comment]
@web-dev23 please maintain the PR template and right hand side

**Comment by Sanjay-1312** [comment]
Issue 2: Not fixed.
image
OB: The tool tip or text alternative is not provided for the 'Increase' and 'Decrease' button.
EB: Ideally, the icon should be provided with the text alternative to define the purpose of the UI.

image
OB: There is a separate tab stop is provided for the 'Hrs', 'Min' and Am/Pm. 
EB: There is should be no separate tab stop should be provided


Issue 3: Not fixed
image
OB: There is an separate tab stop provided for the static text.
EB: Ideally, when calendar is open the success or error message should be read followed by the calendar date number.

Retest Details:
https://deploy-preview-6841--fundamental-ngx.netlify.app/#/core/datetime-picker
JAWS 2021

**Comment by web-dev23** [comment]
> Issue 2: Not fixed. image OB: The tool tip or text alternative is not provided for the 'Increase' and 'Decrease' button. EB: Ideally, the icon should be provided with the text alternative to define the purpose of the UI.
> 
> image OB: There is a separate tab stop is provided for the 'Hrs', 'Min' and Am/Pm. EB: There is should be no separate tab stop should be provided
> 
> Issue 3: Not fixed image OB: There is an separate tab stop provided for the static text. EB: Ideally, when calendar is open the success or error message should be read followed by the calendar date number.
> 
> Retest Details: https://deploy-preview-6841--fundamental-ngx.netlify.app/#/core/datetime-picker JAWS 2021

@puru-hk , @Sanjay-1312 
Issue 2 - added tooltip for Increase/decrease button. Removed tab stop. I don't quite understand at what point for example "hrs" label should be read? When user is switched to Increase hours button, appropriate information ("Increase hours button") is read, isn't this sufficient?
Issues 3 - Removed tab stop. 
"When calendar is open the success or error message should be read **followed by the calendar date number**" - I guess this is an additional requirement, should we create a separate ticket for that as we previously agreed?

**Comment by Sanjay-1312** [comment]
Hello Colleagues,

Issue 2 and 3 is fixed.

Retest Details:

https://deploy-preview-6841--fundamental-ngx.netlify.app/#/core/datetime-picker
JAWS 2021

**Pull request merged**
