### PR TITLE
fix: (Core) wizard step indicator stacking bugs on narrow screens

### LINKED ISSUE #4420: Wizard - incorrect stacking functionality
- [ ] When the screen is at the below size, you would expect that clicking the icons stacked on the far-left should open an action sheet which would allow you to choose between navigating backwards towards either step 1 or step 2.  Instead, you are taken to step 2. (Ignore the missing padding on the right icon - fix coming in the next version of styles)
Screen Shot 2021-02-17 at 10 16 04 AM

- [ ] Additionally, you can get this use case, and I'd expect the action sheet to have three options.
Screen Shot 2021-02-17 at 10 19 35 AM

- [ ] And in this example, clicking the stacked icons on the right will occasionally open the expected action sheet, but usually, will simply take you directly to the fourth step.  I am not sure what is causing the discrepancy.
Screen Shot 2021-02-17 at 10 27 16 AM

- [ ] Lastly, when `appendToWizard` is set to false, if the last step is visited and the user navigates back to an earlier one, the last visited step will not be clickable.  It should be clickable and open the action sheet. In the image below step 4 has been visited and clicking it does nothing.
Screen Shot 2021-02-17 at 1 10 56 PM

### PR DESCRIPTION
**Pull request by mikerodonnell89**
fixes #4420 

Fixes a number of bugs where the stacked step indicator action sheet would be missing steps it should have, or clicking the step indicator would change to a step rather than open the action sheet

Before
Screen Shot 2021-03-10 at 9 32 34 AM

After
Screen Shot 2021-03-10 at 9 31 01 AM

### CODE REVIEW

**Comment by InnaAtanasova** [comment]
First example:
1. Complete all 4 steps :
Screen Shot 2021-03-10 at 12 00 36 PM

2. Go back to the first one:
Screen Shot 2021-03-10 at 12 00 43 PM

The last two stacked steps are in grey indicating that they are not completed. They should be in blue as the user completed them.

**Comment by InnaAtanasova** [comment]
after returning to bog screen, the last item has a dropdown menu with previously stacked steps:
Screen Shot 2021-03-10 at 12 05 10 PM

**Comment by nikvalor** [comment]
Project: null Platform B
 Url: null 
 This link will expire at

**Comment by nikvalor** [comment]
Project: null Platform A 
 Url: null 
 This link will expire at

**Comment by nikvalor** [comment]
Project: null Platform B
 Url: null 
 This link will expire at

**Comment by nikvalor** [comment]
Project: null CORE 
 Url: null 
 This link will expire at

**Comment by nikvalor** [comment]
Project: null Platform A 
 Url: null 
 This link will expire at

**Comment by nikvalor** [comment]
Project: null CORE 
 Url: null 
 This link will expire at

**Comment by nikvalor** [comment]
Project: null Platform B
 Url: null 
 This link will expire at

**Comment by nikvalor** [comment]
Project: null Platform A 
 Url: null 
 This link will expire at

**Comment by InnaAtanasova** [comment]
In this case steps 1 and 2 are completed, the connector between them should be blue.

Screen Shot 2021-03-11 at 3 57 43 PM

**Comment by InnaAtanasova** [comment]
On small screen, when 1 and 2 are stacked, the overflow menu does not show but immediately goes to step 2
Screen Shot 2021-03-11 at 4 01 25 PM

**Comment by InnaAtanasova** [comment]
The rest of my comments have been addressed.

**Comment by nikvalor** [comment]
Project: null Platform B
 Url: null 
 This link will expire at

**Comment by nikvalor** [comment]
Project: null Platform A 
 Url: null 
 This link will expire at

**Comment by nikvalor** [comment]
Project: null CORE 
 Url: null 
 This link will expire at

**Comment by nikvalor** [comment]
Project: null Platform A 
 Url: null 
 This link will expire at

**Comment by nikvalor** [comment]
Project: null Platform B
 Url: null 
 This link will expire at

**Comment by nikvalor** [comment]
Project: null CORE 
 Url: null 
 This link will expire at

**Review by InnaAtanasova — APPROVED** [review]

**Pull request merged**
