### PR TITLE
fix(core): step-input, fix a11y issues

### PR DESCRIPTION
**Pull request by Betrozov**
## Related Issue

closes https://github.com/sap/fundamental-ngx/issues/6181
closes https://github.com/SAP/fundamental-ngx/issues/7292

## Description

Fixed Step Input a11y issues

##### During Implementation

1. Visual Testing:

-   [n/a] visual misalignments/updates
-   [n/a] check Light/Dark/HCB/HCW themes
-   [n/a] RTL/LTR - proper rendering and labeling
-   [n/a] responsiveness(resize)
-   [n/a] Content Density (Cozy/Compact/(Condensed))
-   [x] States - hover/disabled/focused/active/on click/selected/selected hover/press state
-   [n/a] Interaction/Animation - open/close, expand/collapse, add/remove, check/uncheck
-   [n/a] Mouse vs. Keyboard support
-   [n/a] Text Truncation

2. API and functional correctness

-   [n/a] check for console logs (warnings, errors)
-   [n/a] API boundary values
-   [n/a] different combinations of components - free style
-   [n/a] change the API values during testing

3. Documentation and Example validations

-   [n/a] missing API documentation or it is not understandable
-   [n/a] poor examples
-   [n/a] Stackblitz works for all examples

4. Accessibility testing
5. Browser Testing - Edge, Safari, Chrome, Firefox

##### PR Quality

-   [x] the commit message(s) follows the guideline:
        https://github.com/SAP/fundamental-ngx/blob/main/CONTRIBUTING.md
-   [n/a] tests for the changes that have been done
-   [x] all items on the PR Review Checklist are addressed :
        https://github.com/SAP/fundamental-ngx/wiki/PR-Review-Checklist
-   [n/a] Run npm run build-pack-library and test in external application
-   [n/a] update `README.md`
-   [n/a] [Breaking Changes Wiki](https://github.com/SAP/fundamental-ngx/wiki/Breaking-Changes)

##### PR Review

-   [x] visual misalignments/updates
-   [x] check Light/Dark/HCB/HCW themes
-   [x] RTL/LTR - proper rendering and labeling
-   [x] responsiveness(resize)
-   [x] Content Density (Cozy/Compact/(Condensed))
-   [x] States - hover/disabled/focused/active/on click/selected/selected hover/press state
-   [x] Interaction/Animation - open/close, expand/collapse, add/remove, check/uncheck
-   [x] Mouse vs. Keyboard support
-   [x] Text Truncation

2. API and functional correctness

-   [x] check for console logs (warnings, errors)
-   [x] API boundary values
-   [x] different combinations of components - free style
-   [x] change the API values during testing

3. Documentation and Example validations

-   [x] missing API documentation or it is not understandable
-   [x] poor examples
-   [x] Stackblitz works for all examples

4. Accessibility testing
5. Browser Testing - Edge, Safari, Chrome, Firefox

### CODE REVIEW

**Comment by InnaAtanasova** [comment]
@Betrozov could you please fix the netlify preview? I can't check the component

**Review by platon-rov — APPROVED** [review]

**Review by dimamarksman — APPROVED** [review]

**Comment by Betrozov** [comment]
> @Betrozov could you please fix the netlify preview? I can't check the component

fixed

**Review by InnaAtanasova — CHANGES_REQUESTED** [review]
I don't see the State messages. It's only the input that changes the color but the popover body does not show. 
Expected behaviour:
Screen Shot 2021-11-30 at 11 09 32 AM
Screen Shot 2021-11-30 at 11 09 23 AM

**Review by InnaAtanasova — APPROVED** [review]
Created a separate issue for the missing message for State Input:
https://github.com/SAP/fundamental-ngx/issues/7292

**Review by mikerodonnell89 — APPROVED** [review]

**Comment by Sanjay-1312** [comment]
Hello Colleagues,

Issue 1: Fixed.

issue 2: 
image

OB: On accessing any step input field, the associated label information is not announced and UI type information is not conveyed.
EB: The associated label should be read, on accessing the input field and UI type should be read.

Issue 3:
image

OB: On accessing the step input ‘input states’, no information is conveyed about the state the step input such as ‘information’, ‘success’, ‘warning’ and ‘error’.
EB: The color  status of the Set input should be conveyed.

OB:On changing the values of set input field, the changed value numbers are not read.
EB: The changed value information should be read.

Retest Details:
 https://deploy-preview-7235--fundamental-ngx.netlify.app
JAWS 2021

**Comment by dimamarksman** [comment]
Created a separate issue to link the label element to ngx form component cause we need it for all form components
https://github.com/SAP/fundamental-ngx/issues/7295

**Comment by Sanjay-1312** [comment]
Issue 2:
Partially Fixed:
OB: On accessing the step input field, its UI type is not conveyed to the user.
EB: Ideally, the UI type should be conveyed to the user.
image

Issue 3: Fixed.

Issue 4: 
image
OB: On changing the values, the label is read, the changed values are not read.
EB: The changed value should be read on increment and decrement. 

Retest Details:
https://deploy-preview-7235--fundamental-ngx.netlify.app
JAWS 2021

**Comment by Sanjay-1312** [comment]
Issue 2: Fixed.

Issue 4: Partially Fixed.
image

Observed Behavior: On changing the value, the changed value is announced along with the label and values are read twice.
Expected Behavior: The Changed value should be read and label should not be announced and values should read once.

Retest Details:
https://deploy-preview-7235--fundamental-ngx.netlify.app
JAWS 2021

**Comment by Sanjay-1312** [comment]
Hello Colleagues,

issue 4: Fixed.

Retest Details:
https://deploy-preview-7235--fundamental-ngx.netlify.app
JAWS 2021

**Pull request merged**
