### PR TITLE
feat: (Core) Introduce dynamic page

### PR DESCRIPTION
**Pull request by JKMarkowski**
#### Please provide a link to the associated issue.
fixes: https://github.com/SAP/fundamental-ngx/issues/4559
#### Please provide a brief summary of this pull request.
There is added core version of DynamicPage component with complete documentation

#### Please check whether the PR fulfills the following requirements

- [x] the commit message follows the guideline:
https://github.com/SAP/fundamental-ngx/blob/main/CONTRIBUTING.md
- [x] tests for the changes that have been done
- [x] all items on the PR Review Checklist are addressed :
https://github.com/SAP/fundamental-ngx/wiki/PR-Review-Checklist

Documentation checklist:
- [x] update `README.md`
- [x] [Breaking Changes Wiki](https://github.com/SAP/fundamental-ngx/wiki/Breaking-Changes)
- [x] Documentation Examples
- [x] Stackblitz works for all examples

### CODE REVIEW

**Comment by mikerodonnell89** [comment]
Floating footer width should not extend to the edge of the window: 

Screen Shot 2021-02-19 at 11 14 13 AM

**Comment by mikerodonnell89** [comment]
The incorrect API is referenced:

Screen Shot 2021-02-19 at 11 27 58 AM

**Review by mikerodonnell89 — CHANGES_REQUESTED** [review]
Awesome job! Just a few small things

**Comment by JKMarkowski** [comment]
Hi @mikerodonnell89 Thanks for review, your comments have been addressed

**Comment by InnaAtanasova** [comment]
Hey @JKMarkowski really great work with this component! I found some minor issues (not really sure the floating footer is related to the current component):
1. Dynamic Page inside Column Layout example:
The buttons are not aligned and the footer is "cut" 
Screen Shot 2021-02-25 at 3 43 47 PM

Closer look to the button: 
Screen Shot 2021-02-25 at 3 44 04 PM
Screen Shot 2021-02-25 at 3 44 09 PM


2. Responsive Dynamic Page
When you change to `Cosy` the buttons are "cut"
Image from iOS

**Review by mikerodonnell89 — APPROVED** [review]
Great work!

**Review by InnaAtanasova — APPROVED** [review]

**Comment by InnaAtanasova** [comment]
`should apply valid height on content` unit test is failing, the rest is great!

**Pull request merged**
