### PR TITLE
fix: (Core) create missing link list variant examples of card

### LINKED ISSUE #3864: Card: Missing variant of a Link list card
####
Is this a bug, enhancement, or feature request?
Feature request

#### Briefly describe your proposal.

It's missing a variant of a Link list card:
https://ux.wdf.sap.corp/fiori-design-web/overview-page-list-cards/#link-list-card

### PR DESCRIPTION
**Pull request by DeepakSap14**
#### Please provide a link to the associated issue.
Closes #3864 

#### Please provide a brief summary of this pull request.
This PR creates examples for variants of Link list cards

#### Please check whether the PR fulfills the following requirements

- [x] the commit message follows the guideline:
https://github.com/SAP/fundamental-ngx/blob/main/CONTRIBUTING.md
- [x] tests for the changes that have been done
- [x] all items on the PR Review Checklist are addressed :
https://github.com/SAP/fundamental-ngx/wiki/PR-Review-Checklist
- [x] Run npm run build-pack-library and test in external application

Documentation checklist:
- na update `README.md`
- na [Breaking Changes Wiki](https://github.com/SAP/fundamental-ngx/wiki/Breaking-Changes)
- [x] Documentation Examples
- [x] Stackblitz works for all examples

### CODE REVIEW

**Comment by InnaAtanasova** [comment]
Shouldn't this be a byline list with links? We already have an example of a Card with List integration.

Screen Shot 2021-04-13 at 3 01 22 PM

**Comment by InnaAtanasova** [comment]
Screen Shot 2021-04-13 at 3 04 08 PM

What's the point of having a list with only 1 element? Also, shouldn't the image be clickable and part of the `li` element int this case?

**Comment by InnaAtanasova** [comment]
Missing the keywords `fixes` or `closes` in the PR template

**Comment by DeepakSap14** [comment]
> Shouldn't this be a byline list with links? We already have an example of a Card with List integration.
> 
> Screen Shot 2021-04-13 at 3 01 22 PM

Here is an issue found in core-list when border-less byline list created.
Screenshot 2021-04-14 at 4 36 47 PM
i have to fix that with change in list component.
Screenshot 2021-04-14 at 8 36 51 PM

currently css change is in this PR, but i will move that css to fundamental-styles with another PR.

**Comment by DeepakSap14** [comment]
> Screen Shot 2021-04-13 at 3 04 08 PM
> 
> What's the point of having a list with only 1 element? Also, shouldn't the image be clickable and part of the `li` element int this case?

1. For creating title and subtitle, i have to use list. There is no other class available which gives these styling.
2. If image is put inside list li element, then padding of 1 rem will apply and will not be able to fill card width.

For resolving these issues, we have raise separate PR.

**Review by InnaAtanasova — CHANGES_REQUESTED** [review]
@DeepakSap14 please check my comment on the other PR https://github.com/SAP/fundamental-ngx/pull/5110

List Card is a different type of Card and it has its own styling that needs to be added first to fund-styles and then implemented in fund-ngx.

**Comment by DeepakSap14** [comment]
@InnaAtanasova this PR has a style class added in list component. 
i have a separate task created to move ngx styles to fundamental-styles. i will work on that first.
i will come to this PR later.

**Pull request closed without merging**
