### PR TITLE
fix(platform): menu-button, fixed accessibility issues

### PR DESCRIPTION
**Pull request by Lukakatche**
## Related Issue(s)
Closes https://github.com/sap/fundamental-ngx/issues/6151

## Description

Fixed accessibility issues for platform menu button component in documentation examples

##### During Implementation

1. Visual Testing:

-   [n/a] visual misalignments/updates
-   [n/a] check Light/Dark/HCB/HCW themes
-   [n/a] RTL/LTR - proper rendering and labeling
-   [n/a] responsiveness(resize)
-   [n/a] Content Density (Cozy/Compact/(Condensed))
-   [n/a] States - hover/disabled/focused/active/on click/selected/selected hover/press state
-   [n/a] Interaction/Animation - open/close, expand/collapse, add/remove, check/uncheck
-   [n/a] Mouse vs. Keyboard support
-   [n/a] Text Truncation

2. API and functional correctness

-   [n/a] check for console logs (warnings, errors)
-   [n/a] API boundary values
-   [n/a] different combinations of components - free style
-   [n/a] change the API values during testing

3. Documentation and Example validations

-   [n/a] missing API documentation or it is not understandable
-   [n/a] poor examples
-   [n/a] Stackblitz works for all examples

4. Accessibility testing
5. Browser Testing - Edge, Safari, Chrome, Firefox

##### PR Quality

-   [x] the commit message(s) follows the guideline:
        https://github.com/SAP/fundamental-ngx/blob/main/CONTRIBUTING.md
-   [ ] tests for the changes that have been done
-   [x] all items on the PR Review Checklist are addressed :
        https://github.com/SAP/fundamental-ngx/wiki/PR-Review-Checklist
-   [ ] Run npm run build-pack-library and test in external application
-   [ ] update `README.md`
-   [ ] [Breaking Changes Wiki](https://github.com/SAP/fundamental-ngx/wiki/Breaking-Changes)

### CODE REVIEW

**Comment by Lukakatche** [comment]
@InnaAtanasova if we use title instead of [title] that gets confused with native html attribute and then title is attached to the component as well as the button inside, therefore screen reader will read it twice.

**Review by Betrozov — APPROVED** [review]

**Comment by Sanjay-1312** [comment]
Hello Colleagues,

Issue 1: As per the above reply.

Issue  2:

OB: The name of the button is reading three times to the user. 
EB: Ideally the button name and type should be read once to the user name followed type of the UI element.

Issue 3:
Same issue persists.
On changing the button name the color status should be read to the user.

Issue 4: Same issue persists

OB: The label name of the button is reading twice to the user.
EB: The label should be conveyed once to the user.

Retest Details:
https://deploy-preview-7040--fundamental-ngx.netlify.app/#/platform/menu-button
JAWS 2021

**Review by platon-rov — APPROVED** [review]

**Comment by Betrozov** [comment]
> Hello Colleagues,
> 
> Issue 2: 
> OB: The name of the button is reading three times to the user.
> EB: Ideally the button name and type should be read once to the user name followed type of the UI element.
> 
> Issue 4: Same issue persists  
> OB: The label name of the button is reading twice to the user.
> EB: The label should be conveyed once to the user.
> 

Hi @Sanjay-1312 
Regarding those 2 issues about reading twice or three times
The first reading is for the button name.
The second reading is for the button title, which is the same as the name
The third reading is for the button type, which is the same as the name and title.

**Comment by Betrozov** [comment]
68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3630623630633032313331383963653537316333323266352f64633339313461632d643631342d343431642d396166352d656664626630373131353466
68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3630623630633032313331383963653537316333323266352f65356135383461302d396537392d346231382d613730382d333034656261303238303866
cc: @Sanjay-1312

**Comment by Sanjay-1312** [comment]
Hello Colleagues,

Issue 2:
The same issue persists
image
I have provided the reference link.
https://sapui5untested.int.sap.eu2.hana.ondemand.com/#/entity/sap.m.Button/sample/sap.m.sample.Button
OB: The name of the button is reading three times to the user.
EB: Ideally the button name and type should be read once to the user name followed type of the UI element.

Issue 3:
image

OB: On accessing the 'Negative', 'Positive' button, the color status of the button is not read.
EB: The button color information should be read to the user. 
image

Issue 4:
OB: The label name of the button is reading twice to the user.
EB: The label should be conveyed once to the user.
https://sapui5untested.int.sap.eu2.hana.ondemand.com/#/entity/sap.m.MenuButton/sample/sap.m.sample.MenuButton

Retest Details:
https://deploy-preview-7040--fundamental-ngx.netlify.app/#/platform/menu-button
JAWS 2021

**Review by InnaAtanasova — APPROVED** [review]

**Pull request closed without merging**
