### PR TITLE
[Proposal] Disable removal icon (WIP)

### PR DESCRIPTION
**Pull request by rossgardt**
#### Please provide a brief summary of this pull request.
It would be great to have a version of the token without the cross icon.
If you are open to accept this, I will prepare a proper PR, including more documentation.

Please **note:** this is just a draft PR as basis for discussion.

#### Please check whether the PR fulfills the following requirements

- [ ] the commit message follows the guideline:
https://github.com/SAP/fundamental-ngx/blob/master/CONTRIBUTING.md
- [ ] tests for the changes that have been done

Documentation checklist:
- [ ] update `README.md`
- [ ] [Breaking Changes Wiki](https://github.com/SAP/fundamental-ngx/wiki/Breaking-Changes)
- [ ] Documentation Examples

### CODE REVIEW

**Comment by droshev** [comment]
@rossgardt thanks for the interest. Of course we can accept it as long as it follows all requirements.

**Comment by rossgardt** [comment]
@droshev Thanks. I will adjust the PR according the guidelines.
Just wanted to make sure it is generally accepted before putting in the work 🙂

**Comment by droshev** [comment]
@rossgardt we are more than happy to get contribution!

**Comment by droshev** [comment]
@rossgardt any update?

**Comment by rossgardt** [comment]
Will push an update by Monday 🙂 
Did not have the time yet, but it is on my list!

**Comment by rossgardt** [comment]
Sorry, I am not able to make time for that right now.

**Pull request closed without merging**
