### PR TITLE
fix: (Platform) add cdk styles to menu component

### PR DESCRIPTION
**Pull request by Betrozov**
#### Please provide a link to the associated issue.
https://github.com/SAP/fundamental-ngx/issues/3972
https://github.com/SAP/fundamental-ngx/issues/3981
https://github.com/SAP/fundamental-ngx/issues/3977
https://github.com/SAP/fundamental-ngx/issues/3980
#### Please provide a brief summary of this pull request.
MenuTriggerDirective works correct
#### Please check whether the PR fulfills the following requirements

- [X] the commit message follows the guideline:
https://github.com/SAP/fundamental-ngx/blob/master/CONTRIBUTING.md

### CODE REVIEW

**Review by InnaAtanasova — APPROVED** [review]

**Comment by puru-hk** [comment]
Tested all the these issues #3972, #3981, #3977, #3980. I think there is some style need to be change please have a look for these issues #3535 , #3650. 

As per the fiori3 visual spec should be 
image

**Comment by Betrozov** [comment]
> Tested all the these issues #3972, #3981, #3977, #3980. I think there is some style need to be change please have a look for these issues #3535 , #3650.
> 
> As per the fiori3 visual spec should be
> image

this PR only for this issue https://github.com/SAP/fundamental-ngx/issues/3972
I think these #3535, #3650 issues should be fixed by separate PRs

**Comment by puru-hk** [comment]
Okay fine I think it looks good for me

**Review by stefanoScalzo — APPROVED** [review]

**Review by KevinOkamoto — COMMENTED** [review]
Looks good.

**Review by olshansky — APPROVED** [review]
Also closes https://github.com/SAP/fundamental-ngx/issues/3908

**Pull request merged**
