### PR TITLE
feat: self contained styles, 0.3.0 adapt

### PR DESCRIPTION
**Pull request by JKMarkowski**
#### Please provide a link to the associated issue.
fixes: https://github.com/SAP/fundamental-ngx/issues/1234
#### Please provide a brief summary of this pull request.
There is 0.3.0 fundamental-styles adaptation with self contained styles. We had to change a lot of components, some of them was refactored during working on this branch, so it caused many conflicts. 

The schematics are also changed. Right now it import `icon.css` and `fonts.css` to angular.json in the project, that uses ngx library.

**Let's not merge it yet until https://github.com/SAP/fundamental-styles/pull/349 is merged. Identifier, select wait for this PR**

### CODE REVIEW

**Comment by JKMarkowski** [comment]
There are some checkbox/radio issues, but it will be fixed in fundamental-styles@0.2.1

**Comment by InnaAtanasova** [comment]
Styling issues:
1. Breadcrumb - items are underlined
Screen Shot 2019-09-25 at 11 34 13 AM

2. Button - `main` and `toolbar` types don't display the correct colors
Screen Shot 2019-09-25 at 11 37 06 AM

3. The border color of the add-ons
Screen Shot 2019-09-25 at 11 38 09 AM

4. Date, Time, DateTime Pickers - missing border/wrong color for the add-on icon
Screen Shot 2019-09-25 at 11 38 22 AM

5. Menu items in dropdown have underline
Screen Shot 2019-09-25 at 11 39 07 AM

6. Input group add-on buttons 
Screen Shot 2019-09-25 at 11 39 53 AM

7. List - items underline
Screen Shot 2019-09-25 at 11 40 04 AM

8. Checkboxes not working (@JKMarkowski already mentioned this) but also when used in forms, additional padding is added
Screen Shot 2019-09-25 at 11 40 24 AM

9. Localization editor menu is broken
Screen Shot 2019-09-25 at 11 40 36 AM

10. Menu with Addon is broken
Screen Shot 2019-09-25 at 11 41 04 AM

11. Search input
Screen Shot 2019-09-25 at 11 42 06 AM

**Comment by JKMarkowski** [comment]
@InnaAtanasova 
#1, #5, #7, #10 - Removed underline on docs styles (following fundamental-styles)
#2 - main/toolbar removed
#3 / #4 /#6 - can't reproduce
#8 - Removed list checkbox component (right now it follows radio buttons in this example)
#9 - To clarify
#11 - Search Input removed

**Comment by JKMarkowski** [comment]
Deploy review on netlify: https://deploy-preview-1307--fundamental-ngx.netlify.com/ I dont know why it's not there.

**Pull request merged**
