### PR TITLE
fix: (Core|Platform) ng xi18n command running on angular/cli@10 fails

### PR DESCRIPTION
**Pull request by dimamarksman**
#### Please provide a link to the associated issue.
Closes:  https://github.com/SAP/fundamental-ngx/issues/4846
#### Please provide a brief summary of this pull request.
This PR is going to fix the error which is thrown while running `ng xi18n` by `@angular/cli@10` in app which imports `fundamental-ngx` modules.

The fix is related to how the lib modules import/export files.

To avoid this issue we have to: 
1. Use direct references to the components/directives files that are declared/exported via a NgModule
2. Avoid barrels imports
3.  Avoid circular dependencies.

#### Please check whether the PR fulfills the following requirements

- [x] the commit message follows the guideline:
https://github.com/SAP/fundamental-ngx/blob/main/CONTRIBUTING.md
- [x] tests for the changes that have been done
- [x] all items on the PR Review Checklist are addressed :
https://github.com/SAP/fundamental-ngx/wiki/PR-Review-Checklist
- [x] Run npm run build-pack-library and test in external application

Documentation checklist:
- [x] update `README.md`
- [x] [Breaking Changes Wiki](https://github.com/SAP/fundamental-ngx/wiki/Breaking-Changes)
- [x] Documentation Examples
- [x] Stackblitz works for all examples

### CODE REVIEW

**Comment by dimamarksman** [comment]
How I tested it.
1. Change angular.json so all `@angular/...` refer to the "~10.2" versions.
2. Update [tsconfig.json](https://github.com/SAP/fundamental-ngx/blob/db72473d8c28b0fca345e8735466b21b3f34391e/apps/docs/tsconfig.json#L8-L13)  references so you have
```
"paths": {
            "@fundamental-ngx/core": [
                "dist/libs/core"
            ],
            "@fundamental-ngx/platform": [
                "dist/libs/platform"
            ]
        }
```
3. `npm run build-artifacts`
4. run `npx ng xi18n docs`

As result you should get generated `messages.xlf` file with i18n messages from fundamental-ngx modules.

**Review by KevinOkamoto — APPROVED** [review]

**Comment by nikvalor** [comment]
Project: null Platform A 
 Url: null 
 This link will expire at

**Comment by nikvalor** [comment]
Project: null Platform B
 Url: null 
 This link will expire at

**Review by mikerodonnell89 — APPROVED** [review]

**Comment by kavya-b** [comment]
> How I tested it.
> 
> 1. Change angular.json so all `@angular/...` refer to the "~10.2" versions.
> 2. `npm i`.
> 3. Update [tsconfig.json](https://github.com/SAP/fundamental-ngx/blob/db72473d8c28b0fca345e8735466b21b3f34391e/apps/docs/tsconfig.json#L8-L13)  references so you have
> 
> ```
> "paths": {
>             "@fundamental-ngx/core": [
>                 "dist/libs/core"
>             ],
>             "@fundamental-ngx/platform": [
>                 "dist/libs/platform"
>             ]
>         }
> ```
> 
> 1. `npm run build-artifacts`
> 2. run `npx ng xi18n docs`
> 
> As result you should get `messages.xlf` file generated with i18n messages from fundamental-ngx modules.

Hi @dimamarksman I also tested this on another dummy app that was already on ng10 and it works without showing up any of the previous errors! However, it also overwrites any existing trans-units on the host app's `messages.xlf`. Is this something this PR addresses or are we considering the overwriting a known issue?

**Review by kavya-b — APPROVED** [review]

**Pull request merged**
