### PR TITLE
fix: Refactor Tabs

### PR DESCRIPTION
**Pull request by JKMarkowski**
#### Please provide a link to the associated issue.
https://github.com/SAP/fundamental-ngx/issues/892
#### Please provide a brief summary of this pull request.
There was needed big refactor for this issue, including adding some directives/components, but now tab component is fully customizable and generic. I added also some unit tests. 
#### If this is a new feature, have you updated the documentation?
Yes, documentation has been updated to show new way to use this component.

### CODE REVIEW

**Comment by MattL75** [comment]
This increases the required markup for tabs significantly. What I had in mind was to keep the directives shown in the issue and the current component as separate. Doing so would keep the markup for both methods of using tabs very simple, and at the same time keep each component/directive simple in their implementation. The ultimate goal of the issue was just to enable using the tabs with a router-outlet. What do you think?

**Comment by JKMarkowski** [comment]
Right now there is possibility to put `[routerLink]` to `<a>` element with `fd-tab-link` directive. To make this fully working and also keep possibility to put normal content like it was before, I had to add additional markups. But yes for using router-outlet it wasn't really needed. I could just add 2 other little directives which would be used only to show nav without panel.

**Comment by MattL75** [comment]
I think it might be simpler to have the two directives and make the two different uses completely separated. This will make it easier for users to consume tabs in both uses, while also making easier for us to maintain these since they will both be simpler individually. @mikerodonnell89 @droshev thoughts?

**Comment by mikerodonnell89** [comment]
In my opinion this is an example of extra markup being a good thing.  The extra flexibility here is crucial.  And having proper HTML semantics (`<nav>, <ul>, <li>`) is nice for accessibility (though I guess that could be improved upon with the previous more strict approach).  Having two directives with different uses would be confusing to someone approaching the tab for the first time.

**Comment by MattL75** [comment]
@mikerodonnell89 I disagree. Having two directives is not confusing at all if properly documented (see Material). In terms of accessibility, including extra markup is not a good thing. See the [guidelines](https://www.w3.org/TR/wai-aria-practices-1.1/#tabpanel), tabs aren't strictly paired with navigation and lists. The extra markup is **very** significant here, we're talking almost twice as much. Maintaining a component with two different modes is also not very practical, with the code often becoming bloated over time.

**Comment by JKMarkowski** [comment]
So @MattL75 , @mikerodonnell89 , @droshev  what is the conclusion, do we keep it as it is on this PR, or should I create new one with 2 additional directives?

**Comment by mikerodonnell89** [comment]
@JKMarkowski consensus was to go the 2 directives route

**Pull request closed without merging**
