### PR TITLE
feat(core,platform): skeleton loading

### PR DESCRIPTION
**Pull request by platon-rov**
## Related Issue(s)

Closes https://github.com/SAP/fundamental-ngx/issues/7838

## Description

* Skeleton component & [docs](https://deploy-preview-9062--fundamental-ngx.netlify.app/#/core/skeleton)

* Examples of using skeleton, although skeleton placeholders can be used anywhere, there are the components which would most likely need skeletons, so it's a quick reference.
  * [Core Card](https://deploy-preview-9062--fundamental-ngx.netlify.app/#/core/card#loading)
  * [Core Table](https://deploy-preview-9062--fundamental-ngx.netlify.app/#/core/table#loading)
  * [Core List](https://deploy-preview-9062--fundamental-ngx.netlify.app/#/core/list#loading)
  * [Core List Byline](https://deploy-preview-9062--fundamental-ngx.netlify.app/#/core/list-byline#list-byline-loading)
  * [Core Facets](https://deploy-preview-9062--fundamental-ngx.netlify.app/#/core/facets#loading)
  * [Core Wizard](https://deploy-preview-9062--fundamental-ngx.netlify.app/#/core/wizard#loading)

* Skeleton placeholders added **in** components which accept data sources, so skeleton placeholders being shown until data comes or no data is provided
  * [Core Timeline](https://deploy-preview-9062--fundamental-ngx.netlify.app/#/core/timeline#basic)
  * [Platform List & Byline](https://deploy-preview-9062--fundamental-ngx.netlify.app/#/platform/list#loading)
  * [Platform Table](https://deploy-preview-9062--fundamental-ngx.netlify.app/#/platform/table#initial-loading)
  * [Platform Value Help Dialog](https://deploy-preview-9062--fundamental-ngx.netlify.app/#/platform/value-help-dialog#initial-loading)
  * [Platform Smart Filter Bar](https://deploy-preview-9062--fundamental-ngx.netlify.app/#/platform/smart-filter-bar#loading)
  * [Platform Form Generator](https://deploy-preview-9062--fundamental-ngx.netlify.app/#/platform/form-generator#loading)
  * [Platform Wizard Generator](https://deploy-preview-9062--fundamental-ngx.netlify.app/#/platform/wizard-generator#loading)

### After:
CleanShot 2022-12-09 at 14 29 10@2x
CleanShot 2022-12-09 at 14 29 20@2x

### CODE REVIEW

**Comment by N1XUS** [comment]
@platon-rov I've noticed that the moment when animation completes and resets is a bit twitchy. Could you maybe try to make the transition from the end of animation to it's initial state more smoother?

**Review by g-cheishvili — APPROVED** [review]
Looks good for me. Just update branch and run migrations after that

**Review by mikerodonnell89 — APPROVED** [review]
This is really great, especially for the platform components where it works out of the box on the datasource. I think there are a few more components there utilizing datasources where it could be useful but I think let's get this merged and we can add more later

**Comment by InnaAtanasova** [comment]
1. I couldn't find an example for List with Byline. Is it going to be the same as the Standard List? Imo we should have a separate case for List with Byline, showing a placeholder for the avatar and then text on 2 lines
2. Platform Action List - the "loading lines" should be in the center

**Review by InnaAtanasova — APPROVED** [review]

**Comment by platon-rov** [comment]
> @platon-rov I've noticed that the moment when animation completes and resets is a bit twitchy. Could you maybe try to make the transition from the end of animation to it's initial state more smoother?

Good catch, improved.

> 1. I couldn't find an example for List with Byline. Is it going to be the same as the Standard List? Imo we should have a separate case for List with Byline, showing a placeholder for the avatar and then text on 2 lines

Added example to core list and implemented in platform list component.

> 2. Platform Action List - the "loading lines" should be in the center

I think we can omit this one because list becomes action list when action items being projected into it, so we have to check this relation, i.e. it increases coupling between components (list & action items). It's different for byline mode because we have input property in the list component so we can decide which skeleton placeholders show by checking its value.

**Review by droshev — APPROVED** [review]

**Pull request merged**
