### PR TITLE
Integrating allure to CI

### PR DESCRIPTION
**Pull request by nikvalor**
#### Please check whether the PR fulfills the following requirements

- [ ] the commit message follows the guideline:
https://github.com/SAP/fundamental-ngx/blob/main/CONTRIBUTING.md
- [ ] tests for the changes that have been done
- [ ] all items on the PR Review Checklist are addressed :
https://github.com/SAP/fundamental-ngx/wiki/PR-Review-Checklist

Documentation checklist:
- [ ] update `README.md`
- [ ] [Breaking Changes Wiki](https://github.com/SAP/fundamental-ngx/wiki/Breaking-Changes)
- [ ] Documentation Examples
- [ ] Stackblitz works for all examples

### CODE REVIEW

**Comment by nikvalor** [comment]
Project: allure-results 
 Url: https://allure-results--pr-4712-bo1gzjsy.web.app 
 This link will expire at Sat 20 Mar 2021 10:56:59 AM GMT

**Review by InnaAtanasova — CHANGES_REQUESTED** [review]
Hi @nikvalor the PR title does not follow the guidelines, the checkboxes in the PR template should be checked or marked as `n/a`, the PR should have reviewers, labels, assignee, project and milestone (all of them are at the right hand side of the GitHun page). We avoid merging code that is commented out. Is there a specific reason all these tests are excluded?

**Comment by nikvalor** [comment]
> Hi @nikvalor the PR title does not follow the guidelines, the checkboxes in the PR template should be checked or marked as `n/a`, the PR should have reviewers, labels, assignee, project and milestone (all of them are at the right hand side of the GitHun page). We avoid merging code that is commented out. Is there a specific reason all these tests are excluded?

It's just PR for the debugging allure integration with Travis CI. So thats why I didn't request any approval

**Comment by InnaAtanasova** [comment]
> > Hi @nikvalor the PR title does not follow the guidelines, the checkboxes in the PR template should be checked or marked as `n/a`, the PR should have reviewers, labels, assignee, project and milestone (all of them are at the right hand side of the GitHun page). We avoid merging code that is commented out. Is there a specific reason all these tests are excluded?
> 
> It's just PR for the debugging allure integration with Travis CI. So thats why I didn't request any approval

ok, you can skip the approval but if you want this PR to be merged you need to handle the PR template and the PR title because it will appear in the release notes. If the checkboxes in the template are not checked, Mergeable will fail so you won't be able to merge it :)

**Comment by nikvalor** [comment]
Project: allure-results Platform A 
 Url:  
 This link will expire at Thu 01 Apr 2021 12:23:20 PM GMT

**Comment by nikvalor** [comment]
Project: allure-results Platform A 
 Url: https://allure-results--platform-a-pr-4712-gs6t72n0.web.app 
 This link will expire at Thu 01 Apr 2021 01:01:40 PM GMT

**Comment by nikvalor** [comment]
Project: allure-results Platform B
 Url: https://allure-results--platform-b-pr-4712-i9ip6x04.web.app 
 This link will expire at Thu 01 Apr 2021 01:03:09 PM GMT

**Comment by nikvalor** [comment]
Project: allure-results CORE 
 Url: https://allure-results--core-pr-4712-u1azq9aw.web.app 
 This link will expire at Thu 01 Apr 2021 01:44:31 PM GMT

**Comment by nikvalor** [comment]
Closed this one. It was only for debugging

**Pull request closed without merging**
