### PR TITLE
bug: datepicker and datetimepicker input validation

### LINKED ISSUE #750: Datetimepicker / Datepicker - keyboard input clears the field
#### Is this a bug, enhancement, or feature request?

bug

#### Briefly describe your proposal.

Changing the date/time via keyboard clears the input field

#### Which versions of Angular and Fundamental NGX are affected? (If this is a feature request, use current version.)

latest

#### If this is a bug, please provide steps for reproducing it.

1) Open datepickers popover (click on input)
2) Set any date using datepicker controls
3) Close datepickers popover
4) Click datepicker input field and adjust date/time using keyboard
5) Click outside or hit tab
6) Data disappears from input

#### Please provide relevant source code if applicable.

n/a

#### Is there anything else we should know?

n/a

### PR DESCRIPTION
**Pull request by mikerodonnell89**
fixes #750

### CODE REVIEW

**Comment by mikerodonnell89** [comment]
@konradkukier2 please have a look at the deployment preview above and let me know if this is what you're looking for, thanks!

**Comment by MattL75** [comment]
If you press backspace and remove the AM/PM on a datetime, it just resets it. Is this intended?

**Comment by mikerodonnell89** [comment]
> If you press backspace and remove the AM/PM on a datetime, it just resets it. Is this intended?

good catch, just pushed a fix

https://github.com/SAP/fundamental-ngx/pull/785/commits/9a359d25aa867e01a5cd27c7d94be68962418c0e

**Comment by MattL75** [comment]
@mikerodonnell89 build failing

**Pull request merged**
