### PR TITLE
fix(core): datetime picker - mobile mode switcher

### PR DESCRIPTION
**Pull request by dmitry-stepanenko**
## Related Issue(s)

closes https://github.com/SAP/fundamental-ngx/issues/5842

## Description
Date time Picker: in Mobile not able to select the date and time in both landscape and portrait mode

### Before:
before
### After:
after

##### During Implementation

1. Visual Testing:

-   [x] visual misalignments/updates
-   [x] check Light/Dark/HCB/HCW themes
-   [x] RTL/LTR - proper rendering and labeling
-   [x] responsiveness(resize)
-   [x] Content Density (Cozy/Compact/(Condensed))
-   [n/a] States - hover/disabled/focused/active/on click/selected/selected hover/press state
-   [x] Interaction/Animation - open/close, expand/collapse, add/remove, check/uncheck
-   [n/a] Mouse vs. Keyboard support
-   [x] Text Truncation

2. API and functional correctness

-   [x] check for console logs (warnings, errors)
-   [n/a] API boundary values
-   [n/a] different combinations of components - free style
-   [n/a] change the API values during testing

3. Documentation and Example validations

-   [n/a] missing API documentation or it is not understandable
-   [n/a] poor examples
-   [n/a] Stackblitz works for all examples

4. Accessibility testing
5. Browser Testing - Edge, Safari, Chrome, Firefox

##### PR Quality

-   [x] the commit message(s) follows the guideline:
        https://github.com/SAP/fundamental-ngx/blob/main/CONTRIBUTING.md
-   [n/a] tests for the changes that have been done
-   [x] all items on the PR Review Checklist are addressed :
        https://github.com/SAP/fundamental-ngx/wiki/PR-Review-Checklist
-   [n/a] Run npm run build-pack-library and test in external application
-   [n/a] update `README.md`
-   [n/a] [Breaking Changes Wiki](https://github.com/SAP/fundamental-ngx/wiki/Breaking-Changes)

### CODE REVIEW

**Review by mikerodonnell89 — CHANGES_REQUESTED** [review]
I am seeing some strange behavior here though I'm confused as to how the changes in this PR could be causing it

https://user-images.githubusercontent.com/2471874/161293746-abf9b232-a8d5-47fe-a5ee-90871a8bda61.mov

**Comment by dmitry-stepanenko** [comment]
> I am seeing some strange behavior here though I'm confused as to how the changes in this PR could be causing it. Note the small empty popover body after attempting to close
> 
>  Screen.Recording.2022-04-01.at.9.22.42.AM.mov

Hey, Mike. That's really odd. I can't replicate it (you can see my recording above). Tried now again, but it closes fine. Are there any additional steps to be made to replicate?

**Comment by dmitry-stepanenko** [comment]
@mikerodonnell89 I took a look at that thing, it can be observed only in netlify preview for some reason. 

The issue is caused by the absence of `.fd-popover__body--hidden` style in `popover.css`. It was a recent refactoring 3 weeks ago, when this class was added to fundamental-styles https://github.com/SAP/fundamental-styles/blob/main/src/styles/popover.scss#L198. 

I can verify that class is present in css file and is pulled properly in local builds or in main. 

Since this change is not related to my PR, I propose to ignore it in the preview of current PR and see how it goes. Maybe it's just sort of a caching issue with netlify

**Comment by g-cheishvili** [comment]
Maybe we could add carousel here on mobile? So that user switches to time picker with one snap, plus calendar and time picker could have been better aligned

**Comment by dmitry-stepanenko** [comment]
@g-cheishvili that's a good point. Updated the component according to how it [behaves in UI5](https://sapui5.hana.ondemand.com/#/entity/sap.m.DateTimePicker/sample/sap.m.sample.DateTimePicker)

https://user-images.githubusercontent.com/33101123/162927351-01218342-9ad5-4beb-b29f-202c3d24a886.mp4

**Comment by mikerodonnell89** [comment]
> Maybe it's just sort of a caching issue with netlify

the most likely explanation. Also I prefer the toggle button over touch scrolling. Approved

**Review by mikerodonnell89 — APPROVED** [review]

**Pull request merged**
