### PR TITLE
docs: update platform README.md with UpToDate info

### PR DESCRIPTION
**Pull request by fkolar**
Added nessesary changes and some fixes.

#### Please provide a link to the associated issue.
#2167

#### Please provide a brief summary of this pull request.

Getting Platform readme up to date. 

#### Please check whether the PR fulfills the following requirements

- [x] the commit message follows the guideline:
https://github.com/SAP/fundamental-ngx/blob/master/CONTRIBUTING.md

Documentation checklist:
- [x] update `README.md`

### CODE REVIEW

**Comment by fkolar** [comment]
> Hi @fkolar , your PR title doesn't follow the guidelines. Since you have 1 commit you need to follow the same guidelines for the commit message for the release notes.

@InnaAtanasova  Understood. Title shoudl ok now.

**Comment by fkolar** [comment]
@InnaAtanasova can you re-check ? Is the title ok now?

**Comment by InnaAtanasova** [comment]
> @InnaAtanasova can you re-check ? Is the title ok now?
> 
> I can see this PR #2163, that is using docs instead of doc.

@fkolar , it should be `docs` according to the Angular guidelines [here](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#type)

**Comment by InnaAtanasova** [comment]
> > @InnaAtanasova can you re-check ? Is the title ok now?
> > I can see this PR #2163, that is using docs instead of doc.
> 
> @fkolar , it should be `docs` according to the Angular guidelines [here](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#type)
And it should use verbs in present time, like "update, change, fix, etc."

**Comment by InnaAtanasova** [comment]
@fkolar since you have only 1 commit when you press the Merge button the title of this one commit will be added later to the release notes (See the attached image). To have more consistent release notes could you please manually change the title to be the same as the PR title? Thank you!
Screen Shot 2020-03-15 at 2 00 58 PM

**Comment by fkolar** [comment]
@InnaAtanasova  I though that we have our own guidelines. Are you saying that it needs to ok with our guidelines plus Angular guidelines ? 

Then let's sync our guidelines with the angular ones

**Comment by fkolar** [comment]
> @fkolar since you have only 1 commit when you press the Merge button the title of this one commit will be added later to the release notes (See the attached image). To have more consistent release notes could you please manually change the title to be the same as the PR title? Thank you!
> Screen Shot 2020-03-15 at 2 00 58 PM

I did inline edit here in github so I need to ammend message from my computer. Let me do it.

**Pull request merged**
