### PR TITLE
feat(platform): propagate ctrlKey from the table row…

### PR DESCRIPTION
**Pull request by robert-isaac-sap**
…mouse/keyboard event

## Description

right now the table component event for navigate doesn't tell if the ctrokey was pressed or not which we need to open the link in the same or a new tab

##### PR Quality

-   [x] the commit message(s) follows the guideline:
        https://github.com/SAP/fundamental-ngx/blob/main/CONTRIBUTING.md

### CODE REVIEW

**Review by mikerodonnell89 — CHANGES_REQUESTED** [review]
We would also need `metaKey` for mac users

**Comment by robert-isaac-sap** [comment]
thanks @mikerodonnell89 
I added it now

**Review by mikerodonnell89 — APPROVED** [review]

**Review by InnaAtanasova — APPROVED** [review]

**Comment by robert-isaac-sap** [comment]
when do you plan to merge it?

**Comment by mikerodonnell89** [comment]
> when do you plan to merge it?

@robert-isaac-sap Can you reopen the PR as a branch directly from this repository, rather than a fork? Our CI is not working with forks at the moment. Then we can merge it

**Comment by mikerodonnell89** [comment]
@robert-isaac-sap We are having some trouble with the CI at the moment but are looking to get this merged asap. Will keep you posted

**Comment by mikerodonnell89** [comment]
PR is good but due to CI issues with outside contributors, closing in favor of https://github.com/SAP/fundamental-ngx/pull/12747

**Pull request closed without merging**
