### PR TITLE
fix: (Core|Platform) bring v.0.14.0 of fundamental-styles

### PR DESCRIPTION
**Pull request by InnaAtanasova**
#### Please provide a brief summary of this pull request.
This PR is bringing version 0.14.0 of Fundamental-styles. 
Changes I made:
- removed custom styling for Flexible column layout. Now it's importing the styling from Fundamental-styles
- removed `fd-dynamic-page__collapsible-header-container--collapsed` class which was removed in Fundamental-styles
- updated Switch component to use the latest class naming
- re-structured Switch component to reflect the latest changes from Fundamental-styles, added a span with optional text for active/inactive state

BREAKING CHANGE:
- input property `optionalText` for Switch has been removed

#### Please check whether the PR fulfills the following requirements

- [x] the commit message follows the guideline:
https://github.com/SAP/fundamental-ngx/blob/master/CONTRIBUTING.md
- [x] tests for the changes that have been done
- [x] all items on the PR Review Checklist are addressed :
https://github.com/SAP/fundamental-ngx/wiki/PR-Review-Checklist

Documentation checklist:
- [na] update `README.md`
- [x] [Breaking Changes Wiki](https://github.com/SAP/fundamental-ngx/wiki/Breaking-Changes)
- [x] Documentation Examples
- [x] Stackblitz works for all examples

### CODE REVIEW

**Comment by mikerodonnell89** [comment]
Message box close button is black (used to be blue) and has this weird focus outline 

Screen Shot 2020-12-15 at 3 43 57 PM

**Comment by InnaAtanasova** [comment]
> Message box close button is black (used to be blue) and has this weird focus outline
> 
> Screen Shot 2020-12-15 at 3 43 57 PM

The button should not be there per specs. The change is out of the scope of this PR and will be fixed in another.

**Review by JKMarkowski — DISMISSED** [review]
LGTM. Could you add removal of `@Input() optionalText` in switch componennt into breaking changes?

**Review by JKMarkowski — CHANGES_REQUESTED** [review]
Could you also rebase it to latest master?
- Action sheet got buttons issue with center
- Tabs now have shadow, maybe it should be removed in documentation
image

**Comment by JKMarkowski** [comment]
Should split button be centered in this case?
split button

**Comment by InnaAtanasova** [comment]
> Should split button be centered in this case?
> split button

Is it in the scope of the PR?

**Comment by InnaAtanasova** [comment]
> Should split button be centered in this case?
> split button

Hi @JKMarkowski it was due to custom styling for button in ngx. I removed it and now it looks ok. Could you please check.

**Review by JKMarkowski — APPROVED** [review]
LGTM. Great job!

**Pull request merged**
