### PR TITLE
chore: #510 enable RTL toggle in the documentation

### LINKED ISSUE #510: enable rtl mode for the documentation
#### Is this a bug, enhancement, or feature request?
enhancement
#### Briefly describe your proposal.
enable RTL toggle in the documentation for the components

### PR DESCRIPTION
**Pull request by droshev**
#### Please provide a link to the associated issue.
fixes #510

### CODE REVIEW

**Comment by mikerodonnell89** [comment]
It is looking like most components will require some additional work

Time picker input padding
screen shot 2019-02-12 at 10 18 38 am
---

Time input padding
screen shot 2019-02-12 at 10 18 25 am
---

Tile icon padding
screen shot 2019-02-12 at 10 18 18 am
---

Side nav w/ multiple levels dropdown icon
screen shot 2019-02-12 at 10 17 49 am
---

Modal close button
screen shot 2019-02-12 at 10 17 09 am
---

Menu items still on the left
screen shot 2019-02-12 at 10 17 00 am
---

List edit icons should be floated left
screen shot 2019-02-12 at 10 16 21 am
---

Not sure what's going on with the parens here
screen shot 2019-02-12 at 10 16 04 am
---

Padding on months (years too)
screen shot 2019-02-12 at 10 24 05 am
---

Status icon order broken
screen shot 2019-02-12 at 10 14 43 am
---

Alert component opened as content are not affected by RTL (might need to be passed as an input?)
screen shot 2019-02-12 at 10 14 28 am
---

Popover alignment should change
screen shot 2019-02-12 at 10 13 57 am
---

Save button padding
screen shot 2019-02-12 at 10 13 45 am

**Comment by droshev** [comment]
We should let @eboyer know

**Comment by droshev** [comment]
@mikerodonnell89 did you do `npm i`?

**Comment by mikerodonnell89** [comment]
@droshev apologies, i had not.  several issues still exist after updating, I've edited my original comment

**Comment by mikerodonnell89** [comment]
We will open separate tickets for the issues I outlined in my comment

**Pull request merged**
