### PR TITLE
#455 added modules to public_api

### PR DESCRIPTION
**Pull request by MattL75**
#### Please provide a link to the associated issue.
#455 

#### Please provide a brief summary of this pull request.
Exposed the calendar, popover, datepicker and toggle apis. Did not expose Utils since there is no point.

### CODE REVIEW

**Comment by damien-murphy** [comment]
Adding these to the public API gives an error during runtime.

```
ERROR in : Unexpected value 'CalendarModule in /xxx/node_modules/fundamental-ngx/fundamental-ngx.d.ts' 
imported by the module 'FundamentalNGXModule in /xxx/src/app/utilities/fundamental-ngx.module.ts'. 
Please add a @NgModule annotation.

ERROR in : Unexpected value 'DatePickerModule in /Users/i070397/git_fsm/portal/crowd-pwa/frontend/node_modules/fundamental-ngx/fundamental-ngx.d.ts' 
imported by the module 'FundamentalNGXModule in /Users/i070397/git_fsm/portal/crowd-pwa/frontend/src/app/utilities/fundamental-ngx.module.ts'. 
Please add a @NgModule annotation.

ERROR in : Unexpected value 'PopoverModule in /Users/i070397/git_fsm/portal/crowd-pwa/frontend/node_modules/fundamental-ngx/fundamental-ngx.d.ts' 
imported by the module 'FundamentalNGXModule in /Users/i070397/git_fsm/portal/crowd-pwa/frontend/src/app/utilities/fundamental-ngx.module.ts'. 
Please add a @NgModule annotation.

ERROR in : Unexpected value 'ToggleModule in /Users/i070397/git_fsm/portal/crowd-pwa/frontend/node_modules/fundamental-ngx/fundamental-ngx.d.ts' imported by the module 'FundamentalNGXModule in /Users/i070397/git_fsm/portal/crowd-pwa/frontend/src/app/utilities/fundamental-ngx.module.ts'. 
Please add a @NgModule annotation.

ERROR in : Unexpected value 'UtilsModule in /Users/i070397/git_fsm/portal/crowd-pwa/frontend/node_modules/fundamental-ngx/fundamental-ngx.d.ts' 
imported by the module 'FundamentalNGXModule in /Users/i070397/git_fsm/portal/crowd-pwa/frontend/src/app/utilities/fundamental-ngx.module.ts'. 
Please add a @NgModule annotation.
```

**Comment by MattL75** [comment]
Can you give us steps to reproduce this? @mikerodonnell89 and I can't seem to reproduce

**Comment by damien-murphy** [comment]
Just imported the Module using the code below

Note: I have commented out the ones that throw the errors and it works as expected

In my app.module.ts I have this import

```
import { FundamentalNGXModule } from './utilities/fundamental-ngx.module';
@NgModule({
  ...
  imports: [
    FundamentalNGXModule.forRoot()
  ]
```

This is the fundamental-ngx.module.ts file

```
import { 
  ActionBarModule,
  AlertModule,
  BadgeLabelModule,
  BreadcrumbModule,
  ButtonGroupModule,
  ButtonModule,
  // CalendarModule,
  ComboboxInputModule,
  // DatePickerModule,
  FormModule,
  IconModule,
  IdentifierModule,
  ImageModule,
  InlineHelpModule,
  InputGroupModule,
  ListModule,
  LoadingSpinnerModule,
  MenuModule,
  ModalModule,
  PaginationModule,
  PanelModule,
  // PopoverModule,
  SearchInputModule,
  ShellbarModule,
  SideNavigationModule,
  TableModule,
  TabsModule,
  TileModule,
  TimeModule,
  TimePickerModule,
  // ToggleModule,
  TreeModule,
  // UtilsModule
} from 'fundamental-ngx';

import { NgModule, ModuleWithProviders } from '@angular/core';

@NgModule({
  imports: [
    ActionBarModule,
    AlertModule,
    BadgeLabelModule,
    BreadcrumbModule,
    ButtonGroupModule,
    ButtonModule,
    // CalendarModule,
    ComboboxInputModule,
    // DatePickerModule,
    FormModule,
    IconModule,
    IdentifierModule,
    ImageModule,
    InlineHelpModule,
    InputGroupModule,
    ListModule,
    LoadingSpinnerModule,
    MenuModule,
    ModalModule,
    PaginationModule,
    PanelModule,
    // PopoverModule,
    SearchInputModule,
    ShellbarModule,
    SideNavigationModule,
    TableModule,
    TabsModule,
    TileModule,
    TimeModule,
    TimePickerModule,
    // ToggleModule,
    TreeModule,
    // UtilsModule
  ],
  exports: [
    ActionBarModule,
    AlertModule,
    BadgeLabelModule,
    BreadcrumbModule,
    ButtonGroupModule,
    ButtonModule,
    // CalendarModule,
    ComboboxInputModule,
    // DatePickerModule,
    FormModule,
    IconModule,
    IdentifierModule,
    ImageModule,
    InlineHelpModule,
    InputGroupModule,
    ListModule,
    LoadingSpinnerModule,
    MenuModule,
    ModalModule,
    PaginationModule,
    PanelModule,
    // PopoverModule,
    SearchInputModule,
    ShellbarModule,
    SideNavigationModule,
    TableModule,
    TabsModule,
    TileModule,
    TimeModule,
    TimePickerModule,
    // ToggleModule,
    TreeModule,
    // UtilsModule
  ],
})

export class FundamentalNGXModule {
  public static forRoot(): ModuleWithProviders {
    return {
      ngModule: FundamentalNGXModule,
      providers: [
      ]
    };
  }
}

```

**Comment by MattL75** [comment]
Honestly not too sure what's wrong. Did you rebuild the library and restart the dev-server?

**Comment by MattL75** [comment]
I packed this PR locally into a .tgz file and installed it in a new application. I do not get these errors and I can use the components such as datepicker and calendar.

We are not exposing the UtilsModule since there is little useful functionality in it.

**Comment by damien-murphy** [comment]
> Honestly not too sure what's wrong. Did you rebuild the library and restart the dev-server?

I just modified the file in my node_modules folder I did not rebuild. This might be why I was still getting that error.

**Pull request merged**
