### PR TITLE
fix(core): tabs, fix collapseOverflow for icon only mode

### PR DESCRIPTION
**Pull request by Betrozov**
#### Please provide a link to the associated issue.
Closes https://github.com/SAP/fundamental-ngx/issues/4424

#### Please provide a brief summary of this pull request.
-  Icon only tabs works
- set collapseOverflowto true by default
#### Please check whether the PR fulfills the following requirements

- [X] the commit message follows the guideline:
https://github.com/SAP/fundamental-ngx/blob/main/CONTRIBUTING.md
- [n/a] tests for the changes that have been done
- [X] all items on the PR Review Checklist are addressed :
https://github.com/SAP/fundamental-ngx/wiki/PR-Review-Checklist
- [X] Run npm run build-pack-library and test in external application

Documentation checklist:
- [n/a] update `README.md`
- [n/a] [Breaking Changes Wiki](https://github.com/SAP/fundamental-ngx/wiki/Breaking-Changes)
- [n/a] Documentation Examples
- [n/a] Stackblitz works for all examples

### CODE REVIEW

**Review by Smiranin — APPROVED** [review]

**Review by platon-rov — CHANGES_REQUESTED** [review]
Please add paddings to the overflow menu items

image

Seems like the overflow menu does not apply to the "Icon Only Tabs Built by defining own template with routerLink":

image

**Comment by Betrozov** [comment]
> Please add paddings to the overflow menu items
> 
> image
> 
> Seems like the overflow menu does not apply to the "Icon Only Tabs Built by defining own template with routerLink":
> 
> image

Hi @platon-rov 
Let's create separate issues for these two issues
For the first issue, we need to discuss it because we do not have styles for it
So, about the second issue, here we use the "fd-tab-nav" directive that does not support overflow like "fd-tab-list" component, we need to discuss it too.

**Review by platon-rov — APPROVED** [review]

**Review by mikerodonnell89 — CHANGES_REQUESTED** [review]
In some instances at specific widths, a tab will be hidden before the "more" popover control appears.  This is the 'Compact Icon Only Tabs Built by passing parameters' example (has 3 tabs at full width):
Screen Shot 2021-08-24 at 1 56 42 PM

> > Please add paddings to the overflow menu items
> > image
> 
> So, about the second issue, here we use the "fd-tab-nav" directive that does not support overflow like "fd-tab-list" component, we need to discuss it too.

This should support overflow just like fd-tab-list.  Feel free to open a second issue for this (possibly in fundamental-styles repo?)

**Comment by puru-hk** [comment]
Issue is not fixed See the below attachment 
Screenshot 2021-08-25 at 14 44 55

**Comment by Betrozov** [comment]
> Issue is not fixed See the below attachment
> Screenshot 2021-08-25 at 14 44 55

Hi @puru-hk 
please see this thread

> > > Please add paddings to the overflow menu items
> > > image
> > 
> > So, about the second issue, here we use the "fd-tab-nav" directive that does not support overflow like "fd-tab-list" component, we need to discuss it too.
> 
> This should support overflow just like fd-tab-list.  Feel free to open a second issue for this (possibly in fundamental-styles repo?)

so I'm going to create an issue for it in fundamental-styles and then it must be fixed in fundamental-ngx

**Comment by puru-hk** [comment]
> d in fundamental-n

Okay

**Comment by Betrozov** [comment]
> In some instances at specific widths, a tab will be hidden before the "more" popover control appears. This is the 'Compact Icon Only Tabs Built by passing parameters' example (has 3 tabs at full width):
> Screen Shot 2021-08-24 at 1 56 42 PM

fixed

**Comment by mikerodonnell89** [comment]
> > Issue is not fixed See the below attachment
> > Screenshot 2021-08-25 at 14 44 55
> 
> Hi @puru-hk
> please see this thread
> 
> > > > Please add paddings to the overflow menu items
> > > > image
> > > 
> > > 
> > > So, about the second issue, here we use the "fd-tab-nav" directive that does not support overflow like "fd-tab-list" component, we need to discuss it too.
> > 
> > 
> > This should support overflow just like fd-tab-list.  Feel free to open a second issue for this (possibly in fundamental-styles repo?)
> 
> so I'm going to create an issue for it in fundamental-styles and then it must be fixed in fundamental-ngx

@Betrozov can you link this issue in styles please

**Review by mikerodonnell89 — COMMENTED** [review]
When resizing the entire window from 362 to 361 pixel width, the icons quickly flicker onto 2 separate rows before collapsing into the "more" overflow (specifically referring to the previously mentioned 'Compact Icon Only Tabs Built by passing parameters' example).  Is this unavoidable?

**Comment by Betrozov** [comment]
> > > Issue is not fixed See the below attachment
> > > Screenshot 2021-08-25 at 14 44 55
> > 
> > 
> > Hi @puru-hk
> > please see this thread
> > > > > Please add paddings to the overflow menu items
> > > > > image
> > > > 
> > > > 
> > > > So, about the second issue, here we use the "fd-tab-nav" directive that does not support overflow like "fd-tab-list" component, we need to discuss it too.
> > > 
> > > 
> > > This should support overflow just like fd-tab-list.  Feel free to open a second issue for this (possibly in fundamental-styles repo?)
> > 
> > 
> > so I'm going to create an issue for it in fundamental-styles and then it must be fixed in fundamental-ngx
> 
> @Betrozov can you link this issue in styles please

@mikerodonnell89 https://github.com/SAP/fundamental-ngx/issues/6426

**Comment by Betrozov** [comment]
> When resizing the entire window from 362 to 361 pixel width, the icons quickly flicker onto 2 separate rows before collapsing into the "more" overflow (specifically referring to the previously mentioned 'Compact Icon Only Tabs Built by passing parameters' example). Is this unavoidable?

@mikerodonnell89  fixed

**Review by mikerodonnell89 — APPROVED** [review]

**Pull request merged**
