### PR TITLE
fix(platform): fix random selection of table checkbox

### LINKED ISSUE #8597: Random selections of checkboxes in treetable
#### Is this a bug, enhancement, or feature request? 
bug

#### Briefly describe your proposal.
When checked the last checkbox (tree table and parent is not expanded), it will auto select some random checkboxes. This is happened when the table has 1 parent with a child and the rest of the rows have no parent.

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)

Angular 13
fundamental library latest version.

#### If this is a bug, please provide steps for reproducing it.
1. Go to platform table component drag and drop. (https://sap.github.io/fundamental-ngx/#/platform/table#tree)
2. click on the third row check box.
3. 2nd row is automatically getting checked.
image

### LINKED ISSUE #8603: [sourcing]: fdp-table - checkboxes are not selected correct if table has parent/child rows
#### Is this a bug, enhancement, or feature request?
Bug
#### Briefly describe your proposal.
- When checked the last checkbox (tree table and parent is not expanded), it will auto select some random checkboxes. This is happened when the table has 1 parent with a child and the rest of the rows have no parent.
#### If this is a bug, please provide steps for reproducing it.
- Create 2 rows with no parent
- Create a parent row and then a child to it
- Create 2 rows with no parent
- If don't expand the parent,
#### Is there anything else we should know?
Showed the issue to Frank, Kevin

### PR DESCRIPTION
**Pull request by skaquib123**
## Related Issue(s)

closes #8597 
closes #8603 

## Description
Issue was wrong index number was passing while we click on checkbox because of which other row was getting selected while we select one particular row.
I changed the selected index of the items of the tree table and passed the correct index.

##### During Implementation

1. Visual Testing:

-   [x] visual misalignments/updates
-   [x] check Light/Dark/HCB/HCW themes
-   [x] RTL/LTR - proper rendering and labeling
-   [x] responsiveness(resize)
-   [x] Content Density (Cozy/Compact/(Condensed))
-   [x] States - hover/disabled/focused/active/on click/selected/selected hover/press state
-   [x] Interaction/Animation - open/close, expand/collapse, add/remove, check/uncheck
-   [x] Mouse vs. Keyboard support
-   [x] Text Truncation

2. API and functional correctness

-   [x] check for console logs (warnings, errors)
-   [x] API boundary values
-   [x] different combinations of components - free style
-   [x] change the API values during testing

3. Documentation and Example validations

-   [x] missing API documentation or it is not understandable
-   [x] poor examples
-   [x] Stackblitz works for all examples

4. Accessibility testing
5. Browser Testing - Edge, Safari, Chrome, Firefox

##### PR Quality

-   [x] the commit message(s) follows the guideline:
        https://github.com/SAP/fundamental-ngx/blob/main/CONTRIBUTING.md
-   [x] tests for the changes that have been done
-   [x] all items on the PR Review Checklist are addressed :
        https://github.com/SAP/fundamental-ngx/wiki/PR-Review-Checklist
-   [x] Run npm run build-pack-library and test in external application
-   [x] update `README.md`
-   [x] [Breaking Changes Wiki](https://github.com/SAP/fundamental-ngx/wiki/Breaking-Changes)

### CODE REVIEW

**Comment by skaquib123** [comment]
@droshev It seems like the netlify is showing some error. I have attached the screenshot of the error.  Can you help me re running the netlify?
image

**Review by mikerodonnell89 — APPROVED** [review]

**Comment by skaquib123** [comment]
@mikerodonnell89 there was a failing unit test that I fixed. FYI.

**Review by platon-rov — APPROVED** [review]

**Review by InnaAtanasova — APPROVED** [review]

**Review by mikerodonnell89 — APPROVED** [review]

**Review by fkolar — APPROVED** [review]
Looks good

**Comment by skaquib123** [comment]
@droshev It seems like I am not authorised to  merge.
image

**Pull request merged**
