### PR TITLE
fix(core): listbox has aria-selected attribute

### PR DESCRIPTION
**Pull request by ZsDeak-SAP**
## Related Issue(s)
 
None, happy to open one if needed.

## Description

`listbox` role cannot be attributed with `aria-selected` [ref](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-selected#associated_roles). this creates  a medium issue on our accessibility audit.

##### During Implementation

1. Visual Testing:

no visual changes

2. API and functional correctness

no API changes

3. Documentation and Example validations

-   [ x] missing API documentation or it is not understandable
-   [ x] poor examples
-   [ x] Stackblitz works for all examples

4. Accessibility testing
5. Browser Testing - Edge, Safari, Chrome, Firefox

##### PR Quality

-   [ x] the commit message(s) follows the guideline:
        https://github.com/SAP/fundamental-ngx/blob/main/CONTRIBUTING.md
-   [ x] tests for the changes that have been done
-   [ x] all items on the PR Review Checklist are addressed :
        https://github.com/SAP/fundamental-ngx/wiki/PR-Review-Checklist
-   [ x] Run npm run build-pack-library and test in external application
-   [ x] update `README.md`
-   [ x] [Breaking Changes Wiki](https://github.com/SAP/fundamental-ngx/wiki/Breaking-Changes)

### CODE REVIEW

**Comment by ZsDeak-SAP** [comment]
@droshev hi, thanks for the approve!
i see one of the tests is failing, could you please advise as to why would that fail? the error message doesn't tell me much....

**Comment by ZsDeak-SAP** [comment]
hi @droshev, `PR checks / Run affected e2e commands (pull_request)`  step keeps failing, do you have any clues what i'm doing wrong for that to fail?

**Review by g-cheishvili — APPROVED** [review]

**Comment by g-cheishvili** [comment]
I think it failed because you have a read-only access to our repo and firebase failed(?)

**Comment by droshev** [comment]
thanks for the PR, we merged with https://github.com/SAP/fundamental-ngx/pull/10608

**Pull request closed without merging**
