### PR TITLE
fix(core,platform): form message issues

### PR DESCRIPTION
**Pull request by platon-rov**
Follow-up https://github.com/SAP/fundamental-styles/pull/4154

## Related Issue(s)

Closes none.

## Description

Fixes various Form Message related issues.

### Before:
image

image

image

### After:
image

image

image

### CODE REVIEW

**Review by InnaAtanasova — CHANGES_REQUESTED** [review]
We are adding band-aids to a big wound. To start, the css for form messages should be in fund-styles. I saw a PR in fund-styles fixing the same issue in a diff way. Apparently this is a big issue which, in my opinion, should be addressed more seriously and in fund-styles, not here. 

Please, create an issue with examples and suggestions and let's tackle it in the next sprint as a big task.

**Comment by platon-rov** [comment]
> We are adding band-aids to a big wound. To start, the css for form messages should be in fund-styles. I saw a PR in fund-styles fixing the same issue in a diff way. Apparently this is a big issue which, in my opinion, should be addressed more seriously and in fund-styles, not here.
> 
> Please, create an issue with examples and suggestions and let's tackle it in the next sprint as a big task.

Here is more explanation about the root of the issue, https://github.com/SAP/fundamental-styles/issues/4202. Probably we have to discuss so I can explain why I have chosen exact this approach.

**Review by InnaAtanasova — APPROVED** [review]
The wiki page for breaking changes should be updated!

**Review by mikerodonnell89 — CHANGES_REQUESTED** [review]
Screenshot 2023-02-13 at 11 25 01 AM

semantic select still looks broken

**Comment by droshev** [comment]
@platon-rov Can we try to prepare this for merging and address all the comments? thanks

**Comment by platon-rov** [comment]
> Screenshot 2023-02-13 at 11 25 01 AM
> 
> semantic select still looks broken

Yea, this pr was waiting for changes in styles. Now we have them, feel free to re review.

**Review by g-cheishvili — APPROVED** [review]
It looks good to me

**Review by mikerodonnell89 — APPROVED** [review]

**Review by mikerodonnell89 — CHANGES_REQUESTED** [review]
failing e2e needs to be fixed

**Review by mikerodonnell89 — APPROVED** [review]

**Pull request merged**
