### PR TITLE
don't merge: demonstrate how to add new items using the form generator

### PR DESCRIPTION
**Pull request by mikerodonnell89**
fixes none

### CODE REVIEW

**Review by g-cheishvili — APPROVED** [review]

**Comment by g-cheishvili** [comment]
I think this is not adding, but just showing existing items. Adding would be if you pushed to some array new item with exact same type as before

**Comment by N1XUS** [comment]
Agree with @g-cheishvili. This example is not something I would consider as "adding", rather just conditionally "showing".

**Review by N1XUS — CHANGES_REQUESTED** [review]

**Comment by mikerodonnell89** [comment]
> I think this is not adding, but just showing existing items. Adding would be if you pushed to some array new item with exact same type as before

That's correct, but from the user's perspective, same thing I think. I'll need to speak to the client if this satisfies their requirements

**Comment by droshev** [comment]
They would need to add fields on the fly.

**Comment by droshev** [comment]
We have the features being implemented [here](https://github.com/SAP/fundamental-ngx/pull/10368)

**Pull request closed without merging**
