### PR TITLE
feat: new content density mechanism

### LINKED ISSUE #9592: Platform Table: Navigable row indicator column not clickable
#### Is this a bug, enhancement, or feature request?

bug

#### Briefly describe your proposal.

FTP Table:

I have enabled `[noVerticalBorders]="true"`

The navigable row indicator (`>`) and cell border of the Organization UI looks disabled and the user cannot click on it.

FD seems to have an issue: when clicking on the `>` column the row is not selected.

https://fundamental-ngx.netlify.app/#/platform/table#navigatable-row

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)

Latest

#### If this is a bug, please provide steps for reproducing it.

FD seems to have an issue: when clicking on the `>` column the row is not selected.

https://fundamental-ngx.netlify.app/#/platform/table#navigatable-row

#### Please provide relevant source code if applicable.

N/A

#### Is there anything else we should know?

DXP organization#538

### LINKED ISSUE #9607: Shellbar input styling broken in compact mode
Placeholder text and magnifying class are positioned too high when switching to compact mode
Screenshot 2023-03-29 at 2 21 01 PM

### LINKED ISSUE #9627: bug: platform select docs page prevents tab keydown event
#### Is this a bug, enhancement, or feature request?
bug
#### Briefly describe your proposal.
1. Go to https://sap.github.io/fundamental-ngx/#/platform/select;
2. Focus on any element;
3. Press tab key

ER: Focus shifts to next focusable item;

AR: Focus doesn't shift.

### LINKED ISSUE #9628: bug(core,platform): select focused button is not by the guidelines
#### Is this a bug, enhancement, or feature request?
visual bug
#### Briefly describe your proposal.
In fundamental-styles we do not set focus on the dropdown button of the select component.
But for the ngx version, we do have focus on the button if the button itself was clicked instead of the whole select component.

How it should be:
image
How it currently is:
image

### PR DESCRIPTION
**Pull request by N1XUS**
## Description
- Migrated content density logic from fundamental-styles;
- Removed all '[component]--compact' classes in favour of unified 'is-compact' and 'is-condensed';
- Updated unit test selectors;
- Updated e2e test selectors;
- Removed changeDetector from contentDensityIObserver and migrated all listeners of contentDensityObserver.isCompact to async contentDensityObserver.isCompact$;
- closes #9627
- closes #9628
- closes #9607
- closes #9592

##### During Implementation

1. Visual Testing:

-   [x] visual misalignments/updates
-   [x] check Light/Dark/HCB/HCW themes
-   [x] RTL/LTR - proper rendering and labeling
-   [x] responsiveness(resize)
-   [x] Content Density (Cozy/Compact/(Condensed))
-   [x] States - hover/disabled/focused/active/on click/selected/selected hover/press state
-   [x] Interaction/Animation - open/close, expand/collapse, add/remove, check/uncheck
-   [x] Mouse vs. Keyboard support
-   [x] Text Truncation

2. API and functional correctness

-   [x] check for console logs (warnings, errors)
-   [x] API boundary values
-   [x] different combinations of components - free style
-   [x] change the API values during testing

3. Documentation and Example validations

-   [x] missing API documentation or it is not understandable
-   [x] poor examples
-   [x] Stackblitz works for all examples

4. Accessibility testing
5. Browser Testing - Edge, Safari, Chrome, Firefox

##### PR Quality

-   [x] the commit message(s) follows the guideline:
        https://github.com/SAP/fundamental-ngx/blob/main/CONTRIBUTING.md
-   [x] tests for the changes that have been done
-   [x] all items on the PR Review Checklist are addressed :
        https://github.com/SAP/fundamental-ngx/wiki/PR-Review-Checklist
-   [x] Run npm run build-pack-library and test in external application
-   [x] update `README.md`
-   [x] [Breaking Changes Wiki](https://github.com/SAP/fundamental-ngx/wiki/Breaking-Changes)

### CODE REVIEW

**Review by mikerodonnell89 — CHANGES_REQUESTED** [review]
Core menu items are not responding to density changes. Also same with combobox, multicombobox, multiinput, i suspect all the same reasons:

https://user-images.githubusercontent.com/2471874/228365509-bd217b5a-aae4-4eac-87f4-8e576df15a54.mov

**Comment by mikerodonnell89** [comment]
Datepicker items still showing in cozy when everything else is compact - could be just a popover contents thing in general? 
Screenshot 2023-03-28 at 3 23 03 PM

**Comment by mikerodonnell89** [comment]
Specs state that the feed input button should always be used in large mode 
Screenshot 2023-03-28 at 3 27 28 PM

**Comment by mikerodonnell89** [comment]
Platform input group focus outlines are behaving odd on this PR but not on the current netlify build for the latest main: https://fundamental-ngx.netlify.app/#/platform/input-group. 

In this first screenshot, after clicking submit, the whole docs page gets focused
Screenshot 2023-03-28 at 3 31 41 PM

And here we see the whole input gets a focus outline
Screenshot 2023-03-28 at 3 31 32 PM

**Comment by N1XUS** [comment]
@mikerodonnell89 Thank you for your review! Please re-check, all items has been addressed.

**Comment by mikerodonnell89** [comment]
Inputs in dialog form are not switching to compact:
Screenshot 2023-03-29 at 1 02 01 PM

**Comment by mikerodonnell89** [comment]
Depending on where exactly I click the select, I see different focus outlines. See this clip:

https://user-images.githubusercontent.com/2471874/228657484-5c328b62-ff82-4b61-8dc4-e23b3f84a336.mov



Should look like this if you click the addon button, I think
Screenshot 2023-03-29 at 2 17 36 PM

**Comment by mikerodonnell89** [comment]
Not caused by this PR, but, possibly related and fixable here? https://github.com/SAP/fundamental-ngx/issues/9607

image

**Comment by mikerodonnell89** [comment]
Another input group focus issue - I noticed the focus outline here now has a border radius
Screenshot 2023-03-29 at 2 48 39 PM

Previously it was a more defined square:
Screenshot 2023-03-29 at 2 49 00 PM

I think all of these focus related issues also need to be moved to fundamental-styles as well

**Comment by N1XUS** [comment]
> Not caused by this PR, but, possibly related and fixable here? #9607
> 
> image

Yes, it is reproducible in main too, so it is not comming from this PR

**Review by mikerodonnell89 — APPROVED** [review]

**Pull request merged**
