### PR TITLE
fix: (Platform) table platform component selected row hover styles

### LINKED ISSUE #4163: Bug: On Table for Platform - entire row need to exhibit interaction hover state. Currently it is just the single left-most column
#### Is this a bug, enhancement, or feature request?
Bug

#### Briefly describe your proposal.
On Table for Platform - entire row need to exhibit interaction hover state. Currently it is just the single left-most column. This is for Single Row Selection, Multiple Row Selection, Column Grouping, and Column Freezing examples on Table.
image

Visual Core states the following:
image
image
image

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
v0.25.0

#### If this is a bug, please provide steps for reproducing it.
Go to: https://sap.github.io/fundamental-ngx/#/platform/table
Scroll down to: Single Row Selection and Multiple Row Selection examples
See error
image

### PR DESCRIPTION
**Pull request by platon-rov**
#### Please provide a link to the associated issue.

Closes #4163.

#### Please provide a brief summary of this pull request.

Table rows are focusable now if enabled any of selection mode (single/multi).

#### Please check whether the PR fulfills the following requirements

- [X] the commit message follows the guideline:
https://github.com/SAP/fundamental-ngx/blob/main/CONTRIBUTING.md
- [X] tests for the changes that have been done
- [X] all items on the PR Review Checklist are addressed :
https://github.com/SAP/fundamental-ngx/wiki/PR-Review-Checklist
- [X] Run npm run build-pack-library and test in external application

Documentation checklist:
- [X] update `README.md`
- [X] [Breaking Changes Wiki](https://github.com/SAP/fundamental-ngx/wiki/Breaking-Changes)
- [X] Documentation Examples
- [x] Stackblitz works for all examples

### CODE REVIEW

**Review by InnaAtanasova — APPROVED** [review]

**Review by olshansky — APPROVED** [review]

**Review by KevinOkamoto — APPROVED** [review]

**Comment by Seamoo13** [comment]
Case where hover state not applied to the whole row:
**STR**
- go to the selection or multiselection examples
- hover over any row by placing the mouse over any cell EXCEPT the checkbox cell

**Actual results:** hover state not applied to the checkbox cell

**Expected results:** hover state should be applied to the entire row
https://sapui5.hana.ondemand.com/#/entity/sap.ui.table.Table/sample/sap.ui.table.sample.Selection

https://user-images.githubusercontent.com/47522152/114831770-6bad1700-9dd6-11eb-9f3d-2969f0c18945.mp4

**Comment by platon-rov** [comment]
> Actual results: hover state not applied to the checkbox cell

@Seamoo13 seems like it's only reproducible on the netlify site because of the cached npm packages, I will raise that question.

**Review by Seamoo13 — APPROVED** [review]

**Comment by pierrom** [comment]
I can see #4163 was closed. Can somebody verify that entire row is highlighted? Looks like checkbox area is excluded - see sample below. Per discussion with @puru-hk - he commented that this is already being worked on. Thanks.
image

**Comment by platon-rov** [comment]
@pierrom, Due to the netlify caching system we're not seeing changes yet. But yea, it's already fixed.

**Pull request merged**
