### PR TITLE
fix: (platform) fix of defects related to Search Field

### PR DESCRIPTION
**Pull request by KevinOkamoto**
#### Please provide a link to the associated issue.
#3086 

#### Please provide a brief summary of this pull request.
The following issues were addressed:

- [x] Platform Search Field: on button hover has wrong styling
- [x] Platform Search Field: the search input is modifying the results and is also case sensitive when camelcasing is part of the word
- [x] Platform Search Field: when long list of data is present and you search a substring, the result popover does not stick to the search field and instead floats.
- [x] Platform Search Filed: Without entering the letter or character autosuggestion is showing, and entering the space bar auto suggestion is showing
- [x] Platform Search Field: Category is not closing even after selected the category from the keyboard.

#### Please check whether the PR fulfills the following requirements

- [x] the commit message follows the guideline:
https://github.com/SAP/fundamental-ngx/blob/master/CONTRIBUTING.md
- [x] all items on the PR Review Checklist are addressed :
https://github.com/SAP/fundamental-ngx/wiki/PR-Review-Checklist

Documentation checklist:
- [x] Documentation Examples

### CODE REVIEW

**Comment by puru-hk** [comment]
Tested this issue it is working fine.

**Comment by InnaAtanasova** [comment]
Search Field with Categories has the following issue:
type something in the input field -> `Input Change Text` updates with the value
delete the value using the delete key, not the cleat button -> one letter of the value remains.

See screenshots:

Screen Shot 2020-09-10 at 4 55 27 PM
Screen Shot 2020-09-10 at 4 55 34 PM

Screen Shot 2020-09-10 at 4 55 12 PM
Screen Shot 2020-09-10 at 4 55 20 PM

**Review by sKudum — APPROVED** [review]
LGTM

**Comment by KevinOkamoto** [comment]
@InnaAtanasova I fixed issue with input text not updating on deletion of last character.

**Review by InnaAtanasova — APPROVED** [review]

**Comment by stefanoScalzo** [comment]
Should take into account spaces, type in Apple with a space, nothing should be there but both apple and pineapple are there

**Review by stefanoScalzo — COMMENTED** [review]
see above

**Comment by dimamarksman** [comment]
LGTM

**Comment by KevinOkamoto** [comment]
@stefanoScalzo Is there a use-case for including leading whitespace in a search term? I can maybe see a case for including trailing whitespace in the search term. Most search fields I've used ignore leading white-space.

**Comment by stefanoScalzo** [comment]
> where

The UI5 Example takes into account whitespaces

**Comment by KevinOkamoto** [comment]
> 
> The UI5 Example takes into account whitespaces

The UI5 Example is also has the following defect mentioned in the defect list:

> Search Filed: Without entering the letter or character autosuggestion is showing. And entering the space bar auto suggestion is showing. to be fixed(suggestions should appear only if atleast one character is input by the user)

in that if you type in one space character, it is matching all strings with one space in the string.

Screen Shot 2020-09-16 at 7 36 55 AM

Isn't it better user experience to trim leading whitespace? In my experience, leading whitespace in the search term is usually done by accident, like when the user cuts-and-pastes a string into the search field.

**Pull request merged**
