### PR TITLE
fix(core): combobox a11y issues

### LINKED ISSUE #5801: Accessibility Testing_Core_Combo box
Hi Team,

Please find the error document attached for Core_Combo box.
[Combobox_Core_Ariba Controls.docx](https://github.com/SAP/fundamental-ngx/files/6713646/Combobox_Core_Ariba.Controls.docx)

### PR DESCRIPTION
**Pull request by dmitry-stepanenko**
## Related Issue.

Closes #5801

## Description
This PR contains fixes for platform combobox component. 

Quick overview of changes according to original doc with issues from the ticket:
Issue 1: cannot reproduce
Issue 2: done
Issue 3: done
Issue 4: done
Issue 5: cannot reproduce
Issue 6: not done (the whole placeholder is pronounced no matter it’s truncated or not)
Issue 7: done
Issue 8: not done (not an issue, inputs with state information/warning/error/success in high contrast themes will have dashed borders according to fundamental-styles)
Issue 9: not done, there's a PR for this https://github.com/SAP/fundamental-ngx/pull/6941
Issue 10: done
Issue 11: cannot reproduce
Issue 12: not done (appears to be not an issue, there's some additional information, but it's not much and it's relevant

Issue 13: cannot reproduce
Issue 14: cannot reproduce
Issue 15: cannot reproduce
Issue 16: cannot reproduce

##### During Implementation

1. Visual Testing:

-   [n/a] visual misalignments/updates
-   [n/a] check Light/Dark/HCB/HCW themes
-   [n/a] RTL/LTR - proper rendering and labeling
-   [n/a] responsiveness(resize)
-   [n/a] Content Density (Cozy/Compact/(Condensed))
-   [x] States - hover/disabled/focused/active/on click/selected/selected hover/press state
-   [x] Interaction/Animation - open/close, expand/collapse, add/remove, check/uncheck
-   [x] Mouse vs. Keyboard support
-   [x] Text Truncation

2. API and functional correctness

-   [x] check for console logs (warnings, errors)
-   [x] API boundary values
-   [n/a] different combinations of components - free style
-   [x] change the API values during testing

3. Documentation and Example validations

-   [x] missing API documentation or it is not understandable
-   [n/a] poor examples
-   [n/a] Stackblitz works for all examples

4. Accessibility testing
5. Browser Testing - Edge, Safari, Chrome, Firefox

##### PR Quality

-   [x] the commit message(s) follows the guideline:
        https://github.com/SAP/fundamental-ngx/blob/main/CONTRIBUTING.md
-   [n/a] tests for the changes that have been done
-   [x] all items on the PR Review Checklist are addressed :
        https://github.com/SAP/fundamental-ngx/wiki/PR-Review-Checklist
-   [n/a] Run npm run build-pack-library and test in external application
-   [n/a] update `README.md`
-   [n/a] [Breaking Changes Wiki](https://github.com/SAP/fundamental-ngx/wiki/Breaking-Changes)

##### PR Review

-   [x] visual misalignments/updates
-   [x] check Light/Dark/HCB/HCW themes
-   [x] RTL/LTR - proper rendering and labeling
-   [x] responsiveness(resize)
-   [x] Content Density (Cozy/Compact/(Condensed))
-   [x] States - hover/disabled/focused/active/on click/selected/selected hover/press state
-   [x] Interaction/Animation - open/close, expand/collapse, add/remove, check/uncheck
-   [x] Mouse vs. Keyboard support
-   [x] Text Truncation

2. API and functional correctness

-   [x] check for console logs (warnings, errors)
-   [x] API boundary values
-   [x] different combinations of components - free style
-   [x] change the API values during testing

3. Documentation and Example validations

-   [x] missing API documentation or it is not understandable
-   [x] poor examples
-   [x] Stackblitz works for all examples

4. Accessibility testing
5. Browser Testing - Edge, Safari, Chrome, Firefox

### CODE REVIEW

**Comment by Sanjay-1312** [comment]
Hello Colleagues,

Issue 1:

OB: The text alternative for the close button is not provided within the mobile dialog.
EB: Ideally, a text alternative for element should be given which fulfills the purpose of the content.

Issue 9:

OB: On entering the data the automatic suggestion list is available and the first letter is not read.
EB: The suggestion list full word should be read should be meaningful.

Retest Details:
https://deploy-preview-6951--fundamental-ngx.netlify.app/#/core/combobox
JAWS 2021

**Comment by dmitry-stepanenko** [comment]
@Sanjay-1312 
for the first issue I see 2 comments above:
> OB: Within the Mobile dialog, the 'Close' button are not reachable using keyboard.

> OB: The text alternative for the close button is not provided within the mobile dialog.

I can't replicate any of those. Attaching the recording 
MacOS
Nov-02-2021 10-27-53
Windows
a
JAWS Output 
image



As for issue 9, there's a requirement https://experience.sap.com/fiori-design-web/combo-box/#autocomplete to bring autocompletion while user types. According to specs, autocompletion is done by selection the non-entered part of the 1st found result. Unfortunately, when this happens, screen reader picks that selection, but not the whole word. I don't think this can be fixed without changing the approach for autocompletion. 
P.s. screen readers behaves exactly the same on SAPUI5 https://sapui5.hana.ondemand.com/#/entity/sap.m.ComboBox/sample/sap.m.sample.ComboBox

**Comment by Sanjay-1312** [comment]
Hello Colleagues,

Issue 1:

OB: On hovering the mouse  to the 'Close' button doesn't have tooltip to describe the purpose of the UI.
EB: Ideally, a text alternative for element should be given which fulfills the purpose of the content.

**Comment by dmitry-stepanenko** [comment]
@Sanjay-1312 done

**Comment by Sanjay-1312** [comment]
issue 1: Fixed.

issue 9:
image
OB: On typing letter in search field, the  automatic suggestion list appears and the list count for the list is not read.
EB: Ideally, the list count should be read when the automatic list appears 

Issue 12:
Observed Behavior:
On activating the combo box, the mobile dialog name 'Title' is not read.
Expected Behavior: 
The dialog name 'Title' should be read on activating the combo box.

Retest Details:
https://deploy-preview-6951--fundamental-ngx.netlify.app/#/core/combobox
JAWS 2021
Windows 10

**Comment by Sanjay-1312** [comment]
Hello Colleagues,

Issue 2 and 12 are fixed.
Hence reported issues are fixed.

Retest Details:
https://deploy-preview-6521--fundamental-ngx.netlify.app/#/platform/value-help-dialog
JAWS 2021

**Comment by Sanjay-1312** [comment]
issue 9:
image
OB: On typing letter in search field, the  automatic suggestion list appears and the list count for the list is not read.
EB: Ideally, the list count should be read when the automatic list appears 

Issue 12:
image
Observed Behavior:
On activating the combo box, the mobile dialog name 'Title' is not read.
Expected Behavior: 
The dialog name 'Title' should be read on activating the combo box.

Retest Details:
https://deploy-preview-6951--fundamental-ngx.netlify.app/#/core/combobox
JAWS 2021
Windows 10

**Comment by puru-hk** [comment]
@Sanjay-1312 I have tested the above issues. It is fixed. Could you please verify once. 

image

image

**Comment by Sanjay-1312** [comment]
Issue 9: Fixed.

Issue 12:
image

OB: On activating the Search here combo box of 'Mobile mode', The dialog appears and the dialog name is read and additional information such as  Title 8 results list items is read.
EB: The additional information such as 'Title 8 result list item' should be removed.
The issue is partially fixed, So please fix the issue.

Retest Details:
https://deploy-preview-6951--fundamental-ngx.netlify.app/#/core/combobox
JAWS 2021

**Review by mikerodonnell89 — CHANGES_REQUESTED** [review]
re: issue 5 - group header does not receive visual focus outline but the element is still tabindexed (and does receive tab focus) via tabindex="0".  I think we should set tabindex to -1 on these group headers

**Comment by dmitry-stepanenko** [comment]
> re: issue 5 - group header does not receive visual focus outline but the element is still tabindexed (and does receive tab focus) via tabindex="0". I think we should set tabindex to -1 on these group headers

@mikerodonnell89 was going to do it, but it appears that we should actually show focus on the group headers according to https://github.com/SAP/fundamental-ngx/issues/3456. So I have brought back the visual focus

**Review by Betrozov — APPROVED** [review]

**Comment by Sanjay-1312** [comment]
Hello Colleagues,

Issue 1 and 9 are fixed.

Retest Details:
https://deploy-preview-6951--fundamental-ngx.netlify.app/#/core/combobox
JAWS 2021

**Review by puru-hk — APPROVED** [review]

**Review by mikerodonnell89 — APPROVED** [review]

**Pull request merged**
