### PR TITLE
fix(platform): tooltip for column size shrink

### LINKED ISSUE #9533: [Sourcing][Reopen] fdp-table : Tooltip for column size shrink with lengthy name
#### Is this a bug, enhancement, or feature request?
Bug

#### Briefly describe your proposal.
Upon column shrinking  resizing - if the column name is lengthy, a tooltip should be shown to the user.

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
angular 15
core / platform : 0.39.1-rc-5

#### If this is a bug, please provide steps for reproducing it.
This is replicable in https://sap.github.io/fundamental-ngx/#/platform/table#default

1) shrink the column
2) text is truncated with elipsis
3) hover on the column 
4) no tooltip displayed

#### Is there anything else we should know?

This is  blocker for guided sourcing.

### PR DESCRIPTION
**Pull request by fkolar**
## Related Issue(s)

closes #9533

## Description

Adds tooltip for the column. Also adds ellipsis for the header text. 
I am not happy with the fix. It adds title for every column and I think what we want is to show the tooltip only if the ellipsis are shown.  Should we add it to the PR or another? 

Still not sure about the best solution for this. 

- After resize is finished lookup the header label element and check if the text is overflowing and only then add the title. 

```ts
// ellipsis visible? 
_isOverflowVisible(el: HTMLElement): boolean {      
        return el.scrollWidth > e.clientWidth
    }
```

Native solution would be just to add 

```html
<span  [attr.title]="_isOverflowVisible (,,) > column.label : null"
```

I think we should do this after resize is finished and then store this informationon the `TableColumn`

##### PR Quality

-   [X ] the commit message(s) follows the guideline:
        https://github.com/SAP/fundamental-ngx/blob/main/CONTRIBUTING.md
-   [x] tests for the changes that have been done
-   [X ] all items on the PR Review Checklist are addressed :
        https://github.com/SAP/fundamental-ngx/wiki/PR-Review-Checklist
-   [x] Run npm run build-pack-library and test in external application
-   [x] update `README.md`
-   [x] [Breaking Changes Wiki](https://github.com/SAP/fundamental-ngx/wiki/Breaking-Changes)

### CODE REVIEW

**Comment by g-cheishvili** [comment]
Maybe we should add an option to disable truncation? Someone might want to wrap or something

**Comment by fkolar** [comment]
> Maybe we should add an option to disable truncation? Someone might want to wrap or something

Good point and just leave default behavior.

**Comment by g-cheishvili** [comment]
> > Maybe we should add an option to disable truncation? Someone might want to wrap or something
> 
> Good point. It is just by spec. header should [never wrap ](https://experience.sap.com/internal/fiori-design-web/grid-table/#column-headers-best-practices).
> 
> I think it does not make much sense to show tooltip for every column, but is it such problem? For performance reason, you need to do this check only once after you resize, which means:
> 
> * save this information to the tableColumn
> * extends `ResizeService` to perform this additional check
> * Extends the  `ResizeService` to access visibleColumns
> * Extends TableRef to also expose `ID`
> * etc..

Yeah, showing tooltip always is not appealing but from performance perspective it makes sense to have all the tooltips visible. @droshev what do you think?
As for the wrap behavior, I think since this is platform component, we can forget about the wrapping here

**Comment by fkolar** [comment]
> After pulling this locally, I'm seeing neither ellipses nor tooltip
> Screenshot 2023-04-03 at 11 00 54 AM

@mikerodonnell89  But None of the Description are shorten on this picture, Tooltips is visible only for the columns that are smaller than text. Can you test on the API Docs locally and see what is the difference between your version and e..g default platform Table?

**Comment by fkolar** [comment]
> Ok I see now, it is working well. Do we want to perform this check on page init as well?

I think it would be too much. Assuming, the hor. scrollbar will always appear so initially columns won't be shrinked. Unless you see some case or way where we can set some fixed width and columns will overlaps their heading labels. 

I was trying to simulate this, but there was always a scrollbar.

**Review by mikerodonnell89 — APPROVED** [review]

**Review by g-cheishvili — APPROVED** [review]

**Pull request merged**
