### PR TITLE
test: (e2e) integrate allure to travis CI

### PR DESCRIPTION
**Pull request by nikvalor**
#### Please provide a link to the associated issue.

[4168](https://app.zenhub.com/workspaces/fundamental-library-5f32933d64202b0012e3572e/issues/sap/fundamental-ngx/4168)

#### Please provide a brief summary of this pull request.

Upload allure report to firebase once tests are finished

#### Please check whether the PR fulfills the following requirements

- [ ] the commit message follows the guideline:
https://github.com/SAP/fundamental-ngx/blob/main/CONTRIBUTING.md
- [ ] tests for the changes that have been done
- [ ] all items on the PR Review Checklist are addressed :
https://github.com/SAP/fundamental-ngx/wiki/PR-Review-Checklist

Documentation checklist:
- [ ] update `README.md`
- [ ] [Breaking Changes Wiki](https://github.com/SAP/fundamental-ngx/wiki/Breaking-Changes)
- [ ] Documentation Examples
- [ ] Stackblitz works for all examples

### CODE REVIEW

**Review by droshev — APPROVED** [review]

**Comment by nikvalor** [comment]
Project: allure-results 
 Url: https://allure-results--pr-4647-h6vjzahq.web.app 
 This link will expire at Thu 18 Mar 2021 03:38:06 PM GMT

**Comment by nikvalor** [comment]
Project: allure-results 
 Url: https://allure-results--pr-4647-h6vjzahq.web.app 
 This link will expire at Fri 19 Mar 2021 09:28:31 AM GMT

**Comment by nikvalor** [comment]
Project: allure-results 
 Url: https://allure-results--pr-4647-h6vjzahq.web.app 
 This link will expire at Fri 19 Mar 2021 09:51:11 AM GMT

**Comment by nikvalor** [comment]
Closed this one. It was only for debugging

**Pull request closed without merging**
