### PR TITLE
feat: Select component - complete refactoring based on material common behaviour (#2744)

### PR DESCRIPTION
**Pull request by JKMarkowski**
BREAKING CHANGE:

This PR also introduces BREAKING CHANGE as binding ``[closeOnOutsideClick]`` was removed. CDK handles all this natively. This binding was specific to Popover functionality

#### Please check whether the PR fulfills the following requirements

- [ ] the commit message follows the guideline:
https://github.com/SAP/fundamental-ngx/blob/master/CONTRIBUTING.md
- [ ] tests for the changes that have been done
- [ ] all items on the PR Review Checklist are addressed :
https://github.com/SAP/fundamental-ngx/wiki/PR-Review-Checklist

Documentation checklist:
- [ ] update `README.md`
- [ ] [Breaking Changes Wiki](https://github.com/SAP/fundamental-ngx/wiki/Breaking-Changes)
- [ ] Documentation Examples
- [ ] Stackblitz works for all examples

### CODE REVIEW

**Comment by fkolar** [comment]
This is getting wild a bit..

**Comment by rengare** [comment]
The PR has conflicts

**Comment by fkolar** [comment]
@JKMarkowski, @droshev  What is the status of this change I did that is moving in and out of the master ?

**Comment by droshev** [comment]
@fkolar I think it is better to ask the material guys to expose the file/component so we can reuse it, instead of copying this from material.

**Pull request closed without merging**
