### PR TITLE
feat: angular 8 version

### PR DESCRIPTION
**Pull request by JKMarkowski**
#### Please provide a link to the associated issue.
fixes: https://github.com/SAP/fundamental-ngx/issues/1281
#### Please provide a brief summary of this pull request.
There is provided a lot of things, related to angular 8 changes. The most important one is docs, which uses IVY compilation and Query/Content reference strategy changes (Added {static: boolean} to every single).
I Added also some important components to public_api,ts.
The angular versions are changed to latest 8.* version.

### CODE REVIEW

**Comment by fkolar** [comment]
The best is the load this to local branch and go thru it. Also Whey did you used `ViewChild` with `static:true` ?
I am asking cuz original behavior was more resolved in `ngAfterViewInit ` not in `ngInit`

**Comment by fkolar** [comment]
- Let's add new node requirements to the package.json as there needs to be node 10+, so we can avoid issue peple are running this with older version of node


**Replace lazy modules with dynamic imports**

```
const routes: Routes = [
    { path: '', loadChildren: './documentation/documentation.module#DocumentationModule' },
    { path: '**', redirectTo: '/home' }
];

// vs
loadChildren: () => import('./documentation/documentation.module').then(m => m.DocumentationModule);

```

`ContentChild, ViewChild`= static option => Shoudl we keep original behaviour or change all to different one. 

`ViewChild` =>In versino 7 all view queries got resolve in ngAfterViewInit, but setting to true it is changed to ngInit

**Comment by droshev** [comment]
If we want to have version `0.11.0` as angular 7 then we need to release `0.11.0` first and then merge this. Let's groom this.

**Comment by fkolar** [comment]
Looks good, just have one question are you sure you want to enable IVY ?

**Comment by JKMarkowski** [comment]
Sure, why shouldn't I ? :d

**Comment by fkolar** [comment]
Its definitelly good move, just many depending apps might fail right away. and we just need to be aware of this. 

Does `docs` app work with this change ?

**Comment by JKMarkowski** [comment]
There is not many apps depending on our `docs` app. `Docs` app works well, you can check preview

**Comment by droshev** [comment]
I squashed the commits and tried to rebase but i ran into tons of errors.

**Pull request merged**
