### PR TITLE
fix: (Core) Update documentation for dialog mobile view

### PR DESCRIPTION
**Pull request by xandrio**
#### Please provide a link to the associated issue.
#5076 

#### Please provide a brief summary of this pull request.
Update documentation for dialog mobile view

#### Please check whether the PR fulfills the following requirements

- [x] the commit message follows the guideline:
https://github.com/SAP/fundamental-ngx/blob/main/CONTRIBUTING.md
- [x] tests for the changes that have been done
- [x] all items on the PR Review Checklist are addressed :
https://github.com/SAP/fundamental-ngx/wiki/PR-Review-Checklist
- [x] Run npm run build-pack-library and test in external application

Documentation checklist:
- [x] update `README.md`
- [x] [Breaking Changes Wiki](https://github.com/SAP/fundamental-ngx/wiki/Breaking-Changes)
- [x] Documentation Examples
- [x] Stackblitz works for all examples

### CODE REVIEW

**Review by mikerodonnell89 — CHANGES_REQUESTED** [review]
I think this is backwards - the mobile dialog should have cozy buttons, but every other dialog should be compact

**Comment by xandrio** [comment]
> I think this is backwards - the mobile dialog should have cozy buttons, but every other dialog should be compact

Yep, I did as you described. Mobile example only changed.

118275541-38da6980-b4cf-11eb-820e-3f439f5b38e8

**Comment by xandrio** [comment]
> I think this is backwards - the mobile dialog should have cozy buttons, but every other dialog should be compact

Thanks! My mistake!

**Comment by droshev** [comment]
if this is updating the documentation there is no way the PR should be labeled `fix`

**Pull request closed without merging**
