### PR TITLE
fix(File Input): Deprecate File Input component.

### PR DESCRIPTION
**Pull request by manu-kr**
#### Please provide a link to the associated issue.
https://github.com/SAP/fundamental-ngx/issues/3042

#### Please provide a brief summary of this pull request.

Remove File Input component from Ngx core, As we introduced new File Uploader component.

#### Please check whether the PR fulfills the following requirements

- [x] the commit message follows the guideline:
https://github.com/SAP/fundamental-ngx/blob/master/CONTRIBUTING.md
- [x ] tests for the changes that have been done
- [x] all items on the PR Review Checklist are addressed :
https://github.com/SAP/fundamental-ngx/wiki/PR-Review-Checklist

Documentation checklist:

- [x] [Breaking Changes Wiki](https://github.com/SAP/fundamental-ngx/wiki/Breaking-Changes)

### CODE REVIEW

**Review by salarenko — COMMENTED** [review]
Looks fine, but I think you missed `apps/docs/src/app/core/api-files.ts`

**Comment by manu-kr** [comment]
> I think we should deprecate this component for at least 1-2 releases before removing it

> Can you please explain the process to deprecate.

**Comment by droshev** [comment]
> > I think we should deprecate this component for at least 1-2 releases before removing it
> 
> > Can you please explain the process to deprecate.

you can see examples with deprecated components/directives/documentation

**Comment by InnaAtanasova** [comment]
Please fix the title, this is not following the naming guidelines!

**Review by droshev — CHANGES_REQUESTED** [review]
the comments are not addressed

**Comment by manu-kr** [comment]
> the comments are not addressed
> 
> > I will address today.

I have addressed your comments. Please have a look.

**Review by droshev — APPROVED** [review]
LGTM

**Comment by manu-kr** [comment]
Deprecating file input component.

**Pull request merged**
