### PR TITLE
feat(platform): refactor dynamic page on top of core

### PR DESCRIPTION
**Pull request by genereg1**
## Related Issue(s)

closes https://github.com/SAP/fundamental-ngx/issues/7168

## Description

- Refactored Platform Dynamic Page built on top of Core implementation.

##### During Implementation

1. Visual Testing:

-   [x] visual misalignments/updates
-   [x] check Light/Dark/HCB/HCW themes
-   [x] RTL/LTR - proper rendering and labeling
-   [x] responsiveness(resize)
-   [x] Content Density (Cozy/Compact/(Condensed))
-   [x] States - hover/disabled/focused/active/on click/selected/selected hover/press state
-   [x] Interaction/Animation - open/close, expand/collapse, add/remove, check/uncheck
-   [x] Mouse vs. Keyboard support
-   [x] Text Truncation

2. API and functional correctness

-   [x] check for console logs (warnings, errors)
-   [n/a] API boundary values
-   [x] different combinations of components - free style
-   [n/a] change the API values during testing

3. Documentation and Example validations

-   [x] missing API documentation or it is not understandable
-   [x] poor examples
-   [x] Stackblitz works for all examples

4. Accessibility testing
5. Browser Testing - Edge, Safari, Chrome, Firefox

##### PR Quality

-   [x] the commit message(s) follows the guideline:
        https://github.com/SAP/fundamental-ngx/blob/main/CONTRIBUTING.md
-   [x] tests for the changes that have been done
-   [x] all items on the PR Review Checklist are addressed :
        https://github.com/SAP/fundamental-ngx/wiki/PR-Review-Checklist
-   [x] Run npm run build-pack-library and test in external application
-   [n/a] update `README.md`
-   [n/a] [Breaking Changes Wiki](https://github.com/SAP/fundamental-ngx/wiki/Breaking-Changes)

### CODE REVIEW

**Review by Betrozov — CHANGES_REQUESTED** [review]
please remove package-lock.json from the PR

**Comment by dimamarksman** [comment]
> please remove package-lock.json from the PR

@Betrozov I have the same issue locally, when trying to run `npm ci` you are getting an error `package-lock not synced`

**Review by dimamarksman — APPROVED** [review]

**Comment by dimamarksman** [comment]
@genereg1 try to fetch the latest from main. Looks like `npm ci` is fine and e2e is fixed as well there

**Review by Betrozov — APPROVED** [review]

**Review by mikerodonnell89 — CHANGES_REQUESTED** [review]
Looks good, but I am commenting because I am wondering if the platform dynamic page should support core's `expandContent` input as well?

**Review by mikerodonnell89 — APPROVED** [review]
LGTM!

**Pull request merged**
