### PR TITLE
fix(core): change styling tabs component

### PR DESCRIPTION
**Pull request by OleksiyDrozdov**
#### Please provide a link to the associated issue.
Closes [#5128](https://github.com/SAP/fundamental-ngx/issues/5128)

#### Please check whether the PR fulfills the following requirements

- [x] the commit message follows the guideline:
https://github.com/SAP/fundamental-ngx/blob/main/CONTRIBUTING.md
- [x] tests for the changes that have been done
- [x] all items on the PR Review Checklist are addressed :
https://github.com/SAP/fundamental-ngx/wiki/PR-Review-Checklist
- [x] Run npm run build-pack-library and test in external application

Documentation checklist:
- [n/a] update `README.md`
- [n/a] [Breaking Changes Wiki](https://github.com/SAP/fundamental-ngx/wiki/Breaking-Changes)
- [n/a] Documentation Examples
- [x] Stackblitz works for all examples

### CODE REVIEW

**Review by InnaAtanasova — COMMENTED** [review]
Will this work without the code being moved to fund-styles and released?

**Comment by InnaAtanasova** [comment]
The right-hand side of the PR needs to be filled - reviewers, labels, milestone, etc.

**Comment by OleksiyDrozdov** [comment]
> code being moved to fund-styles and released

For code to work fund-styles should be released. In order to avoid code duplication I removed part of css from fund-ngx.

**Comment by mikerodonnell89** [comment]
I just built this and tested it in a new project and it does not fix the issue

Screen Shot 2021-06-22 at 4 30 44 PM

**Comment by OleksiyDrozdov** [comment]
@mikerodonnell89 if you install locally https://github.com/SAP/fundamental-styles/pull/2473, connect to local fund-ngx and insert it into your local test project fix will work.

**Comment by OleksiyDrozdov** [comment]
> The right-hand side of the PR needs to be filled - reviewers, labels, milestone, etc.

@InnaAtanasova  Due to access issue I haven't managed to add commit [fix(core): delete styles ](https://github.com/SAP/fundamental-ngx/pull/5735/commits/0f50cc0f9e0050b51876fcec2f193f31800bff0f) to [PR](https://github.com/SAP/fundamental-ngx/pull/5674) and decided to create a new [PR](https://github.com/SAP/fundamental-ngx/pull/5735) (this PR). Now I have all required access rights and the same situation will not be repeated. Apologies if any inconveniences caused.

**Review by InnaAtanasova — APPROVED** [review]

**Review by KevinOkamoto — APPROVED** [review]

**Comment by puru-hk** [comment]
Looks fine.

**Review by puru-hk — APPROVED** [review]

**Review by DeepakSap14 — APPROVED** [review]

**Comment by Seamoo13** [comment]
ran tests through saucelabs locally
all e2e tests (Windows Chrome): PASSED

**Pull request merged**
