### PR TITLE
docs(core): enhance Illustrated Message a11y

### PR DESCRIPTION
**Pull request by olshansky**
#### Please provide a link to the associated issue.
Closes: https://github.com/SAP/fundamental-ngx/issues/4950

#### Please check whether the PR fulfills the following requirements

- [x] the commit message follows the guideline:
https://github.com/SAP/fundamental-ngx/blob/main/CONTRIBUTING.md
- [N/A] tests for the changes that have been done
- [x] all items on the PR Review Checklist are addressed :
https://github.com/SAP/fundamental-ngx/wiki/PR-Review-Checklist
- [N/A] Run npm run build-pack-library and test in external application

Documentation checklist:
- [N/A] update `README.md`
- [N/A] [Breaking Changes Wiki](https://github.com/SAP/fundamental-ngx/wiki/Breaking-Changes)
- [x] Documentation Examples
- [x] Stackblitz works for all examples

### CODE REVIEW

**Review by InnaAtanasova — APPROVED** [review]

**Review by Betrozov — APPROVED** [review]

**Review by sKudum — APPROVED** [review]

**Comment by puru-hk** [comment]
Please find the below comments from the accessibility team
Issue 1: Fixed.

Issue 2: 
image
OB: The tab chain is removed and the tab is given to button but dialog details is not read.
EB: On navigating to the 'Compose' button, the  dialog header 'Inbox' followed by the text element such as 'No new Email check again later and followed by the button name 'Compose' button details should be read at one go.

Issue 3:
image
OB: using JAWS in VPC mode the text should be reachable using the arrow keys.
EB: The text within the dialog need to reachable and read by using arrow keys.
To toogle between the PC and VPC mode in jAWS use insert+z .

Issue 4
OB: The Tool tip is provided as 'Close Dialog' and the tool to information should be read.
image
EB: The tool tip information shouldn't b read only only 'Close' button should be read.

Issue 5: fixed

JAWS 2021
URL: https://deploy-preview-5642--fundamental-ngx.netlify.app/#/core/illustrated-message

**Review by aberikashvili — COMMENTED** [review]
This PR has `tests for the changes that have been done` marked as N/A, but it has 2 changed lines in `.ts` file, UT shouldn't be updated for the changes?

**Comment by olshansky** [comment]
> This PR has `tests for the changes that have been done` marked as N/A, but it has 2 changed lines in `.ts` file, UT shouldn't be updated for the changes?

@aberikashvili these changes in example files, we have no test for examples

**Comment by puru-hk** [comment]
Issue 2
Fixed

Issue 3:
Fixed



Issue 4:
image
OB: On activating the button the focus is available on 'Close' button
EB: on activating the button the dialog and dialog header name header should be read and the first UI element 'Reload' the focus should be available, 

JAWS 2021
URL: https://deploy-preview-5642--fundamental-ngx.netlify.app/#/core/illustrated-message

**Comment by olshansky** [comment]
Updated

**Comment by puru-hk** [comment]
Issue 4: Fixed.

**Pull request merged**
