### PR TITLE
fix(core): datetime picker - a11y issues

### LINKED ISSUE #4663: Date/time Picker: Accessibility Issues
Date/time picker accessibility issues 

Attached screenshot:

[Date.time.Picker.docx](https://github.com/SAP/fundamental-ngx/files/8697565/Date.time.Picker.docx)

### PR DESCRIPTION
**Pull request by dmitry-stepanenko**
## Related Issue(s)

closes #4663 

##### During Implementation

1. Visual Testing:

-   [x] visual misalignments/updates
-   [x] check Light/Dark/HCB/HCW themes
-   [x] RTL/LTR - proper rendering and labeling
-   [x] responsiveness(resize)
-   [x] Content Density (Cozy/Compact/(Condensed))
-   [x] States - hover/disabled/focused/active/on click/selected/selected hover/press state
-   [x] Interaction/Animation - open/close, expand/collapse, add/remove, check/uncheck
-   [x] Mouse vs. Keyboard support
-   [x] Text Truncation

2. API and functional correctness

-   [x] check for console logs (warnings, errors)
-   [x] API boundary values
-   [n/a] different combinations of components - free style
-   [n/a] change the API values during testing

3. Documentation and Example validations

-   [n/a] missing API documentation or it is not understandable
-   [n/a] poor examples
-   [n/a] Stackblitz works for all examples

4. Accessibility testing
5. Browser Testing - Edge, Safari, Chrome, Firefox

##### PR Quality

-   [x] the commit message(s) follows the guideline:
        https://github.com/SAP/fundamental-ngx/blob/main/CONTRIBUTING.md
-   [n/a] tests for the changes that have been done
-   [x] all items on the PR Review Checklist are addressed :
        https://github.com/SAP/fundamental-ngx/wiki/PR-Review-Checklist
-   [n/a] Run npm run build-pack-library and test in external application
-   [n/a] update `README.md`
-   [n/a] [Breaking Changes Wiki](https://github.com/SAP/fundamental-ngx/wiki/Breaking-Changes)

### CODE REVIEW

**Review by InnaAtanasova — APPROVED** [review]

**Comment by Karthickc1994** [comment]
Hello Colleague,

Retest has been taken and the results are below.
Hello Colleague,

Retest has been taken status are below:

Issue1: Fixed
Issue2: Reproducible
Observed behaviour:
When accessing the data picker associated label is not read out.

Expected behaviour:
When accessing the data picket associated label should read out.
Screenshot:

image

Issue3: Not reproducible

Issue4:
Observed behaviour:
The in-place label text does not meet the required ratio of 4.5:1

Expected behaviour:
The in-place label text should satisfy the required ratio of 4.5:1.
Screenshot:

Issue5: Fixed

Issue6:

Observed behaviour:
When accessing the date picker associated label is not read out.

Expected behaviour:
When accessing the date picker associated label should read out.
Screen shot;

image

Issue7: fixed

Issue8:
Observed Behavior:
Ensure ARIA roles, states, and properties are valid


This BUTTON has an aria-controls attribute value of '[object Object]', which includes one or more invalid or duplicate ids
Expected behavior:
Developers must use valid markup and follow the rules of the ARIA specification.
Issue9:Fixed
Issue10: Fixed
Issue11:Fixed
Issue12:Not reproducible
Issue13:Fixed.
Issue14: Fixed.

Retest Environment:

URL: https://fundamental-ngx-gh--pr8102-ds-4663-datetime-pic-hsk3ajq3.web.app/
Browser: chrome Version 102.0.5005.63 (Official Build) (64-bit)
Screen Reader: JAWS 2022.2204.20ILM

Regards,
Karthikeyan.c

**Review by platon-rov — APPROVED** [review]

**Comment by dmitry-stepanenko** [comment]
@Karthickc1994 what ticket are you refering to? In https://github.com/SAP/fundamental-ngx/issues/4663 there're 22 issues and their descriptions are different from what you were testing

**Comment by Karthickc1994** [comment]
Hello Colleague,

Retest has been taken results are below.

Issue1: Fixed
Issue2: Fixed
Issue3: Fixed
Issue4: Fixed
Issue 5:
Checkpoint: ACC-270.5
ACC-270

Observed Behaviour:
There are two tabs stop provided for the time picker element. On the first tab stop the keyboard focus is on the input field on the second tab stop the focus shifts to time picker button highlighted in red.
Screenshot:

image

Expected Behaviour:
Ideally the single tab stop must be provided for the Date/time picker element and the ‘Date/Time Picker’ value help button must be activated through some keyboard shortcuts, thereby reducing the no of tab stops.

Issue6: Fixed
Issue7: Checkpoint: ACC-264.1
ACC-264

Observed Behaviour:
On accessing the input field of the date time input field, the ‘Required’ and Association label Date and Passing Datetime through from object is not announced.

image

image

Expected Behaviour:
Ideally, all visible content and association label, Required field should be conveyed to the user.

Issue8: Fixed

Issue9:
Checkpoint: ACC-264.1
ACC-264

Observed Behaviour:
On accessing the input field of the date time picker, an additional information such as toggle button collapsed is announced.
Screenshot:

image

Expected Behaviour:
Ideally, such additional information must be removed and it will confuse the screen reader user.

Issue10:
Checkpoint: ACC-282.1
ACC-282

Observed Behaviour:
On adapting the screen to 320 pixels, the group header (or) title is truncated.

screenshot:
image

Expected Behaviour:
Ideally, the screen should get adapted and there should be no loss of content.

Issue11: Partially fixed.
Checkpoint: ACC-282.1
ACC-282

Observed Behaviour:
On adapting the screen to 320 pixels, the ‘Cancel’ button is not fully visible.

Expected Behaviour:
Ideally, the ‘Cancel’ button should be fully visible to the user, the buttons should not removed when the screen adapt to the different screen mode.

image

Issue12: Fixed

Issue13: Fixed

Issue14:Fixed

Issue15; Fixed

Issue16: Not reproducible

Issue17: fixed

Issue 18:
Checkpoint: ACC-264.1
ACC-264

Observed Behaviour: Screenshot
On accessing the ‘Calendar’ date the additional information such as contains Controls ; is read out.
Screenshot:

image

Issue 19:
Checkpoint: ACC-260.2
ACC-260

Observed Behaviour:
On adapting the screen to 200% zoom, the ‘Cancel’ button is truncated to the side panel of the screen.

screenshot:
image

Expected Behaviour:
Ideally, the UI shouldn’t get truncated, should be visible to the user.

Issue 20:
Checkpoint: ACC-264.1
ACC-264

Observed Behaviour:
On accessing the ‘Date/Time picker’, any format of input can be entered [numerical, Alphabetic, special characters]. But there is no error indication for this
Screenshot:
image

Expected Behaviour:
User must be provided with a text description of the error, if input errors are detected automatically

Issue21: Fixed.

Retest environment:
https://deploy-preview-8102--fundamental-ngx.netlify.app/#/core/datetime-picker
https://deploy-preview-8102--fundamental-ngx.netlify.app/#/platform/datetime-picker
Browser: Chrome Version 102.0.5005.115 (Official Build) (64-bit)
Screen reader: JAWS 2022.2204.20ILM

Regards,
Karthikeyan.c

**Comment by dmitry-stepanenko** [comment]
Hi @Karthickc1994 

Issue 5 - it's intended behavior, on first tab stop you're able to enter the values manually, on the second you're focused on the button, that allows you to open the popup. This behavior now presents across all components with similar popups.
issue 7 - fixed
issue 9 - not an issue, screen reader describes the state of the popover control button
issue 10 - this is intended behavior, ideally labels should not be so long
issue 11 - fixed
issue 18 - this is the limitation of JAWS, it is not announced it VoiceOver, for example
issue 19 - should not be an issue, if calendar size is bigger than the screen size, there's a scroll available to get to the control buttons
issue 20 - not an issue, that provided value is actually a valid date input, you can see the parsed value under the control. If something invalid is provided, input becomes red

**Pull request merged**
