### PR TITLE
fix(core,platform): date & time pickers - fix i18n

### PR DESCRIPTION
**Pull request by dmitry-stepanenko**
## Related Issue(s)

closes https://github.com/SAP/fundamental-ngx/issues/7609

## Description
Currently i18n of Date Picker - the validation is not working properly. Change the language to German, remove the last digit for the year, the field becomes red (invalid). Add the digit again. The field remains invalid.

This is caused by the `FdDateAdapter` not able to parse dates in any locale except the US one. The reason is actually the native date parsing api, that adapter relies on. In order to be able to parse dates in other locales, we have to use `MomentDatetimeAdapter` in our examples.

##### During Implementation

1. Visual Testing:

-   [n/a] visual misalignments/updates
-   [n/a] check Light/Dark/HCB/HCW themes
-   [n/a] RTL/LTR - proper rendering and labeling
-   [n/a] responsiveness(resize)
-   [n/a] Content Density (Cozy/Compact/(Condensed))
-   [x] States - hover/disabled/focused/active/on click/selected/selected hover/press state
-   [x] Interaction/Animation - open/close, expand/collapse, add/remove, check/uncheck
-   [n/a] Mouse vs. Keyboard support
-   [n/a] Text Truncation

2. API and functional correctness

-   [x] check for console logs (warnings, errors)
-   [x] API boundary values
-   [n/a] different combinations of components - free style
-   [n/a] change the API values during testing

3. Documentation and Example validations

-   [x] missing API documentation or it is not understandable
-   [x] poor examples
-   [n/a] Stackblitz works for all examples

4. Accessibility testing
5. Browser Testing - Edge, Safari, Chrome, Firefox

##### PR Quality

-   [x] the commit message(s) follows the guideline:
        https://github.com/SAP/fundamental-ngx/blob/main/CONTRIBUTING.md
-   [n/a] tests for the changes that have been done
-   [x] all items on the PR Review Checklist are addressed :
        https://github.com/SAP/fundamental-ngx/wiki/PR-Review-Checklist
-   [n/a] Run npm run build-pack-library and test in external application
-   [n/a] update `README.md`
-   [n/a] [Breaking Changes Wiki](https://github.com/SAP/fundamental-ngx/wiki/Breaking-Changes)

### CODE REVIEW

**Review by mikerodonnell89 — COMMENTED** [review]
Our examples using the moment datetime adapter handle validation differently than the fd datetime adapter. With the moment adapter the field doesn't check for validation until it's been cleared entirely then the user types in some invalid value. Should we open a separate issue to get these more in sync? @droshev @dmitry-stepanenko

**Comment by dmitry-stepanenko** [comment]
> Our examples using the moment datetime adapter handle validation differently than the fd datetime adapter. With the moment adapter the field doesn't check for validation until it's been cleared entirely then the user types in some invalid value. Should we open a separate issue to get these more in sync? @droshev @dmitry-stepanenko

Hi, @mikerodonnell89. Validation is there. The thing is `moment` is really flexible in terms of what it can parse, so a lot of expressions that looks invalid, will still be resolved. I've added raw date output for i18n examples, so it's more visual
Feb-16-2022 13-08-49

**Review by platon-rov — COMMENTED** [review]
I'm okay with the changes but if our own adapter doesn't fully meet the requirements & we propose to switch out of using it we need to consider if it's should be present at all. 

I will raise that question on the todays call.

**Comment by platon-rov** [comment]
Okay, we discussed this a bit.

Moment is currently deprecated, so there is not much sense to stick to it tighter. Let's think what we can do, go with native or any other custom solution.

cc @droshev

**Comment by platon-rov** [comment]
We can start using dayjs to avoid implementing (i.e. spending time) our own on top of native. Also, native has some limitations, especially, about locales, so i think it's not the option here. From what i see dayjs is the smallest alternative but its api very close to the momentjs and some not included initially features can be achieved using plugins.

Another option - date-fns, that, accordingly to the comparison table, has all the features but is a way bigger by its size, has less locales than dayjs and its api haven't been designed to mimic momentjs.

here is the whole comparison table: https://github.com/you-dont-need/You-Dont-Need-Momentjs/blob/master/README.md#feature-parity

cc @droshev @g-cheishvili @N1XUS @dmitry-stepanenko

**Comment by platon-rov** [comment]
MomentJS issue ticket https://github.com/SAP/fundamental-ngx/issues/7904

**Comment by platon-rov** [comment]
We discussed it yesterday, most probably we will be switching to the another library (dayjs or date-fns).

**Comment by dmitry-stepanenko** [comment]
@mikerodonnell89 @platon-rov now when we have updated dayjs adapter, I think we can proceed with this one

**Review by platon-rov — APPROVED** [review]

**Pull request merged**
