### PR TITLE
fix(core): prevent error on missing menuService

### PR DESCRIPTION
**Pull request by ErfanNaz**
#### Please provide a brief summary of this pull request.
menuService is defined as optional and can be null. Checks added to prevent error when menuService is null.

#### Please check whether the PR fulfills the following requirements

- [x] the commit message follows the guideline:
https://github.com/SAP/fundamental-ngx/blob/main/CONTRIBUTING.md
- [na] tests for the changes that have been done
- [na] all items on the PR Review Checklist are addressed :
https://github.com/SAP/fundamental-ngx/wiki/PR-Review-Checklist
- [na] Run npm run build-pack-library and test in external application

Documentation checklist:
- [na] update `README.md`
- [na] [Breaking Changes Wiki](https://github.com/SAP/fundamental-ngx/wiki/Breaking-Changes)
- [na] Documentation Examples
- [na] Stackblitz works for all examples

### CODE REVIEW

**Comment by InnaAtanasova** [comment]
Hey @ErfanNaz thank you so much for your contribution. Please sign the CLA so we can merge your PR. Thank you!

**Review by dimamarksman — APPROVED** [review]

**Review by mikerodonnell89 — CHANGES_REQUESTED** [review]
Thank you for this PR, just one thing I'd like to request which is in the `_setMenuService` function, let's change the line `this.menuService = this.menuService || this._submenu.menuService;` to `this.menuService = this.menuService || this._submenu?.menuService;` - because `_submenu` may be undefined and not have a menuService (note the added `?` after _submenu)

**Comment by ErfanNaz** [comment]
> Thank you for this PR, just one thing I'd like to request which is in the `_setMenuService` function, let's change the line `this.menuService = this.menuService || this._submenu.menuService;` to `this.menuService = this.menuService || this._submenu?.menuService;` - because `_submenu` may be undefined and not have a menuService (note the added `?` after _submenu)

good catch, i have made the changes

**Comment by Seamoo13** [comment]
I ran tests locally since Travis env variables are not available to external contributors:
unit tests (core): PASSED
unit tests (platform): PASSED
all e2e tests (Windows Chrome): PASSED

**Pull request merged**
