### PR TITLE
fix(platform): fill suggestions with selected state

### LINKED ISSUE #7082: bug: multi-combobox(platform): mark that item is selected disappear after you click 'Show selected items' and get back to list of all items
#### Is this a bug, enhancement, or feature request?
bug
#### Briefly describe your proposal.
mark that item is selected disappear after you click 'Show selected items' and get back to list of all items
#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
0.33.0
#### If this is a bug, please provide steps for reproducing it.
Open https://fundamental-ngx.netlify.app/#/platform/multi-combobox#mobile
Click on multi-combobox
Select any item in the list
Click on button 'Show selected items
Click on button 'Show all items
Expected: you came back to the list with all items, selected items before still selected
Actual result: items not selected

### PR DESCRIPTION
**Pull request by xandrio**
## Related Issue(s)
Closes https://github.com/SAP/fundamental-ngx/issues/7082

## Description

Fill suggestions with selected values

### CODE REVIEW

**Review by InnaAtanasova — APPROVED** [review]
Nice work!

**Review by Betrozov — APPROVED** [review]

**Comment by Betrozov** [comment]
Hi @xandrio  
Please do not remove the PR template from your future PRs.

**Review by mikerodonnell89 — APPROVED** [review]

**Review by platon-rov — COMMENTED** [review]
@nickiovenko @Betrozov i think this pr should be reassigned as Alexander not working anymore as i understand.

**Comment by mikerodonnell89** [comment]
@platon-rov @nickiovenko @Betrozov i assigned it to myself and fixed the merge conflicts, going to let this build and test the preview, then merge to main

**Comment by nickiovenko** [comment]
@mikerodonnell89 Thank you!

**Pull request merged**
