### PR TITLE
[WIP] test: storybook tests

### PR DESCRIPTION
**Pull request by stefanoScalzo**
#### Please provide a link to the associated issue.
#1954 #2104 
#### Please provide a brief summary of this pull request.
This PR will add storybook for most existing fiori 3 components 
#### Please check whether the PR fulfills the following requirements

- [x] the commit message follows the guideline:
https://github.com/SAP/fundamental-ngx/blob/master/CONTRIBUTING.md
- [x] tests for the changes that have been done

Documentation checklist:
- [x] update `README.md`
- [x] [Breaking Changes Wiki](https://github.com/SAP/fundamental-ngx/wiki/Breaking-Changes)
- [x] Documentation Examples
- [x] Stackblitz works for all examples

Changes:
- Updated to the latest storybook packages
- Refactored Bar storybook
- Refactored Breadcrumb storybook

### CODE REVIEW

**Comment by stefanoScalzo** [comment]
Add knobs for text

**Comment by droshev** [comment]
Here are my comments:
Side Navigation:
- compact knobs doesn't seem to work
- text only is not working properly
Screen Shot 2020-02-21 at 10 13 27 AM
- the alignment looks broken
Screen Shot 2020-02-21 at 10 17 53 AM
Screen Shot 2020-02-21 at 10 17 47 AM

Select a11y issue 
Screen Shot 2020-02-21 at 10 20 25 AM

Product Switch 
- a11y issues
Screen Shot 2020-02-21 at 10 20 56 AM
- rendering issue
Screen Shot 2020-02-21 at 10 21 25 AM

**Comment by stefanoScalzo** [comment]
@droshev side nav is actually not a bad alignment. Just realized its a bug when we have mixture of icons and no icons and nesting

**Comment by droshev** [comment]
@stefanoScalzo something is wrong with the PR. It is touching platform files

**Comment by droshev** [comment]
@stefanoScalzo this PR is going out of control. We won't merge a PR with that many commits(48 at the moment) and touched files that are nothing to do with the PR

**Comment by droshev** [comment]
It would be better if we split the PR in small PRs => closing this PR

**Pull request closed without merging**
