### PR TITLE
fix: (Core) Accessibility: Combobox: No focus indication

### PR DESCRIPTION
**Pull request by mykolavorobiov**
#### Please provide a link to the associated issue.
[3458](https://github.com/SAP/fundamental-ngx/issues/3458)
#### Please provide a brief summary of this pull request.
In this PR I have fixed focus state for input group, because combobox implement that into content.

Before
image
image
After
image
image
image

#### Please check whether the PR fulfills the following requirements

- [x] the commit message follows the guideline:
https://github.com/SAP/fundamental-ngx/blob/main/CONTRIBUTING.md
- [x] tests for the changes that have been done
- [x] all items on the PR Review Checklist are addressed :
https://github.com/SAP/fundamental-ngx/wiki/PR-Review-Checklist

Documentation checklist:
- [x] [Breaking Changes Wiki](https://github.com/SAP/fundamental-ngx/wiki/Breaking-Changes)

### CODE REVIEW

**Review by Betrozov — APPROVED** [review]

**Review by IlyaSurmay — APPROVED** [review]

**Review by dimamarksman — APPROVED** [review]

**Review by mikerodonnell89 — CHANGES_REQUESTED** [review]
A nitpicky detail, but the Fiori specs have the focus outline remain around the icon button when active or hovered.  See here: https://experience.sap.com/fiori-design-web/combo-box/#behavior-and-interaction

However in this PR the focus outline will disappear when the button is active/hovered
Screen Shot 2020-12-28 at 10 31 51 AM

**Comment by mykolavorobiov** [comment]
> A nitpicky detail, but the Fiori specs have the focus outline remain around the icon button when active or hovered. See here: https://experience.sap.com/fiori-design-web/combo-box/#behavior-and-interaction
> 
> However in this PR the focus outline will disappear when the button is active/hovered
> Screen Shot 2020-12-28 at 10 31 51 AM
> 
> This may need to be addressed in the styles repo

@mikerodonnell89 Thanks for your attend. I will do styles fix in another PR to the styles repo.
Also we need to set up `in-focus` class on main box manually. And changes in this PR covered that.

**Comment by stefanoScalzo** [comment]
> > A nitpicky detail, but the Fiori specs have the focus outline remain around the icon button when active or hovered. See here: https://experience.sap.com/fiori-design-web/combo-box/#behavior-and-interaction
> > However in this PR the focus outline will disappear when the button is active/hovered
> > Screen Shot 2020-12-28 at 10 31 51 AM
> > This may need to be addressed in the styles repo
> 
> @mikerodonnell89 Thanks for your attend. I will do styles fix in another PR to the styles repo.
> Also we need to set up `in-focus` class on main box manually. And changes in this PR covered that.

This is currently being fixed here https://github.com/SAP/fundamental-styles/pull/1973 LGTM

**Review by stefanoScalzo — APPROVED** [review]

**Review by mikerodonnell89 — APPROVED** [review]
Approving this since my comments are being addressed in styles

**Pull request merged**
