### PR TITLE
docs: fix playground background color 

### PR DESCRIPTION
**Pull request by droshev**
#### Please provide a link to the associated issue.
fixes: #3127

### CODE REVIEW

**Comment by nikvalor** [comment]
Project: allure-results CORE 
 Url: https://allure-results--core-pr-4856-kmj9h6bm.web.app 
 This link will expire at Sun 04 Apr 2021 12:56:29 AM GMT

**Comment by nikvalor** [comment]
Project: allure-results Platform B
 Url: https://allure-results--platform-b-pr-4856-hg6bp4y1.web.app 
 This link will expire at Sun 04 Apr 2021 01:07:42 AM GMT

**Comment by nikvalor** [comment]
Project: allure-results Platform A 
 Url: https://allure-results--platform-a-pr-4856-4xgk2luy.web.app 
 This link will expire at Sun 04 Apr 2021 01:12:48 AM GMT

**Comment by mikerodonnell89** [comment]
Don't we want a white background here?

Screen Shot 2021-03-09 at 2 55 56 PM

**Review by mikerodonnell89 — CHANGES_REQUESTED** [review]
Don't we want a white background here?

Screen Shot 2021-03-09 at 2 55 56 PM

**Comment by droshev** [comment]
> Don't we want a white background here?
> 
> Screen Shot 2021-03-09 at 2 55 56 PM

but in dark themes it doesn't work well

**Comment by InnaAtanasova** [comment]
Agree with @mikerodonnell89 
You can use either transparent or --sapObjectHeader_Background
Screen Shot 2021-03-10 at 11 03 22 AM

**Comment by droshev** [comment]
> Agree with @mikerodonnell89
> You can use either transparent or --sapObjectHeader_Background
> Screen Shot 2021-03-10 at 11 03 22 AM

Even if i don't agree i did it.

**Review by InnaAtanasova — APPROVED** [review]

**Review by mikerodonnell89 — APPROVED** [review]

**Pull request merged**
