### PR TITLE
fix: (core) toolbar enhancements

### PR DESCRIPTION
**Pull request by olshansky**
#### Please provide a link to the associated issue.
Closes: https://github.com/SAP/fundamental-ngx/issues/2890
Closes: https://github.com/SAP/fundamental-ngx/issues/3018
#### Please check whether the PR fulfills the following requirements

- [x] the commit message follows the guideline:
https://github.com/SAP/fundamental-ngx/blob/master/CONTRIBUTING.md
- [x] tests for the changes that have been done
- [x] all items on the PR Review Checklist are addressed :
https://github.com/SAP/fundamental-ngx/wiki/PR-Review-Checklist

Documentation checklist:
- [x] Documentation Examples
- [x] Stackblitz works for all examples

### CODE REVIEW

**Comment by JKMarkowski** [comment]
Hi @olshansky Code looks great for me. Just one thing that bothers me 
toolbarpriority
As you can see high/low priority are treated same. I guess this is also the reason why overflow button goes outside on lower resolutions

**Comment by olshansky** [comment]
@JKMarkowski thanks, fixed

**Comment by stefanoScalzo** [comment]
Screen Shot 2020-08-17 at 2 29 28 PM
i dont think its normal that they are all disappearing with this much space left

**Comment by mikerodonnell89** [comment]
In the overflow priority example, "high" gets moved to overflow before "button first".  I think any item without a specified priority should be moved before high priority items

**Comment by olshansky** [comment]
@stefanoScalzo I believe that it's correct according to the specifications:
> Child elements can be grouped so that they can "overflow" together.

**Comment by olshansky** [comment]
@mikerodonnell89 note from fiori design guidelines: 
> The priority of each item is high by default. If two items have equal priority, the item on the right side overflows first.

`button first` has the same priority as the button `high`, but the button `high` on the right side of `button first`. So, it's correct behavior

**Comment by olshansky** [comment]
As for a11y

> All child elements should be keyboard accessible
> - User should be able to "tab" navigate through all child elements.
> - User should be able to click "enter" to invoke action on the child elements.
>
> The overflow menu should be keyboard accessible.
> - User should be able to click "enter" to open the overflow menu.
> - User should be able to navigate the overflow menu using "up" and "down" arrow keys.
_____

> - User should be able to click "enter" to invoke action on the child elements.

I think it's related to the implementation of each child component, because of components could have different behavior on occurred action _(click, space or enter keypress)_

> - User should be able to navigate the overflow menu using "up" and "down" arrow keys.

It's a popover component and could be implemented in a separate PR.
_____
I could make a separate issue and describe these notes if necessary. Please, ping me if it necessary to do

**Comment by KevinOkamoto** [comment]
A minor issue - is there a way to get rid of the button flicker as the toolbar is resized? Can we add a check to see if the set of visible buttons change in the `_collapseItems()` function, or something similar?

**Comment by olshansky** [comment]
@KevinOkamoto with checking it's not so easy as I expected. But I got rid of flickering similar as much as possible now to UI5 examples

**Review by salarenko — APPROVED** [review]

**Pull request merged**
