### PR TITLE
fix(platform): action-bar, fix a11y issues

### PR DESCRIPTION
**Pull request by Betrozov**
## Related Issue
closes https://github.com/sap/fundamental-ngx/issues/6092

## Description

Fixed action-bar i11y issues

##### During Implementation

1. Visual Testing:

-   [n/a] visual misalignments/updates
-   [n/a] check Light/Dark/HCB/HCW themes
-   [n/a] RTL/LTR - proper rendering and labeling
-   [n/a] responsiveness(resize)
-   [n/a] Content Density (Cozy/Compact/(Condensed))
-   [n/a] States - hover/disabled/focused/active/on click/selected/selected hover/press state
-   [n/a] Interaction/Animation - open/close, expand/collapse, add/remove, check/uncheck
-   [n/a] Mouse vs. Keyboard support
-   [n/a] Text Truncation

2. API and functional correctness

-   [n/a] check for console logs (warnings, errors)
-   [n/a] API boundary values
-   [n/a] different combinations of components - free style
-   [n/a] change the API values during testing

3. Documentation and Example validations

-   [n/a] missing API documentation or it is not understandable
-   [n/a] poor examples
-   [n/a] Stackblitz works for all examples

4. Accessibility testing
5. Browser Testing - Edge, Safari, Chrome, Firefox

##### PR Quality

-   [x] the commit message(s) follows the guideline:
        https://github.com/SAP/fundamental-ngx/blob/main/CONTRIBUTING.md
-   [n/a] tests for the changes that have been done
-   [x] all items on the PR Review Checklist are addressed :
        https://github.com/SAP/fundamental-ngx/wiki/PR-Review-Checklist
-   [n/a] Run npm run build-pack-library and test in external application
-   [n/a] update `README.md`
-   [n/a] [Breaking Changes Wiki](https://github.com/SAP/fundamental-ngx/wiki/Breaking-Changes)

### CODE REVIEW

**Review by genereg1 — APPROVED** [review]

**Review by dmitry-stepanenko — APPROVED** [review]

**Review by platon-rov — APPROVED** [review]

**Comment by Veerakarthick** [comment]
Hello Colleague,

Retest has been taken below are the details.

Issue1:
Observed Behavior:
On accessing the ‘Save’ button, its associated texts are not read.
Expected Behavior:
Ideally, all important information visually conveyed to the user must be read.
screenshot:
image

issue2:
Observed Behavior:
The text alternative or tooltip for the ‘More’ button, is not provided.
Expected Behavior:
Ideally, a text alternative for element should be given which fulfills the purpose of the content
Screenshot:
image

issue3:
Observed Behavior:
On accessing the ‘More’ button, its UI name ‘More’ is not read.
Expected Behavior:
Ideally, the name of the UI should be communicated to the user when accessed.
Screen shot:
image

issue4:
Observed Behavior:
On resizing the screen to 320CSS pixels, the texts are truncated and Horizontal scroll is available.
Expected Behavior:
The screen layout must be scaled so that there is no loss of either content, affordance, or function.
screenshot:
image

issue5: Partially fixed
Observed Behavior:
On resizing the screen to 200% zoom, text are truncated no alternative provided for the truncated text.
Expected Behavior:
The screen layout must be scaled so that there is no loss of either content, affordance, or function.

Screenshot:
image


Retest Environment:
URL:https://deploy-preview-7413--fundamental-ngx.netlify.app
Browser:Chrome Version 96.0.4664.110 (Official Build) (64-bit)
Screen reader: JAWS2021.2111.13 ILM




Regards,
Karthikeyan.c

**Comment by genereg1** [comment]
Hello @Veerakarthick 
As I see in your screenshots you tested A11y issues in Action Bar Core implementation when the issue and the PR relates to Platform implementation 
Please recheck it in Action Bar Platform

**Comment by Veerakarthick** [comment]
Hello Colleague,

The URL: is not working please check and provide me the update landscape for retest.

URL used for retest: 
https://fundamental-ngx-gh--pr7413-fix-action-bar-a11y-aug6grw5.web.app/

Regards,
Karthikeyan.c

**Comment by Karthickc1994** [comment]
Hello Colleague,

Retest has been taken with the below environment the test results are below.

Issue 1: Fixed.
Issue 2: Fixed.
Issue 3: Fixed.
Issue 4: Fixed.
Issue 5: Fixed.

Retest Environment:
URL: https://deploy-preview-7413--fundamental-ngx.netlify.app/
Component: Platform
Browser: Version 101.0.4951.54 (Official Build) (64-bit)
Screen Reader: JAWS 2022.2204.20ILM

Regards,
Karthikeyan.c

**Comment by Karthickc1994** [comment]
Hello Colleague,

Retest has been taken with the below environment the test results are below.

Issue 1: Fixed.
Issue 2: Fixed.
Issue 3: Fixed.
Issue 4: Fixed.
Issue 5: Fixed.

Retest Environment:
URL: https://deploy-preview-7413--fundamental-ngx.netlify.app/
Component: Platform
Browser: Version 101.0.4951.54 (Official Build) (64-bit)
Screen Reader: JAWS 2022.2204.20ILM

Regards,
Karthikeyan.c

**Pull request merged**
