### PR TITLE
fix(platform): fixing accessibility of step input component

### PR DESCRIPTION
**Pull request by web-dev23**
## Related Issue(s)

Closes https://github.com/SAP/fundamental-ngx/issues/6140

##### During Implementation

1. Visual Testing:

-   [x] visual misalignments/updates
-   [x] check Light/Dark/HCB/HCW themes
-   [x] RTL/LTR - proper rendering and labeling
-   [x] responsiveness(resize)
-   [x] Content Density (Cozy/Compact/(Condensed))
-   [x] States - hover/disabled/focused/active/on click/selected/selected hover/press state
-   [x] Interaction/Animation - open/close, expand/collapse, add/remove, check/uncheck
-   [x] Mouse vs. Keyboard support
-   [x] Text Truncation

2. API and functional correctness

-   [x] check for console logs (warnings, errors)
-   [x] API boundary values
-   [x] different combinations of components - free style
-   [x] change the API values during testing

3. Documentation and Example validations

-   [x] missing API documentation or it is not understandable
-   [x] poor examples
-   [x] Stackblitz works for all examples

4. Accessibility testing
5. Browser Testing - Edge, Safari, Chrome, Firefox

##### PR Quality

-   [x] the commit message(s) follows the guideline:
        https://github.com/SAP/fundamental-ngx/blob/main/CONTRIBUTING.md
-   [x] tests for the changes that have been done
-   [x] all items on the PR Review Checklist are addressed :
        https://github.com/SAP/fundamental-ngx/wiki/PR-Review-Checklist
-   [x] Run npm run build-pack-library and test in external application
-   [x] update `README.md`
-   [x] [Breaking Changes Wiki](https://github.com/SAP/fundamental-ngx/wiki/Breaking-Changes)

##### PR Review

-   [x] visual misalignments/updates
-   [x] check Light/Dark/HCB/HCW themes
-   [x] RTL/LTR - proper rendering and labeling
-   [x] responsiveness(resize)
-   [x] Content Density (Cozy/Compact/(Condensed))
-   [x] States - hover/disabled/focused/active/on click/selected/selected hover/press state
-   [x] Interaction/Animation - open/close, expand/collapse, add/remove, check/uncheck
-   [x] Mouse vs. Keyboard support
-   [x] Text Truncation

2. API and functional correctness

-   [x] check for console logs (warnings, errors)
-   [x] API boundary values
-   [x] different combinations of components - free style
-   [x] change the API values during testing

3. Documentation and Example validations

-   [x] missing API documentation or it is not understandable
-   [x] poor examples
-   [x] Stackblitz works for all examples

4. Accessibility testing
5. Browser Testing - Edge, Safari, Chrome, Firefox

### CODE REVIEW

**Comment by web-dev23** [comment]
Issue 1 - fixed
Issue 2 - fixed
Issue 3 - probably expected behaviour, this is by design as aria-labelledby of the input component is set to input's label where tooltip is included.
Issue 4 - unable to replicate

**Review by genereg1 — APPROVED** [review]

**Comment by platon-rov** [comment]
> Issue 1 - fixed Issue 2 - fixed Issue 3 - probably expected behaviour, this is by design as aria-labelledby of the input component is set to input's label where tooltip is included. Issue 4 - unable to replicate

please post this in the description section of pr, not in the comments.

**Review by platon-rov — APPROVED** [review]
I found that using arrow up, arrow down doesn't change value. It's implemented in the SAPUI5 and it's about accessibility so I think it can be done in the scope of this pr but it's fully up to you, separate pr can be opened.

**Comment by Sanjay-1312** [comment]
Issue 1:
image

OB: On accessing the spin box, the changed values are not read but the associated label name is read on changing the values.
EB; On increasing or deceasing the value using the arrow keys, the changed value should be read.

For Reference:
https://sapui5untested.int.sap.eu2.hana.ondemand.com/#/entity/sap.m.StepInput/sample/sap.m.sample.StepInputValueState

Issue 2: Fixed.

Issue 3:  As per the design. Fixed

Issue 4: Not reproducible.  Fixed

Retest Details:
https://deploy-preview-7116--fundamental-ngx.netlify.app/#/platform/step-input
JAWS 2021

**Comment by web-dev23** [comment]
> Issue 1: image
> 
> OB: On accessing the spin box, the changed values are not read but the associated label name is read on changing the values. EB; On increasing or deceasing the value using the arrow keys, the changed value should be read.
> 
> For Reference: https://sapui5untested.int.sap.eu2.hana.ondemand.com/#/entity/sap.m.StepInput/sample/sap.m.sample.StepInputValueState
> 
> Issue 2: Fixed.
> 
> Issue 3: As per the design. Fixed
> 
> Issue 4: Not reproducible. Fixed
> 
> Retest Details: https://deploy-preview-7116--fundamental-ngx.netlify.app/#/platform/step-input JAWS 2021

Unable to replicate Issue 1
image

**Review by dimamarksman — APPROVED** [review]

**Comment by Sanjay-1312** [comment]
Issue 1:
image
OB: On accessing the spin box, the changed values are not read but the associated label name is read on changing the values. EB; On increasing or deceasing the value using the arrow keys, the changed value should be read.

Retest Details:
https://deploy-preview-7116--fundamental-ngx.netlify.app/#/platform/step-input 
JAWS 2021

**Comment by Sanjay-1312** [comment]
Issue 1:

image

Observed Behaviour: On activating the ‘increasing and Decreasing’ button, the changed value is not read instead the label is read.
Expected Behaviour:  Ideally, the changed values such should be read on changing the values and label shouldn’t be read.
For Reference:
https://sapui5untested.int.sap.eu2.hana.ondemand.com/#/entity/sap.m.StepInput/sample/sap.m.sample.StepInputValueState

Retest Details:
https://deploy-preview-7116--fundamental-ngx.netlify.app/#/platform/step-input
JAWS 2021

**Comment by Karthickc1994** [comment]
Hello Colleague,

Retest has been taken the results are below:

All the issues are fixed with the below environment: 

QA approved.

Retest Environment:
URL: https://deploy-preview-7116--fundamental-ngx.netlify.app/
Browser: Version 101.0.4951.54 (Official Build) (64-bit)
Screen Reader: JAWS 2022.2204.20 ILM

Regards,
Karthikeyan.c

**Pull request closed without merging**
