### PR TITLE
fix(core): carousel fund-styles changes adoption.

### PR DESCRIPTION
**Pull request by platon-rov**
## Related Issue(s)

Part of https://github.com/SAP/fundamental-ngx/issues/7984#issuecomment-1128547535

## Description

Fund-Styles changes adoptions for the Carousel component.

### CODE REVIEW

**Comment by platon-rov** [comment]
> This appears to affect the margin between the carousel and images but that is ok, right?

It's existing issue but okay, let's fix it in scope of this pr. 

`[BLOCKED]` by https://github.com/SAP/fundamental-styles/pull/3439

**Comment by g-cheishvili** [comment]
Can you check why tests are failing?

**Comment by InnaAtanasova** [comment]
Screen Shot 2022-05-20 at 1 20 13 PM
Screen Shot 2022-05-20 at 1 19 47 PM

Should the Carousel get an outline?

**Comment by platon-rov** [comment]
> Can you check why tests are failing?

some of them fails because of changes on the `pr/chore/styles-bump-breaking-changes-adoption` and should be fixed there. but i've fixed carousel related ones.

**Review by g-cheishvili — APPROVED** [review]

**Pull request merged**
