### PR TITLE
docs(core): added swipe dialog example

### PR DESCRIPTION
**Pull request by IB002**
## Related Issue(s)

https://github.com/SAP/fundamental-ngx/issues/6047

## Description

Adds a swipe dialog example

### CODE REVIEW

**Review by mikerodonnell89 — COMMENTED** [review]
It looks like lint was skipped for this, I'd recommend resetting the commit and attempting again without `--no-verify`

**Review by droshev — CHANGES_REQUESTED** [review]
I don't see swiping here
not-swiping

Also can you make the first and second level list to be with the same size? The different sizes brings even more confusion.

**Comment by g-cheishvili** [comment]
I do not think that "swipe" is the term we are looking for here. It is more of an multi page dialog, similar to what we have in mobile menu with children

**Review by droshev — CHANGES_REQUESTED** [review]
I still don't see the swiping effect on the item clicking.

**Comment by droshev** [comment]
It can be reopened when there is someone who can bring the swipping

**Pull request closed without merging**
