### PR TITLE
docs(core): select examples

### PR DESCRIPTION
**Pull request by web-dev23**
#### Please provide a link to the associated issue.
Closes https://github.com/SAP/fundamental-ngx/issues/4391

#### Please provide a brief summary of this pull request.
Fixes Select component Stackblitz examples.

#### Please check whether the PR fulfills the following requirements

- [x] the commit message follows the guideline:
https://github.com/SAP/fundamental-ngx/blob/main/CONTRIBUTING.md
- [x] tests for the changes that have been done
- [x] all items on the PR Review Checklist are addressed :
https://github.com/SAP/fundamental-ngx/wiki/PR-Review-Checklist
- [x] Run npm run build-pack-library and test in external application

Documentation checklist:
- [x] update `README.md`
- [x] [Breaking Changes Wiki](https://github.com/SAP/fundamental-ngx/wiki/Breaking-Changes)
- [x] Documentation Examples
- [x] Stackblitz works for all examples

### CODE REVIEW

**Review by Betrozov — APPROVED** [review]

**Review by N1XUS — APPROVED** [review]

**Comment by maxym-valor** [comment]
New error in Stackblitz

**Comment by dimamarksman** [comment]
> New error in Stackblitz
> image

@Seamoo13 it's [another issue](https://github.com/SAP/fundamental-ngx/issues/5591)

**Review by InnaAtanasova — APPROVED** [review]

**Comment by web-dev23** [comment]
> New error in Stackblitz
> image

Fixed.

**Comment by maxym-valor** [comment]
Approved!

**Pull request merged**
