### PR TITLE
feat(platform): split platform into libraries

### PR DESCRIPTION
**Pull request by olshansky**
#### Please provide a link to the associated issue.
Closes: https://github.com/SAP/fundamental-ngx/issues/5912

#### Please provide a brief summary of this pull request.
Split platform library into multiple sub-packages.
- Libraries are built with nx instead of ng;
- All main platform modules are now built as separate sub-packages;
- Recommended way of importing files from the platform library now is following:
```typescript
import { PlatformButtonModule } from '@fundamental-ngx/platform/button';
```
- Structure of fundamental-ngx/platform was refactored to allow splitting it into separate sub-packages;
- Platform documentation has been updated with the appropriate import paths;
- TSPath has been updated to reflect all separate submodules paths;
- root tsconfig.json has been renamed to tsconfig.base.json;
- folders from utils has been moved to a separate shared sub-package;
- each library contains own tsconfig.json file with strict mode disabled, and can be enabled on per-package basis;
- Now it is possible to launch module-specific unit tests by using `nx test platform-[module-name]` command

#### Please check whether the PR fulfills the following requirements

- [x] the commit message follows the guideline:
https://github.com/SAP/fundamental-ngx/blob/main/CONTRIBUTING.md
- [x] tests for the changes that have been done
- [x] all items on the PR Review Checklist are addressed :
https://github.com/SAP/fundamental-ngx/wiki/PR-Review-Checklist
- [n/a] Run npm run build-pack-library and test in external application

Documentation checklist:
- [x] update `README.md`
- [x] [Breaking Changes Wiki](https://github.com/SAP/fundamental-ngx/wiki/Breaking-Changes)
- [x] Documentation Examples
- [n/a] Stackblitz works for all examples

### CODE REVIEW

**Review by dimamarksman — APPROVED** [review]

**Review by Smiranin — APPROVED** [review]

**Comment by InnaAtanasova** [comment]
Question: Denis from my team made the split in a way that the old way is still supported. Basically both options are currently possible. Is it the case with the Platform split?

**Comment by Betrozov** [comment]
> Question: Denis from my team made the split in a way that the old way is still supported. Basically both options are currently possible. Is it the case with the Platform split?

Hi @InnaAtanasova 
Yes, the old way is still supported

**Comment by N1XUS** [comment]
@Betrozov I see some failing unit tests in core lib. Does it has something to do with the PR?

**Review by N1XUS — APPROVED** [review]

**Comment by Betrozov** [comment]
> @Betrozov I see some failing unit tests in core lib. Does it has something to do with the PR?

Travis fixed

**Review by droshev — APPROVED** [review]

**Pull request merged**
