### PR TITLE
feat(core): split into libraries

### PR DESCRIPTION
**Pull request by N1XUS**
#### Please provide a link to the associated issue.
Closes SAP/fundamental-ngx#5359

#### Please provide a brief summary of this pull request.

Split core library into multiple sub-packages, while still keeping legacy way of imports.
- Libraries are built with nx instead of ng;
- All main core modules are now built as separate sub-packages;
- Recommended way of importing files from the core library now is following:
```typescript
import {DialogModule, DialogService} from '@fundamental-ngx/core/dialog';
```
- Structure of fundamental-ngx/core was refactored to allow splitting it into separate sub-packages;
- CarouselModule now in the Carousel namespace instead of utils;
- AlertService, DialogService, NotificationService, MessageToastService, ThemesService are removed from providers array in FundamentalNgxCoreModule;
- Core documentation has been updated with the appropriate import paths;
- TSPath has been updated to reflect all separate submodules paths;
- root tsconfig.json has been renamed to tsconfig.base.json;
- tests folder from utils has been moved to a separate sub-package;
- each library contains own tsconfig.json file with strict mode disabled, and can be enabled on per-package basis;
- *.spec.ts files are excluded from dependency graph calculation for nx;
- Now it is possible to launch module-specific unit tests by using `nx test core-[module-name]` command

#### Please check whether the PR fulfills the following requirements

- [x] the commit message follows the guideline:
https://github.com/SAP/fundamental-ngx/blob/main/CONTRIBUTING.md
- [x] tests for the changes that have been done
- [x] all items on the PR Review Checklist are addressed :
https://github.com/SAP/fundamental-ngx/wiki/PR-Review-Checklist
- [x] Run npm run build-pack-library and test in external application

Documentation checklist:
- [x] update `README.md`
- [x] [Breaking Changes Wiki](https://github.com/SAP/fundamental-ngx/wiki/Breaking-Changes)
- [x] Documentation Examples
- [x] Stackblitz works for all examples

### CODE REVIEW

**Comment by platon-rov** [comment]
Please resolve conflicts, provide some description, maybe relative issues.

**Comment by N1XUS** [comment]
> Please resolve conflicts, provide some description, maybe relative issues.

Done. Thank you!

**Comment by platon-rov** [comment]
Please fix Travis's unit tests.

**Comment by dimamarksman** [comment]
These PR changes are so huge, it makes my chrome page unresponsive :(

**Comment by N1XUS** [comment]
> Please fix Travis's unit tests.

Unit tests are fixed.

**Comment by N1XUS** [comment]
> These PR changes are so huge, it makes my chrome page unresponsive :(

I would suggest checking it locally. There are lots of minor changes like import paths, the most crucial part to check is the structure, configuration files, and namespace logic for the sub-packages.

**Review by Betrozov — APPROVED** [review]

**Review by platon-rov — APPROVED** [review]

**Review by InnaAtanasova — APPROVED** [review]

**Pull request merged**
