### PR TITLE
test: added allure to Travis CI build

### PR DESCRIPTION
**Pull request by nikvalor**
#### Please provide a link to the associated issue.
[4828](https://app.zenhub.com/workspaces/fundamental-library-5f32933d64202b0012e3572e/issues/sap/fundamental-ngx/4828)
#### Please provide a brief summary of this pull request.
Added allure to Travis CI build

#### Please check whether the PR fulfills the following requirements

- [x] the commit message follows the guideline:
https://github.com/SAP/fundamental-ngx/blob/main/CONTRIBUTING.md
- [x] tests for the changes that have been done
- [x] all items on the PR Review Checklist are addressed :
https://github.com/SAP/fundamental-ngx/wiki/PR-Review-Checklist

Documentation checklist:
- [x] update `README.md`
- [x] [Breaking Changes Wiki](https://github.com/SAP/fundamental-ngx/wiki/Breaking-Changes)
- [x] Documentation Examples
- [x] Stackblitz works for all examples

### CODE REVIEW

**Comment by nikvalor** [comment]
Project: allure-results Platform B
 Url: https://allure-results--platform-b-pr-4829-y60yffak.web.app 
 This link will expire at Thu 01 Apr 2021 04:12:47 PM GMT

**Comment by nikvalor** [comment]
Project: null CORE 
 Url: null 
 This link will expire at

**Comment by nikvalor** [comment]
Project: null Platform A 
 Url: null 
 This link will expire at

**Comment by nikvalor** [comment]
Project: allure-results CORE 
 Url: https://allure-results--core-pr-4829-p43cda70.web.app 
 This link will expire at Thu 01 Apr 2021 05:22:35 PM GMT

**Comment by nikvalor** [comment]
Project: allure-results Platform A 
 Url: https://allure-results--platform-a-pr-4829-z1bb47ui.web.app 
 This link will expire at Thu 01 Apr 2021 05:31:10 PM GMT

**Review by Seamoo13 — APPROVED** [review]
looks nice, great job!

**Review by AntonOlkhovskyi — APPROVED** [review]

**Review by InnaAtanasova — APPROVED** [review]

**Pull request merged**
