### PR TITLE
fix(platform): Update info bar table to reflect selected filters

### PR DESCRIPTION
**Pull request by khotcholava**
fix(platform): table showing info bar with selected filters

closes [#11783](https://github.com/SAP/fundamental-ngx/issues/11783)

- Implemented an info bar beneath the table toolbar to display active filters, following SAP Fiori design recommendations.
- Used <fd-toolbar fdType="info" [active]="true"> from Fundamental NGX.
- Displayed filter information with the correct format
- Included a "decline" icon in the info bar.
- Info bar appears only when a filter is applied and hides once the filter is reset.
- Added feature to close the popover when the dismiss button is clicked. The popover will reappear upon changing the filters.

### CODE REVIEW

**Comment by khotcholava** [comment]
NOTE: 

**!!! Not yet ready for review !!!**

**Review by mikerodonnell89 — CHANGES_REQUESTED** [review]
Two things in this screenshot:

- [object Object]
- I think we need the compact button

Screenshot 2024-10-24 at 12 58 24 PM

**Comment by InnaAtanasova** [comment]
Still shows [object Object]
Screenshot 2024-10-28 at 9 45 38 AM

**Review by mikerodonnell89 — APPROVED** [review]

**Comment by do-oel** [comment]
Thanks for this fix! Highly appreciated. 

Two smaller things for improvement:
1. The filter info bar shows an index number in front of the filter term. This should be hidden (e.g, Filtered by: StatusColor (**0:** positive)
2. The category name is using no spaces, this seems a bit weird (e.g, **StatusColor** instead of Status Color)


image

**Pull request merged**
