### PR TITLE
fix: (Platform) fix StackBlitz examples

### PR DESCRIPTION
**Pull request by Betrozov**
#### Please provide a link to the associated issue.
https://github.com/SAP/fundamental-ngx/issues/4392
#### Please provide a brief summary of this pull request.
Fixed StackBlitz examples:
- Feed Input
- File Uploader
- Input
- Object Attribute
- Object Marker
- Panel
- Search Field
- Step Input
- Switch
- Textarea
#### Please check whether the PR fulfills the following requirements

- [X] the commit message follows the guideline:
https://github.com/SAP/fundamental-ngx/blob/main/CONTRIBUTING.md
- [X] all items on the PR Review Checklist are addressed :
https://github.com/SAP/fundamental-ngx/wiki/PR-Review-Checklist

Documentation checklist:
- [X] Documentation Examples
- [X] Stackblitz works for all examples

### CODE REVIEW

**Review by InnaAtanasova — APPROVED** [review]
I trust you all examples are working :D 
Maybe change it to `fix` as you change a scss file from the lib?

**Comment by KevinOkamoto** [comment]
When running Stackblitz for the Combobox component, I'm seeing the following error:

Screen Shot 2021-01-25 at 11 06 24 AM

The other components in this PR are running fine.

**Comment by Betrozov** [comment]
> When running Stackblitz for the Combobox component, I'm seeing the following error:
> 
> Screen Shot 2021-01-25 at 11 06 24 AM
> 
> The other components in this PR are running fine.

@KevinOkamoto 
This PR doesn't include fixes for the Combobox.
For Combobox, we have a different PR
https://github.com/SAP/fundamental-ngx/pull/4469

**Review by KevinOkamoto — APPROVED** [review]

**Comment by KevinOkamoto** [comment]
> @KevinOkamoto
> This PR doesn't include fixes for the Combobox.
> For Combobox, we have a different PR
> #4469

Sorry about that. I was looking at the issue (#4392) when going through the documentation examples.

**Review by mikerodonnell89 — APPROVED** [review]

**Pull request merged**
