### PR TITLE
fix(core,platform): table defect hunting issues

### LINKED ISSUE #8409: Defect Hunting: Platform Table bugs
#### Is this a bug, enhancement, or feature request?
bug

#### Briefly describe your proposal.
- [ ] Platform Table (Safari) - in HCW should we have the text shadow? (ask design)
Screen Shot 2021-09-14 at 11 26 03 AM

- [ ] Table platform - not all the examples acts on Content Density switcher(especially condensed)

- [ ] table platform has some misalignments in diff. browsers 
Chrome
Screen Shot 2022-02-14 at 22 51 24
FF
Screen Shot 2022-02-14 at 22 51 17

- [ ] Column Resize Indicator is not removed in DXP - `/dxp/ngx-dxp/issues/149` - it works properly on our doc site. Investigate what could be the root cause

### PR DESCRIPTION
**Pull request by N1XUS**
## Related Issue(s)

closes #8409 

## Description
- Fixed content density for table & CDK example in core;
- Fixed Resizable handle visibility
- Added option to completely disable resize by dragging

##### During Implementation

1. Visual Testing:

-   [x] visual misalignments/updates
-   [x] check Light/Dark/HCB/HCW themes
-   [x] RTL/LTR - proper rendering and labeling
-   [x] responsiveness(resize)
-   [x] Content Density (Cozy/Compact/(Condensed))
-   [x] States - hover/disabled/focused/active/on click/selected/selected hover/press state
-   [x] Interaction/Animation - open/close, expand/collapse, add/remove, check/uncheck
-   [x] Mouse vs. Keyboard support
-   [x] Text Truncation

2. API and functional correctness

-   [x] check for console logs (warnings, errors)
-   [x] API boundary values
-   [x] different combinations of components - free style
-   [x] change the API values during testing

3. Documentation and Example validations

-   [x] missing API documentation or it is not understandable
-   [x] poor examples
-   [x] Stackblitz works for all examples

4. Accessibility testing
5. Browser Testing - Edge, Safari, Chrome, Firefox

##### PR Quality

-   [x] the commit message(s) follows the guideline:
        https://github.com/SAP/fundamental-ngx/blob/main/CONTRIBUTING.md
-   [x] tests for the changes that have been done
-   [x] all items on the PR Review Checklist are addressed :
        https://github.com/SAP/fundamental-ngx/wiki/PR-Review-Checklist
-   [x] Run npm run build-pack-library and test in external application
-   [x] update `README.md`
-   [x] [Breaking Changes Wiki](https://github.com/SAP/fundamental-ngx/wiki/Breaking-Changes)

### CODE REVIEW

**Review by mikerodonnell89 — COMMENTED** [review]
Input and buttons in the toolbar are also not responding to content density switcher

Screen Shot 2022-09-07 at 10 23 00 AM

**Review by mikerodonnell89 — COMMENTED** [review]
Also looks like most tables in the documentation respond to switching between cozy and compact, but are not responding to switching to condensed? A few do display condensed mode but most don't

**Comment by N1XUS** [comment]
> Also looks like most tables in the documentation respond to switching between cozy and compact, but are not responding to switching to condensed? A few do display condensed mode but most don't

Hey Mike. Could you please clarify which tables are responding to condensed mode?

**Review by platon-rov — COMMENTED** [review]
Missing condensed
* (Core) Table With Semantic Row Highlighting
* (Core) Table with Angular CDK

Forced `fdCompact` for some reason, i think we can remove it
* (Platform) Semantic Highlighting
* (Platform) Row custom CSS class

**Comment by N1XUS** [comment]
@platon-rov thanks. Semantic row reacts on condensed density. The issue is with the checkboxes inside. They don't support such state, thats why they go to compact mode, thus, the view is looks like for compact. Other examples has been fixed

**Review by mikerodonnell89 — APPROVED** [review]

**Pull request merged**
