### PR TITLE
fix(core): date picker accessibility

### PR DESCRIPTION
**Pull request by dimamarksman**
## Related Issue(s)

closes https://github.com/sap/fundamental-ngx/issues/6214

## Description

This PR provides some accessibility fixes for core date-time picker component

##### During Implementation

1. Visual Testing:

-   [x] visual misalignments/updates
-   [x] check Light/Dark/HCB/HCW themes
-   [x] RTL/LTR - proper rendering and labeling
-   [x] responsiveness(resize)
-   [x] Content Density (Cozy/Compact/(Condensed))
-   [x] States - hover/disabled/focused/active/on click/selected/selected hover/press state
-   [x] Interaction/Animation - open/close, expand/collapse, add/remove, check/uncheck
-   [x] Mouse vs. Keyboard support
-   [x] Text Truncation

2. API and functional correctness

-   [x] check for console logs (warnings, errors)
-   [x] API boundary values
-   [na] different combinations of components - free style
-   [x] change the API values during testing

3. Documentation and Example validations

-   [x] missing API documentation or it is not understandable
-   [x] poor examples
-   [x] Stackblitz works for all examples

4. Accessibility testing
5. Browser Testing - Edge, Safari, Chrome, Firefox

##### PR Quality

-   [x] the commit message(s) follows the guideline:
        https://github.com/SAP/fundamental-ngx/blob/main/CONTRIBUTING.md
-   [x] tests for the changes that have been done
-   [x] all items on the PR Review Checklist are addressed :
        https://github.com/SAP/fundamental-ngx/wiki/PR-Review-Checklist
-   [x] Run npm run build-pack-library and test in external application
-   [na] update `README.md`
-   [na] [Breaking Changes Wiki](https://github.com/SAP/fundamental-ngx/wiki/Breaking-Changes)

### CODE REVIEW

**Review by mikerodonnell89 — DISMISSED** [review]
Couple issues observed with the Chrome screenreader:

- When I open the datepicker grid by clicking the calendar icon, the current selected date is read correctly but then "December, select month button" is read.  I have not focused the month selection button or moved the mouse away from the calendar icon
- Re: issue 3, when I open the range datepicker grid, only the range start is read (followed by the previous problem above).  Range end is not mentioned

**Comment by dimamarksman** [comment]
> * Re: issue 3, when I open the range datepicker grid, only the range start is read (followed by the previous problem above).  Range end is not mentioned

I don't see the requirement that end-date has to be read. The screen reader reads only focused cell.
You can observe similar behavior on [sapui date-range example](https://sapui5.hana.ondemand.com/#/entity/sap.m.DateRangeSelection/sample/sap.m.sample.DateRangeSelectionValueState)

**Comment by dimamarksman** [comment]
> 



> Couple issues observed with the Chrome screenreader:
> 
> * When I open the datepicker grid by clicking the calendar icon, the current selected date is read correctly but then "December, select month button" is read.  I have not focused the month selection button or moved the mouse away from the calendar icon

Fixed

**Review by dmitry-stepanenko — APPROVED** [review]

**Review by Betrozov — APPROVED** [review]

**Review by InnaAtanasova — APPROVED** [review]

**Comment by Sanjay-1312** [comment]
Issue 1: Fixed.

Issue 2: Fixed.

Issue 3: Fixed.

Issue 4: Fixed.

Retest details:
https://deploy-preview-7324--fundamental-ngx.netlify.app/#/core/date-picker
JAWS 2021

**Pull request merged**
