### PR TITLE
fix: (Platform) adding button pressed markup to panel documentation

### PR DESCRIPTION
**Pull request by krosenk729**
#### Please provide a link to the associated issue.
fixes: https://github.com/SAP/fundamental-ngx/issues/3493

#### Please provide a brief summary of this pull request.
adding button pressed markup to panel documentation

#### Please check whether the PR fulfills the following requirements

- [x] the commit message follows the guideline:
https://github.com/SAP/fundamental-ngx/blob/master/CONTRIBUTING.md
- [x] tests for the changes that have been done
- [x] all items on the PR Review Checklist are addressed :
https://github.com/SAP/fundamental-ngx/wiki/PR-Review-Checklist

Documentation checklist:
- [x] update `README.md`
- [x] [Breaking Changes Wiki](https://github.com/SAP/fundamental-ngx/wiki/Breaking-Changes)
- [x] Documentation Examples
- [x] Stackblitz works for all examples

### CODE REVIEW

**Review by Betrozov — APPROVED** [review]

**Review by mikerodonnell89 — APPROVED** [review]

**Review by JKMarkowski — APPROVED** [review]

**Review by KevinOkamoto — APPROVED** [review]

**Comment by droshev** [comment]
@krosenk729 Thank you for your PR! Would you mind singing the CLA so we can merge the PR?

**Comment by krosenk729** [comment]
@droshev done! sorry for the delay - had to use a different browser for it :) 

could you add a `hacktoberfest-accepted` label to this PR? no worries if you all aren't participating and the answer is 'no'

thanks again

**Comment by droshev** [comment]
> @droshev done! sorry for the delay - had to use a different browser for it :)
> 
> could you add a `hacktoberfest-accepted` label to this PR? no worries if you all aren't participating and the answer is 'no'
> 
> thanks again

@krosenk729 
I added the label, the CLA seems not kicking

**Comment by droshev** [comment]
@krosenk729 - can you re-try CLA? i know sometimes it doesn't kick in

**Comment by krosenk729** [comment]
@droshev   done! it's still pending. is there anything else I should try? thanks

**Comment by KharitonOff** [comment]
The commits in this PR are made by @katherinefhc. @krosenk729 please, make sure that @katherinefhc signs the CLA too.

**Comment by katherinefhc** [comment]
fixed! thanks for your patience

**Pull request merged**
