### PR TITLE
feat(i18n): added new languages [Translation Delivery]

### PR DESCRIPTION
**Pull request by service-tip-git**
Translation Delivery

### CODE REVIEW

**Comment by service-tip-git** [comment]
This pull request is for translation delivery. Please review and approve them.

**Comment by service-tip-git** [comment]
This pull request is for translation delivery. Please review and approve them.

**Comment by service-tip-git** [comment]
This pull request is for translation delivery. Please review and approve them.

**Comment by g-cheishvili** [comment]
Created different PR with the content of this and renamed commits

**Pull request closed without merging**
