### PR TITLE
feat(btp): navigation component implementation

### PR DESCRIPTION
**Pull request by g-cheishvili**
## Related Issue(s)

closes

## Description
Implementing [BTP navigation](https://fundamental-styles.netlify.app/?path=/docs/sap-fiori-btp-navigation-horizontal-navigation--docs) component, along with the `@fundamental-ngx/btp` library

### CODE REVIEW

**Comment by InnaAtanasova** [comment]
Issue with the arrow in Sharing item. The arrow should change for collapsed/expanded states
https://github.com/SAP/fundamental-ngx/assets/39598672/3fe05b46-50f2-4129-9675-3300e4c79357

**Comment by InnaAtanasova** [comment]
Some CSS is broken for the spacing between the items
Screenshot 2023-10-13 at 11 28 50 AM

How it looks like in fund-styles:
Screenshot 2023-10-13 at 11 28 13 AM

**Comment by InnaAtanasova** [comment]
Screenshot 2023-10-13 at 11 31 06 AM

the offset of the menu is not correct. The arrow should be outside of the button, now it looks like it's attached to the button icon

**Comment by InnaAtanasova** [comment]
There's a css issue with the Home item in snapped version 
Screenshot 2023-10-13 at 11 31 28 AM

https://github.com/SAP/fundamental-ngx/assets/39598672/812681a9-bfc9-4852-bb16-816a09947864

**Comment by InnaAtanasova** [comment]
Could you add to one of the examples the spacer in the main navigation so people know they can use it to add more space?

**Comment by InnaAtanasova** [comment]
The phone and tablet modes are missing from the examples. There should be at least a mention of this property in the documentation, so developers are aware of this prop and use it in the responsive design.

**Review by droshev — APPROVED** [review]
We agreed to merge and address the improvements in another PR

**Pull request merged**
