### PR TITLE
feat(btp): horizontal navigation

### LINKED ISSUE #10670: Implement BTP Horizontal Navigation component
- [x] Update fd-styles to the latest design (e.g. two-click area) - https://github.com/SAP/fundamental-styles/pull/4997
- [ ] Bring the Horizontal Navigation to the library under BTP package

### PR DESCRIPTION
**Pull request by N1XUS**
## Related Issue(s)

closes #10670

## Description
- Added `horizontal` navigation modifier;
- Refactored navigation component and it's child components to support horizontal layout;
- Refactored keyboard navigation to support vertical and horizontal navigation;
- Added ability to define custom "More" button.

### After:
image

##### During Implementation

1. Visual Testing:

-   [x] visual misalignments/updates
-   [x] check Light/Dark/HCB/HCW themes
-   [x] RTL/LTR - proper rendering and labeling
-   [x] responsiveness(resize)
-   [x] Content Density (Cozy/Compact/(Condensed))
-   [x] States - hover/disabled/focused/active/on click/selected/selected hover/press state
-   [x] Interaction/Animation - open/close, expand/collapse, add/remove, check/uncheck
-   [x] Mouse vs. Keyboard support
-   [x] Text Truncation

2. API and functional correctness

-   [x] check for console logs (warnings, errors)
-   [x] API boundary values
-   [x] different combinations of components - free style
-   [x] change the API values during testing

3. Documentation and Example validations

-   [x] missing API documentation or it is not understandable
-   [x] poor examples
-   [x] Stackblitz works for all examples

4. Accessibility testing
5. Browser Testing - Edge, Safari, Chrome, Firefox

##### PR Quality

-   [x] the commit message(s) follows the guideline:
        https://github.com/SAP/fundamental-ngx/blob/main/CONTRIBUTING.md
-   [x] tests for the changes that have been done
-   [x] all items on the PR Review Checklist are addressed :
        https://github.com/SAP/fundamental-ngx/wiki/PR-Review-Checklist
-   [x] Run npm run build-pack-library and test in external application
-   [x] update `README.md`
-   [x] [Breaking Changes Wiki](https://github.com/SAP/fundamental-ngx/wiki/Breaking-Changes)

### CODE REVIEW

**Review by mikerodonnell89 — CHANGES_REQUESTED** [review]
This is looking really good. I did notice this overflow popover isn't displaying anything:

Screenshot 2023-12-27 at 2 33 47 PM

**Comment by mikerodonnell89** [comment]
Is it intentional to allow both "Basket" and "Settings" display as selected at the same time? I understand for "Basket" it comes from the `selected` attribute and for "Settings" it comes from `routerLink` being the current page, just wondering if it is intentional to allow two items in the nav to display as selected simultaneously

**Comment by N1XUS** [comment]
@mikerodonnell89 please re-check

**Comment by InnaAtanasova** [comment]
Screenshot 2024-01-02 at 11 31 05 AM

When the children list is expanded the button gets a selected state (but shouldn't)

**Review by InnaAtanasova — CHANGES_REQUESTED** [review]
The a11y roles for the component should be revisited. Per latest design specs we should treat this component as "restyled Icon Tab Bar component", which means we should have the same roles, aria-posinset, aria-setsize,

**Comment by droshev** [comment]
waiting for a signed off a11y spec

**Comment by droshev** [comment]
closing it until we have the final design a11y spec

**Pull request closed without merging**
