### PR TITLE
feat(cdk,platform): dnd predicate

### LINKED ISSUE #9718: [Sourcing] <fdp-table> Prevent DND between rows
#### Is this a bug, enhancement, or feature request?

enhancement

#### Briefly describe your proposal.

For DnD, UI is always changed before we can validate which row can be dropped. For example, in table having folders and files, file cannot be dropped on another file, but the UI will still reflect the change from dnd. For now, our workaround is to refresh the whole table to revert the change if we detect that the a dropRow should not be droppable by the dragged row from emitted event. It would be helpful if we can have more control on the UI change for dnd through object property or the emitted event to have some validation between dragged and dropped rows before making change on UI.

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)

Latest

### PR DESCRIPTION
**Pull request by N1XUS**
## Related Issue(s)

closes #9718

## Description
- Added `dragoverPredicate` and `dropPredicate` input function to define whether the item can be dropped onto another item;
- Moved `async-strategy` from `@fundamental-ngx/platform/shared` to `@fundamental-ngx/cdk/utils`;
- Added `dragoverPredicate` and `dropPredicate` for platform table and updated tree example;
- Updated all platform table examples to use `OnPush` strategy;
- Ejected helper methods into a separate functions from the table component;
- Optimised change detection for toolbar configuration;

##### During Implementation

1. Visual Testing:

-   [x] visual misalignments/updates
-   [x] check Light/Dark/HCB/HCW themes
-   [x] RTL/LTR - proper rendering and labeling
-   [x] responsiveness(resize)
-   [x] Content Density (Cozy/Compact/(Condensed))
-   [x] States - hover/disabled/focused/active/on click/selected/selected hover/press state
-   [x] Interaction/Animation - open/close, expand/collapse, add/remove, check/uncheck
-   [x] Mouse vs. Keyboard support
-   [x] Text Truncation

2. API and functional correctness

-   [x] check for console logs (warnings, errors)
-   [x] API boundary values
-   [x] different combinations of components - free style
-   [x] change the API values during testing

3. Documentation and Example validations

-   [x] missing API documentation or it is not understandable
-   [x] poor examples
-   [x] Stackblitz works for all examples

4. Accessibility testing
5. Browser Testing - Edge, Safari, Chrome, Firefox

### CODE REVIEW

**Comment by mikerodonnell89** [comment]
Failing test appears to be relevant: https://github.com/SAP/fundamental-ngx/actions/runs/5070119085/jobs/9104721307?pr=9921#step:7:12121

**Review by mikerodonnell89 — DISMISSED** [review]
Noticed this when playing around with drag and drop, does not happen on the main branch. Drag astro laptop so it is a child of benda laptop. Then try to drag astro laptop between benda, and the parent laptops, so it should go back to its initial state. Then you will see 2 benda laptops

https://github.com/SAP/fundamental-ngx/assets/2471874/23765a34-7646-463d-ab1f-0e5dc5f3e4c7

**Comment by mikerodonnell89** [comment]
Ignore my force push above. Pushed things to the wrong branch, reset to your latest commit

**Review by mikerodonnell89 — COMMENTED** [review]
Looks like I had a pending suggestion that didn't post

**Comment by InnaAtanasova** [comment]
When I try to move `Other 3` in `Laptops` it doesn't work and the `Laptops` row gets a blue background
https://github.com/SAP/fundamental-ngx/assets/39598672/ce96ee73-d146-484a-b520-7bdcd0ae3bb9

**Comment by N1XUS** [comment]
@InnaAtanasova fixed

**Review by g-cheishvili — CHANGES_REQUESTED** [review]
just minor things

**Comment by InnaAtanasova** [comment]
Minor visual issue. 
Screenshot 2023-05-29 at 11 03 58 AM

**Review by InnaAtanasova — APPROVED** [review]

**Review by InnaAtanasova — APPROVED** [review]

**Pull request merged**
