### PR TITLE
fix: applyCssClass value initialization

### PR DESCRIPTION
**Pull request by salarenko**
#### Please provide a link to the associated issue.
Closes: #3181

#### Please provide a brief summary of this pull request.
This PR brings:
- Proper initialization of `_classMap[this._uuidv4]` value, previously initialized with nested array instead of an array
- Proper typing for `updateComponentClassList(..., previousComponentClassList,..)` argument

#### Please check whether the PR fulfills the following requirements

- [x] the commit message follows the guideline:
https://github.com/SAP/fundamental-ngx/blob/master/CONTRIBUTING.md
- [x] tests for the changes that have been done
- [x] all items on the PR Review Checklist are addressed :
https://github.com/SAP/fundamental-ngx/wiki/PR-Review-Checklist

Documentation checklist:
- [x] update `README.md`
- [x] [Breaking Changes Wiki](https://github.com/SAP/fundamental-ngx/wiki/Breaking-Changes)
- [x] Documentation Examples
- [x] Stackblitz works for all examples

### CODE REVIEW

**Comment by dimamarksman** [comment]
would be good to add proper typing for `firstCommonElementIndex` as well
https://github.com/SAP/fundamental-ngx/blob/e95e4a5c709f0b857df24b333d990347824e47f1/libs/core/src/lib/utils/decorators/apply-css-class.decorator.ts#L51

**Comment by dimamarksman** [comment]
Looking at function signature and naming:
https://github.com/SAP/fundamental-ngx/blob/e95e4a5c709f0b857df24b333d990347824e47f1/libs/core/src/lib/utils/decorators/apply-css-class.decorator.ts#L51-L54
There are some things in this function that are not clear for me:
- Why we try to find index in the second array and not first
- Should this function be responsible for rounding `index === -1 ? 0 : index`

**Comment by salarenko** [comment]
@dimamarksman 
- added argument typing for `firstCommonElementIndex`
- I had similar concenrs to index "rounding", moved out of the function
- you are right this should be `arr1.(arr2)` not `arr2.(arr1)`

I also added some logic to split multiple classes merged into one string
(`['class1', 'class2 class3', 'class4']` => `['class1', 'class2', 'class3', 'class4']`)

**Comment by InnaAtanasova** [comment]
@dimamarksman let us know if you think the PR is ok (I'm not sure if you can approve it :) If you can, please approve)

**Comment by InnaAtanasova** [comment]
LGTM

**Comment by dimamarksman** [comment]
LGTM,
I'm not able to approve.

**Review by JKMarkowski — APPROVED** [review]

**Pull request merged**
