### PR TITLE
fix(core): static dialog nobackdrop position fix

### LINKED ISSUE #5034: bug: dialog (core) - for playground example, static dialog leaves example area and covers page nav bar
#### Is this a bug, enhancement, or feature request?
bug

#### Briefly describe your proposal.
static playground example should be in the content area

#### If this is a bug, please provide steps for reproducing it.
**STR:**
1. go to https://fundamental-ngx.netlify.app/#/core/dialog
2. scroll down to the playground example
3. click to uncheck 'hasBackdrop'
4. click to open dialog
5. look at dialog

**Actual results:** 
- dialog covers navigation menu
- dialog not in content area

**expected results:** dialog will not cover nav menu and will be in the content are

Peek 2021-03-29 15-17

Screenshot at 2021-03-29 15-18-50
Screenshot at 2021-03-29 15-18-34

### LINKED ISSUE #5286: Dialog with no backdrop is not positioned in the middle of the screen
#### Is this a bug, enhancement, or feature request?
Bug
#### Briefly describe your proposal.
Dialog with no backdrop is not positioned in the middle of the screen

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
0.29.1
#### If this is a bug, please provide steps for reproducing it.
Create a Dialog and set the `hasBackdrop` property in the config object to `false`. 
```
const dialogRef = this._dialogService.open(dialog, { 
          hasBackdrop: false
});
```

This is how the dialog is positioned:
Screen Shot 2021-05-04 at 1 38 40 PM

This is how it's positioned with backdrop:
Screen Shot 2021-05-04 at 1 38 21 PM

### PR DESCRIPTION
**Pull request by xandrio**
#### Please provide a link to the associated issue.
Closes #5034 
Closes #5286 

#### Please provide a brief summary of this pull request.
added styles for modal window position (only for body based modal)

#### Please check whether the PR fulfills the following requirements

- [x] the commit message follows the guideline:
https://github.com/SAP/fundamental-ngx/blob/main/CONTRIBUTING.md
- [x] tests for the changes that have been done
- [x] all items on the PR Review Checklist are addressed :
https://github.com/SAP/fundamental-ngx/wiki/PR-Review-Checklist
- [x] Run npm run build-pack-library and test in external application

Documentation checklist:
- [x] update `README.md`
- [x] [Breaking Changes Wiki](https://github.com/SAP/fundamental-ngx/wiki/Breaking-Changes)
- [x] Documentation Examples
- [x] Stackblitz works for all examples

### CODE REVIEW

**Comment by puru-hk** [comment]
**5043:**

Tested in this url https://deploy-preview-5626--fundamental-ngx.netlify.app/#/core/dialog. but the in the dailog content is not properly aligned.

Screen shot:



Expected:

**Comment by puru-hk** [comment]
#5286 Is fixed.

**Comment by Seamoo13** [comment]
@xandrio PRs should receive dev review and approval before getting the `ready for qa` label.

**Comment by xandrio** [comment]
> **5043:**
> 
> Tested in this url https://deploy-preview-5626--fundamental-ngx.netlify.app/#/core/dialog. but the in the dailog content is not properly aligned.
> 
> Screen shot:
> 
> 
> 
> Expected:
> 
> 

I will update configuration then, we can turn on or turn off left-right padding at configuration, but I guess we need to create new issue.

**Review by kavya-b — APPROVED** [review]
LGTM

**Review by InnaAtanasova — CHANGES_REQUESTED** [review]
Should be done in fund-styles

**Review by aberikashvili — COMMENTED** [review]
I see this PR has `tests for the changes that have been done` checked, but I don't see any edited `.spec.ts` file in code changes

**Pull request closed without merging**
