### PR TITLE
fix: implement fundamental-styles version 0.11

### PR DESCRIPTION
**Pull request by katekozlowska**
#### Please provide a link to the associated issue.

closes https://github.com/SAP/fundamental-ngx/pull/3027

#### Please provide a brief summary of this pull request.

breaking changes:
- removed select-native component
- removed Identifier (use Avatar instead)
- removed Image component (use Avatar instead)
- removed dropdown component

#### Please check whether the PR fulfills the following requirements

- [x] the commit message follows the guideline:
https://github.com/SAP/fundamental-ngx/blob/master/CONTRIBUTING.md
- [x] tests for the changes that have been done
- [x] all items on the PR Review Checklist are addressed :
https://github.com/SAP/fundamental-ngx/wiki/PR-Review-Checklist

Documentation checklist:
- [x] update `README.md`
- [x] [Breaking Changes Wiki](https://github.com/SAP/fundamental-ngx/wiki/Breaking-Changes)
- [x] Documentation Examples
- [x] Stackblitz works for all examples

### CODE REVIEW

**Comment by JKMarkowski** [comment]
Only one thing left there and we will be good to merge

**Comment by stefanoScalzo** [comment]
Screen Shot 2020-08-24 at 1 47 03 PM

**Comment by stefanoScalzo** [comment]
Screen Shot 2020-08-24 at 1 48 55 PM
something is wrong with the background images

**Comment by stefanoScalzo** [comment]
Screen Shot 2020-08-24 at 1 51 49 PM
menu items have focus on hover

**Comment by stefanoScalzo** [comment]
Screen Shot 2020-08-24 at 1 55 07 PM
split button focus is off

**Comment by droshev** [comment]
> Screen Shot 2020-08-24 at 1 55 07 PM
> split button focus is off

this is not an issue in ngx, it is coming from styles

**Comment by katekozlowska** [comment]
https://github.com/SAP/fundamental-ngx/pull/3073#issuecomment-679272584

fixed

**Pull request merged**
