### PR TITLE
fix: (Core) InputGroup editing text in disabled state

### PR DESCRIPTION
**Pull request by olshansky**
#### Please provide a link to the associated issue.
Closes: https://github.com/SAP/fundamental-ngx/issues/4230
#### Please check whether the PR fulfills the following requirements

- [x] the commit message follows the guideline:
https://github.com/SAP/fundamental-ngx/blob/main/CONTRIBUTING.md
- [n/a] tests for the changes that have been done
- [x] all items on the PR Review Checklist are addressed :
https://github.com/SAP/fundamental-ngx/wiki/PR-Review-Checklist

Documentation checklist:
- [n/a] update `README.md`
- [n/a] [Breaking Changes Wiki](https://github.com/SAP/fundamental-ngx/wiki/Breaking-Changes)
- [x] Documentation Examples
- [x] Stackblitz works for all examples

### CODE REVIEW

**Review by Betrozov — APPROVED** [review]

**Review by kavya-b — APPROVED** [review]

**Review by InnaAtanasova — APPROVED** [review]

**Comment by InnaAtanasova** [comment]
Screen Shot 2021-01-08 at 10 54 54 AM

It's not described in the issue this PR is fixing but disabled Input Group Search has 2 other problems:
1. You can still focus it
2. The focus is around the whole element AND on the button. IMO it should not focus the button, only the input and when you tab again the focus should go on the button
Do you know if there's an issue about this?

**Comment by olshansky** [comment]
> It's not described in the issue this PR is fixing but disabled Input Group Search has 2 other problems:
> 
> 1. You can still focus it
> 2. The focus is around the whole element AND on the button. IMO it should not focus the button, only the input and when you tab again the focus should go on the button
>    Do you know if there's an issue about this?

@InnaAtanasova I believe you are right. Fixed

**Comment by JKMarkowski** [comment]
InputGroup/Button are still focusable - also button can be clicked inside. 

Peek 2021-01-11 14-14

**Comment by olshansky** [comment]
> InputGroup/Button are still focusable - also button can be clicked inside. - I see that it's not scope of the issue it fixes, but can you fix it there?

@JKMarkowski button should be just not clickable or not focusable? And should the input be focusable?

**Comment by JKMarkowski** [comment]
> button should be just not clickable or not focusable? And should the input be focusable?

@olshansky I think button shouldn't be focusable/clickable + input shouldn't be focusable as well - like on basic [disabled input](https://fundamental-ngx.netlify.app/#/core/input#reactive-form-input) . @InnaAtanasova What do you think about it?

**Comment by InnaAtanasova** [comment]
> > button should be just not clickable or not focusable? And should the input be focusable?
> 
> @olshansky I think button shouldn't be focusable/clickable + input shouldn't be focusable as well - like on basic [disabled input](https://fundamental-ngx.netlify.app/#/core/input#reactive-form-input) . @InnaAtanasova What do you think about it?

In my opinion neither the input nor the button should be clickable or focusable in disabled state

**Comment by olshansky** [comment]
> > > button should be just not clickable or not focusable? And should the input be focusable?
> > 
> > 
> > @olshansky I think button shouldn't be focusable/clickable + input shouldn't be focusable as well - like on basic [disabled input](https://fundamental-ngx.netlify.app/#/core/input#reactive-form-input) . @InnaAtanasova What do you think about it?
> 
> In my opinion neither the input nor the button should be clickable or focusable in disabled state

But what if the disabled state is the sort of "middle" state? Here is a pretty familiar use-case https://ux.stackexchange.com/questions/103239/should-disabled-elements-be-focusable-for-accessibility-purposes

**Comment by InnaAtanasova** [comment]
> > > > button should be just not clickable or not focusable? And should the input be focusable?
> > > 
> > > 
> > > @olshansky I think button shouldn't be focusable/clickable + input shouldn't be focusable as well - like on basic [disabled input](https://fundamental-ngx.netlify.app/#/core/input#reactive-form-input) . @InnaAtanasova What do you think about it?
> > 
> > 
> > In my opinion neither the input nor the button should be clickable or focusable in disabled state
> 
> @InnaAtanasova @JKMarkowski But what if the disabled state is the sort of "middle" state? Here is a pretty familiar use-case https://ux.stackexchange.com/questions/103239/should-disabled-elements-be-focusable-for-accessibility-purposes

@olshansky the discussion you sent makes sense. I am not an a11y expert and can't comment more on this issue. We wrote and asked for an external opinion and will let you know when we get an answer. In Fundamental-NGX when we have a disabled component/element we don't focus it by TAB, that's how all components are implemented so far.

**Comment by olshansky** [comment]
> @olshansky the discussion you sent makes sense. I am not an a11y expert and can't comment more on this issue. We wrote and asked for an external opinion and will let you know when we get an answer. In Fundamental-NGX when we have a disabled component/element we don't focus it by TAB, that's how all components are implemented so far.

Ok, thank you as usual 😊

**Review by JKMarkowski — APPROVED** [review]

**Pull request merged**
