### PR TITLE
fix: (platform) Fixing console errors on platform Form Component pages

### PR DESCRIPTION
**Pull request by KevinOkamoto**
Also fixing platform unit tests.

#### Please provide a link to the associated issue.
https://github.com/SAP/fundamental-ngx/issues/2960

#### Please provide a brief summary of this pull request.

Fixing following errors on Platform: Checkbox documentation page:

```
core.js:4196 ERROR Error: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: '{}'. Current value: '{
  "red": false,
  "blue": true
}'.
```

#### Please check whether the PR fulfills the following requirements

- [x] the commit message follows the guideline:
https://github.com/SAP/fundamental-ngx/blob/master/CONTRIBUTING.md
- [x] tests for the changes that have been done
- [x] all items on the PR Review Checklist are addressed :
https://github.com/SAP/fundamental-ngx/wiki/PR-Review-Checklist

Fix provided:
Issue: FormGroup doesn't broadcast when it's fields are updated.
Fix: Need to add timeout here and store the form value in variable.

### CODE REVIEW

**Comment by DeepakSap14** [comment]
I have pushed same solution for other affected form components. Checkbox Group, Radio Group and switch.

**Comment by fkolar** [comment]
Can you describe what was the actual fix for this ?

**Comment by DeepakSap14** [comment]
> Can you describe what was the actual fix for this ?
Issue: when we are printing form value on html in case of component signature using [formControl]="fl.formControl". we are getting Expression changes error on form value.

Problem identified:
FormGroup doesn't broadcast when it's fields are updated, in case we use [formControl]="fl.formControl" in component signature. 
so by adding method on **change** event from component and then storing form value to print.
like:
in .ts file
public changeFunction(): void {
        this.result = this.customForm.getRawValue();
    }
in .html
<fdp-checkbox (change)="changeFunction()" > </fdp-checkbox>

**Comment by fkolar** [comment]
Does this happends also for input?

**Comment by DeepakSap14** [comment]
> Does this happends also for input?

Yes it happens for input as well. currently in input docs page, we are not printing form value. so this error is not coming.
when i tried printing form value in "apps/docs/src/app/platform/component-docs/platform-forms/platform-input/platform-input-example/platform-input-example.component.html" by using below code.
`form value: {{ this.formTypesGroupRegister.value | json }}`

following error is coming.

Screenshot 2020-08-10 at 7 55 42 PM

**Comment by DeepakSap14** [comment]
A cleaner approach where change detection is triggered in ngAfterViewInit life cycle. This solves our issue.

**Comment by fkolar** [comment]
@DeepakSap14 

When you say: 

```
Fix provided:
Issue: FormGroup doesn't broadcast when it's fields are updated.
Fix: Need to add timeout here and store the form value in variabl
```

FormGroup does not broadcast any fields changes, its a control responsibility and FormField listen for this changes

**Comment by fkolar** [comment]
Can you try to call detect changes here instead :
it inside the form Field. 
Also check when you set new valu if you call stateChanges.emit so this formField parent to detect the change

```
 if (this._control && this._control.ngControl && this._control.ngControl.valueChanges) {
            this._control.ngControl.valueChanges.pipe(takeUntil(this._destroyed)).subscribe((v) => {
                // this.onChange.emit('valueChangess');
                this._cd.markForCheck();
            });
        }

```

**Comment by DeepakSap14** [comment]
> Can you try to call detect changes here instead :
> it inside the form Field.
> Also check when you set new valu if you call stateChanges.emit so this formField parent to detect the change
> 
> ```
>  if (this._control && this._control.ngControl && this._control.ngControl.valueChanges) {
>             this._control.ngControl.valueChanges.pipe(takeUntil(this._destroyed)).subscribe((v) => {
>                 // this.onChange.emit('valueChangess');
>                 this._cd.markForCheck();
>             });
>         }
> ```

stateChanges is already there.
Issue was coming for documentation only. By adding detectChanges in documentation component. it resolves the issue.
@KevinOkamoto

**Pull request closed without merging**
