### PR TITLE
fix: (Core) fix pickers input groupt addon active state

### PR DESCRIPTION
**Pull request by Betrozov**
#### Please provide a link to the associated issue.
Closes SAP/fundamental-ngx#5496

#### Please provide a brief summary of this pull request.
Fixed Date/Datetime/Time picker input groupt addon active state
#### Please check whether the PR fulfills the following requirements

- [X] the commit message follows the guideline:
https://github.com/SAP/fundamental-ngx/blob/main/CONTRIBUTING.md
- [X] tests for the changes that have been done
- [X] all items on the PR Review Checklist are addressed :
https://github.com/SAP/fundamental-ngx/wiki/PR-Review-Checklist
- [X] Run npm run build-pack-library and test in external application

Documentation checklist:
- [X] update `README.md`
- [X] [Breaking Changes Wiki](https://github.com/SAP/fundamental-ngx/wiki/Breaking-Changes)
- [X] Documentation Examples
- [X] Stackblitz works for all examples

### CODE REVIEW

**Comment by dimamarksman** [comment]
@Betrozov I see your fix is about the toggler `active` state but the original issue complains of absent toggler `focus` state

**Review by dimamarksman — APPROVED** [review]

**Comment by platon-rov** [comment]
Please update the link to the appropriate related issue.

**Review by olshansky — APPROVED** [review]

**Comment by Betrozov** [comment]
> Please update the link to the appropriate related issue.

@platon-rov updated

**Review by platon-rov — APPROVED** [review]

**Comment by maxym-valor** [comment]
Tested, approved!

**Review by InnaAtanasova — APPROVED** [review]

**Pull request merged**
