### PR TITLE
fix(core): multi input tokens should not have title attr

### LINKED ISSUE #11675: [P4][Sourcing][Accessibility]Add Content From Sourcing Library-tooltip is not showing the exact text
#### Is this a bug, enhancement, or feature request?
Bug

#### Describe your proposal.
After selecting value from multi input, tooltip is not showing the exact text for the selected values.

#### Can you handle that on the application side
No

#### Which versions of Angular and Fundamental Library for Angular are affected? Please, specify the exact version. (If this is a feature request, use current version.)
Angular: 15
core / platform: 0.43.29

#### If this is a bug, please provide steps for reproducing it; the exact components you are using;
1. Select values from multi input.
2. Mouse over on the selected value.
3. Tooltip should show for the selected value.

#### Please provide relevant source code (if applicable).
https://github.com/SAP/fundamental-ngx/blob/main/libs/core/multi-input/multi-input.component.html

#### Please provide stackblitz example(s).
https://stackblitz.com/edit/6jb1hz?file=src%2Fapp%2Fmulti-input-example.component.ts,src%2Fapp%2Fmulti-input-example.component.html

#### Is there anything else we should know?

**_IMPORTANT: Please refrain from providing links or screenshots of SAP's internal information, as this project is open-source, and its contents are accessible to anyone._**
MC

Screenshot 2024-06-14 at 12 53 15 PM

### PR DESCRIPTION
**Pull request by mikerodonnell89**
fixes #11675

### CODE REVIEW

**Review by InnaAtanasova — APPROVED** [review]

**Comment by InnaAtanasova** [comment]
The issue is reported for Angular 15. You need to open a fix in the ng15 branch, too

**Comment by mikerodonnell89** [comment]
> The issue is reported for Angular 15. You need to open a fix in the ng15 branch, too

So actually the title attribute should never have been set on the tokens. They were added to the main branch only, and the ng15 branch correctly doesn't have them. See my comment here: https://github.com/SAP/fundamental-ngx/issues/11675#issuecomment-2271858613

**Review by dpavlenishvili — APPROVED** [review]

**Comment by droshev** [comment]
@mikerodonnell89 looks like it was added for a reason. The original issue is [this](https://github.com/SAP/fundamental-ngx/issues/10849). Can you double check?

**Comment by mikerodonnell89** [comment]
Waiting for more info from designers before merging this

**Comment by mikerodonnell89** [comment]
After speaking with the designers about this issue, here's what I've learned:

- the only instance in which a token should be truncated is when there is only one selected token. Otherwise, the multi-input will simply display the "_ more" text, and any other tokens that are short enough to fit in the multi-input along with the "_ more" text.
- when there is a truncated token displayed, rather than adding a title attribute, clicking the truncated token will display the multi-input's popover, displaying the full text of the token. Title attributes are not helpful for keyboard or touch screen users

**Pull request merged**
