### PR TITLE
feat(core): message strip alert implementation

### PR DESCRIPTION
**Pull request by g-cheishvili**
## Related Issue(s)

part of #9845 

## Description

Introduced message strip alert functionality and also added autoDismiss feature to cover all use-cases of the `core-alert`.

This PR is not updating horizon 2023 features, because I believe that is a separate PR topic

### CODE REVIEW

**Comment by InnaAtanasova** [comment]
Screenshot 2023-06-09 at 11 30 42 AM
Screenshot 2023-06-09 at 11 30 35 AM

The styling for alert in the middle is off

**Review by mikerodonnell89 — CHANGES_REQUESTED** [review]
Middle actually isn't really close to the middle of the screen: 
Screenshot 2023-06-13 at 3 12 48 PM

**Comment by mikerodonnell89** [comment]
Inna's comments still need to be addressed. Also semi-related side note, but how about some margin between the buttons or some other formatting in the new example? I think we should make an effort to keep the doc pages looking nice with details like that

**Comment by InnaAtanasova** [comment]
> https://deploy-preview-9989--fundamental-ngx.netlify.app

This is still reproducible

**Review by InnaAtanasova — APPROVED** [review]

**Review by mikerodonnell89 — APPROVED** [review]

**Pull request merged**
